//! Simulation Corpus — 215+ labeled content items across 14 categories
//!
//! Each item has per-persona expected outcomes in canonical order:
//! [rust, python, typescript, devops, mobile, bootstrap, power, switcher, niche]

use super::{ContentCategory, ExpectedOutcome, LabeledItem};

// Type aliases for compact notation
type CC = ContentCategory;
type EO = ExpectedOutcome;

// Category shortcuts
const DM: CC = CC::DirectMatch;
const AM: CC = CC::AdjacentMatch;
const CDN: CC = CC::CrossDomainNoise;
const BDL: CC = CC::Borderline;
const CB: CC = CC::CareerNoise;
const SA: CC = CC::SecurityAdvisory;
const INTRO: CC = CC::IntroductoryNoise;
const SHN: CC = CC::ShowHNNoise;
const MT: CC = CC::MetaNoise;
const BC: CC = CC::BusinessNoise;
const RN: CC = CC::ReleaseNotes;
const HI: CC = CC::HNDiscussion;
const DI: CC = CC::DistantlyRelevant;
const RE: CC = CC::ReverseEngineering;

// Outcome shortcuts
const S: EO = EO::StrongRelevant;
const W: EO = EO::WeakRelevant;
const B: EO = EO::MildBorderline;
const N: EO = EO::NotRelevant;
#[allow(dead_code)]
const X: EO = EO::Excluded;

pub(super) fn corpus() -> Vec<LabeledItem> {
    vec![
        // ====================================================================
        // DirectMatch (30) — id 1-30
        // ====================================================================
        LabeledItem { id: 1, category: DM, source_type: "hackernews",
            title: "Rust 2024 Edition: What's New",
            content: "The Rust 2024 edition introduces new language features including improved async support, new syntax for lifetime annotations, and better error messages. This release continues the tradition of zero-cost abstractions.",
            expected: [S, N, N, N, N, N, S, S, B],
        },
        LabeledItem { id: 2, category: DM, source_type: "hackernews",
            title: "Building Desktop Apps with Tauri 2.0",
            content: "Tauri 2.0 brings mobile support, improved plugin system, and a new capabilities-based security model. Build native desktop apps with Rust backend and any web frontend.",
            expected: [S, N, W, N, N, N, S, W, N],
        },
        LabeledItem { id: 3, category: DM, source_type: "reddit",
            title: "SQLite vs PostgreSQL for local-first apps",
            content: "Comparing SQLite and PostgreSQL for applications that prioritize local data storage and offline capability. SQLite wins for embedded use cases.",
            expected: [S, N, W, W, N, N, S, S, N],
        },
        LabeledItem { id: 4, category: DM, source_type: "hackernews",
            title: "tokio async runtime internals explained",
            content: "Deep dive into how tokio's async runtime works: task scheduling, executor pools, IO drivers, and waker mechanics.",
            expected: [S, N, N, N, N, N, S, S, B],
        },
        LabeledItem { id: 5, category: DM, source_type: "hackernews",
            title: "serde: The Rust serialization framework",
            content: "serde remains the de facto standard for serialization in Rust. Learn how derive macros, custom implementations, and the visitor pattern enable zero-copy deserialization.",
            expected: [S, N, N, N, N, N, S, S, B],
        },
        LabeledItem { id: 6, category: DM, source_type: "blog",
            title: "WebAssembly + Rust: Production case study",
            content: "Running Rust compiled to WebAssembly in production: WASM modules for performance-critical browser code and the Wasm component model.",
            expected: [S, N, W, N, N, N, S, W, N],
        },
        LabeledItem { id: 7, category: DM, source_type: "hackernews",
            title: "Memory safety without garbage collection",
            content: "How Rust's ownership model eliminates entire classes of memory bugs: use-after-free, double-free, null pointer dereferences, and data races caught at compile time.",
            expected: [S, N, N, N, N, N, S, S, W],
        },
        LabeledItem { id: 8, category: DM, source_type: "hackernews",
            title: "sqlite-vec: Vector search for SQLite",
            content: "sqlite-vec is a SQLite extension for vector similarity search. Store and query embeddings directly in SQLite using cosine similarity without a separate vector database.",
            expected: [S, W, N, N, N, N, S, S, N],
        },
        LabeledItem { id: 9, category: DM, source_type: "blog",
            title: "Rust error handling with thiserror and anyhow",
            content: "Best practices for error handling in production Rust: thiserror for library errors, anyhow for application errors, the ? operator, and how to provide context.",
            expected: [S, N, N, N, N, N, S, S, B],
        },
        LabeledItem { id: 10, category: DM, source_type: "hackernews",
            title: "Systems programming renaissance: Why Rust matters",
            content: "Rust is reshaping systems programming: Linux kernel modules, embedded systems, OS components, and safety-critical software.",
            expected: [S, N, N, N, N, N, S, S, W],
        },
        LabeledItem { id: 11, category: DM, source_type: "hackernews",
            title: "PyTorch 2.0 performance benchmarks",
            content: "PyTorch 2.0 introduces torch.compile() for dramatic speedups. Benchmarks show 1.5-2x improvement on training workloads with minimal code changes.",
            expected: [N, S, N, N, N, N, S, B, N],
        },
        LabeledItem { id: 12, category: DM, source_type: "hackernews",
            title: "Fine-tuning LLMs with QLoRA",
            content: "QLoRA enables fine-tuning large language models on consumer GPUs using 4-bit quantization and Low-Rank Adaptation.",
            expected: [N, S, N, N, N, N, S, B, N],
        },
        LabeledItem { id: 13, category: DM, source_type: "hackernews",
            title: "Python type hints: The complete guide",
            content: "Python type hints with mypy and pyright. Covers Union types, Protocol, TypeVar, and the new TypeAlias syntax. Static typing dramatically improves code quality.",
            expected: [N, S, N, N, N, W, S, W, N],
        },
        LabeledItem { id: 14, category: DM, source_type: "blog",
            title: "React 19 new features and hooks",
            content: "React 19 ships with the Actions API, use() hook for async rendering, improved server components, and the new React compiler.",
            expected: [N, N, S, N, W, N, S, W, N],
        },
        LabeledItem { id: 15, category: DM, source_type: "hackernews",
            title: "TypeScript 5.4 satisfies and template literals",
            content: "TypeScript 5.4 improves narrowing in closures, adds the NoInfer utility type, and enhances template literal type inference.",
            expected: [N, N, S, N, W, W, S, W, N],
        },
        LabeledItem { id: 16, category: DM, source_type: "hackernews",
            title: "Kubernetes 1.30: What's new for operators",
            content: "Kubernetes 1.30 brings improvements to the operator pattern: better CRD validation, improved leader election, and new admission policies.",
            expected: [N, N, N, S, N, N, S, W, N],
        },
        LabeledItem { id: 17, category: DM, source_type: "hackernews",
            title: "eBPF for production observability",
            content: "eBPF enables zero-overhead observability: trace system calls, network packets, and application behavior without modifying source code.",
            expected: [N, N, N, S, N, N, S, W, N],
        },
        LabeledItem { id: 18, category: DM, source_type: "blog",
            title: "Terraform state management at scale",
            content: "Managing Terraform state for hundreds of services: remote state backends, state locking, workspace isolation, and module design patterns.",
            expected: [N, N, N, S, N, N, W, W, N],
        },
        LabeledItem { id: 19, category: DM, source_type: "hackernews",
            title: "React Native 0.74 new architecture",
            content: "React Native's new architecture: the Fabric renderer and JSI bridge replacement. Performance improvements and better TypeScript integration.",
            expected: [N, N, W, N, S, N, W, W, N],
        },
        LabeledItem { id: 20, category: DM, source_type: "hackernews",
            title: "Expo Router v3: File-based routing for React Native",
            content: "Expo Router v3 brings universal links, improved navigation APIs, and better TypeScript support for cross-platform mobile apps.",
            expected: [N, N, W, N, S, N, W, W, N],
        },
        LabeledItem { id: 21, category: DM, source_type: "hackernews",
            title: "Haskell GHC 9.8 improvements",
            content: "GHC 9.8 includes improved type-level programming features, better error messages, and performance improvements for compiled code.",
            expected: [N, N, N, N, N, N, W, N, S],
        },
        LabeledItem { id: 22, category: DM, source_type: "blog",
            title: "Category theory for programmers: Functors",
            content: "Understanding functors from a programming perspective: Functor laws, fmap, and why category theory provides a principled foundation for functional programming.",
            expected: [N, N, N, N, N, N, W, N, S],
        },
        LabeledItem { id: 23, category: DM, source_type: "hackernews",
            title: "NixOS: Reproducible infrastructure as code",
            content: "NixOS and the Nix package manager enable fully reproducible system configurations. Everything is declarative with rollback support built in.",
            expected: [W, N, N, W, N, N, W, N, S],
        },
        LabeledItem { id: 24, category: DM, source_type: "hackernews",
            title: "Go generics: Practical patterns after 2 years",
            content: "Two years after Go generics, what patterns have emerged? Type constraints, generic data structures, and where generics shine.",
            expected: [W, N, N, N, N, N, W, S, N],
        },
        LabeledItem { id: 25, category: DM, source_type: "hackernews",
            title: "axum web framework: Production patterns",
            content: "Production patterns with axum, the Rust web framework built on tokio and hyper. State management, middleware, and error handling.",
            expected: [S, N, N, N, N, N, S, S, N],
        },
        LabeledItem { id: 26, category: DM, source_type: "hackernews",
            title: "Rust ownership and borrowing: Advanced patterns",
            content: "Advanced Rust ownership patterns: self-referential structs with Pin, lifetime elision rules, and variance in the type system.",
            expected: [S, N, N, N, N, N, S, S, W],
        },
        LabeledItem { id: 27, category: DM, source_type: "blog",
            title: "Python async/await with asyncio in production",
            content: "Running Python asyncio in production: event loop management, concurrency patterns, and debugging async code.",
            expected: [N, S, N, N, N, N, S, W, N],
        },
        LabeledItem { id: 28, category: DM, source_type: "hackernews",
            title: "Next.js App Router: Server components deep dive",
            content: "Understanding React Server Components in Next.js App Router: data fetching patterns, caching strategies, and streaming.",
            expected: [N, N, S, N, N, N, S, W, N],
        },
        LabeledItem { id: 29, category: DM, source_type: "hackernews",
            title: "Grafana and Prometheus: Modern observability stack",
            content: "Building a complete observability platform with Grafana and Prometheus: metric collection, alerting rules, and dashboard design.",
            expected: [N, N, N, S, N, N, W, W, N],
        },
        LabeledItem { id: 30, category: DM, source_type: "blog",
            title: "Expo EAS Build: CI/CD for React Native",
            content: "Expo Application Services (EAS) Build automates the React Native build pipeline for iOS and Android with OTA update support.",
            expected: [N, N, N, N, S, N, W, N, N],
        },

        // ====================================================================
        // AdjacentMatch (20) — id 31-50
        // ====================================================================
        LabeledItem { id: 31, category: AM, source_type: "hackernews",
            title: "C++ coroutines vs Rust async: A comparison",
            content: "Comparing C++ coroutines and Rust async/await: syntax differences, performance characteristics, and the underlying machinery.",
            expected: [W, N, N, N, N, N, W, W, B],
        },
        LabeledItem { id: 32, category: AM, source_type: "hackernews",
            title: "Zig programming language: Memory management",
            content: "Zig's approach to memory management: comptime allocators, error unions, and how Zig avoids the complexity of Rust's borrow checker.",
            expected: [W, N, N, N, N, N, W, W, B],
        },
        LabeledItem { id: 33, category: AM, source_type: "hackernews",
            title: "DuckDB: Analytics in process",
            content: "DuckDB brings OLAP analytics to process-local databases. Query Parquet files, CSV, and JSON directly without a server.",
            expected: [W, W, W, N, N, N, S, S, N],
        },
        LabeledItem { id: 34, category: AM, source_type: "blog",
            title: "Electron vs Tauri: Desktop app framework comparison",
            content: "Comparing Electron and Tauri for desktop application development. Tauri uses the system webview and Rust backend for smaller bundles.",
            expected: [W, N, W, N, N, N, W, W, N],
        },
        LabeledItem { id: 35, category: AM, source_type: "hackernews",
            title: "scikit-learn pipeline patterns",
            content: "Building robust ML pipelines with scikit-learn: Pipeline API, ColumnTransformer, cross-validation, and hyperparameter tuning.",
            expected: [N, W, N, N, N, N, W, N, N],
        },
        LabeledItem { id: 36, category: AM, source_type: "hackernews",
            title: "Hugging Face transformers library tutorial",
            content: "Getting started with the Hugging Face transformers library: loading pretrained models, fine-tuning for classification, and deploying inference endpoints.",
            expected: [N, S, N, N, N, N, W, B, N],
        },
        LabeledItem { id: 37, category: AM, source_type: "hackernews",
            title: "Vite 5: Frontend build tooling",
            content: "Vite 5 improvements: faster HMR, better tree shaking, and the new plugin API. Now the standard bundler for React and Vue projects.",
            expected: [N, N, W, N, N, W, W, W, N],
        },
        LabeledItem { id: 38, category: AM, source_type: "hackernews",
            title: "Prisma ORM: Type-safe database access",
            content: "Prisma provides type-safe database access for TypeScript: schema definition, migrations, and a query builder that generates TypeScript types.",
            expected: [N, N, W, N, N, N, W, W, N],
        },
        LabeledItem { id: 39, category: AM, source_type: "hackernews",
            title: "Helm chart best practices for Kubernetes",
            content: "Production helm chart patterns: templating best practices, values schema validation, and chart testing.",
            expected: [N, N, N, W, N, N, W, W, N],
        },
        LabeledItem { id: 40, category: AM, source_type: "blog",
            title: "Ansible vs Pulumi for infrastructure automation",
            content: "Comparing Ansible and Pulumi for infrastructure automation. Ansible excels at configuration management; Pulumi brings programming language power.",
            expected: [N, N, N, W, N, N, W, W, N],
        },
        LabeledItem { id: 41, category: AM, source_type: "hackernews",
            title: "Swift concurrency: async/await on Apple platforms",
            content: "Swift's actor model and async/await brings structured concurrency to iOS and macOS development.",
            expected: [N, N, N, N, W, N, W, N, N],
        },
        LabeledItem { id: 42, category: AM, source_type: "hackernews",
            title: "Flutter vs React Native: 2024 comparison",
            content: "Comparing Flutter and React Native for cross-platform mobile development: the widget model vs bridge architecture.",
            expected: [N, N, W, N, W, N, W, W, N],
        },
        LabeledItem { id: 43, category: AM, source_type: "blog",
            title: "PureScript: Haskell for the web",
            content: "PureScript brings Haskell's type system to JavaScript compilation with row polymorphism and effect tracking.",
            expected: [N, N, N, N, N, N, W, N, S],
        },
        LabeledItem { id: 44, category: AM, source_type: "hackernews",
            title: "OCaml algebraic data types and pattern matching",
            content: "OCaml's algebraic data types provide safe and expressive modeling: sum types, product types, exhaustive pattern matching, and GADTs.",
            expected: [N, N, N, N, N, N, W, N, W],
        },
        LabeledItem { id: 45, category: AM, source_type: "hackernews",
            title: "gRPC vs REST: When to choose each",
            content: "Comparing gRPC and REST for service communication: performance, schema evolution, streaming support. gRPC excels for internal microservices.",
            expected: [W, N, W, W, N, N, W, S, N],
        },
        LabeledItem { id: 46, category: AM, source_type: "hackernews",
            title: "Redis streams for event-driven architecture",
            content: "Using Redis streams as a lightweight message broker: consumer groups, acknowledgment semantics, and building event-driven microservices.",
            expected: [N, N, N, W, N, N, W, W, N],
        },
        LabeledItem { id: 47, category: AM, source_type: "hackernews",
            title: "Rust for embedded systems with Embassy",
            content: "Embassy is an async embedded framework for Rust. Write interrupt-driven embedded code with Rust's type system guarantees and no-std async/await.",
            expected: [S, N, N, N, N, N, W, W, B],
        },
        LabeledItem { id: 48, category: AM, source_type: "hackernews",
            title: "NumPy vectorization: Beyond for loops",
            content: "Numpy vectorization patterns: broadcasting, advanced indexing, and universal functions for 10-100x speedups in numerical code.",
            expected: [N, W, N, N, N, N, W, B, N],
        },
        LabeledItem { id: 49, category: AM, source_type: "blog",
            title: "tRPC: End-to-end type safety for TypeScript APIs",
            content: "tRPC eliminates the client-server contract problem with fully type-safe client code for Next.js full-stack applications.",
            expected: [N, N, W, N, N, N, W, W, N],
        },
        LabeledItem { id: 50, category: AM, source_type: "hackernews",
            title: "Kafka for event sourcing and CQRS",
            content: "Using Apache Kafka for event sourcing: event log design, consumer group patterns, and building CQRS systems.",
            expected: [N, N, N, W, N, N, W, W, N],
        },

        // ====================================================================
        // CrossDomainNoise (25) — id 51-75
        // ====================================================================
        LabeledItem { id: 51, category: CDN, source_type: "hackernews",
            title: "Ruby on Rails 7.2: What's new",
            content: "Rails 7.2 improvements: native Propshaft for assets, improved Active Record. The web framework that prioritizes developer happiness.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 52, category: CDN, source_type: "hackernews",
            title: "PHP 8.3 performance improvements",
            content: "PHP 8.3 introduces typed class constants, readonly properties, and continues the JIT performance improvements.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 53, category: CDN, source_type: "hackernews",
            title: "Java Spring Boot 3: Modern enterprise Java",
            content: "Spring Boot 3 with Spring Framework 6: native compilation with GraalVM and Jakarta EE 10 support.",
            expected: [N, N, N, N, N, N, N, B, N],
        },
        LabeledItem { id: 54, category: CDN, source_type: "hackernews",
            title: "Scala 3 metaprogramming with macros",
            content: "Scala 3 macros and inline methods: compile-time computation, code generation, and type-level programming.",
            expected: [N, N, N, N, N, N, W, N, B],
        },
        LabeledItem { id: 55, category: CDN, source_type: "hackernews",
            title: "Elixir LiveView: Real-time without JavaScript",
            content: "Phoenix LiveView enables real-time interactive UIs in Elixir without JavaScript SPAs. Server-rendered HTML with WebSocket diffs.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 56, category: CDN, source_type: "hackernews",
            title: "Julia for scientific computing",
            content: "Julia combines Python's ease of use with C-like performance for numerical computing and scientific workloads.",
            expected: [N, B, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 57, category: CDN, source_type: "hackernews",
            title: "C# 12: Primary constructors and collection expressions",
            content: "C# 12 brings primary constructors to classes, collection expressions, and interceptors as an experimental feature.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 58, category: CDN, source_type: "hackernews",
            title: "Kotlin Multiplatform Mobile: Share code across iOS and Android",
            content: "Kotlin Multiplatform Mobile (KMM) enables sharing business logic between iOS and Android while keeping native UIs.",
            expected: [N, N, N, N, B, N, N, N, N],
        },
        LabeledItem { id: 59, category: CDN, source_type: "hackernews",
            title: "Svelte 5 runes: Reactive state revisited",
            content: "Svelte 5 replaces reactive declarations with explicit runes: $state, $derived, $effect for a more explicit reactive model.",
            expected: [N, N, B, N, N, N, B, N, N],
        },
        LabeledItem { id: 60, category: CDN, source_type: "hackernews",
            title: "Angular 17: The renaissance continues",
            content: "Angular 17 ships with a new control flow syntax, defer blocks for lazy loading, and the new view transitions API.",
            expected: [N, N, B, N, N, N, N, N, N],
        },
        LabeledItem { id: 61, category: CDN, source_type: "hackernews",
            title: "Vue 3 Composition API best practices",
            content: "Patterns for Vue 3 Composition API: composable design, reactive utilities, and migration from Options API.",
            expected: [N, N, B, N, N, N, B, N, N],
        },
        LabeledItem { id: 62, category: CDN, source_type: "hackernews",
            title: "Dart and Flutter 3.16: Performance improvements",
            content: "Flutter 3.16 and Dart 3.2 bring improved rendering performance and new Material 3 components.",
            expected: [N, N, N, N, B, N, N, N, N],
        },
        LabeledItem { id: 63, category: CDN, source_type: "hackernews",
            title: "R programming: Statistical computing essentials",
            content: "R remains the language of choice for statisticians: ggplot2 for visualization, dplyr for data manipulation.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 64, category: CDN, source_type: "hackernews",
            title: "COBOL still runs the world: Banking systems",
            content: "COBOL continues to process trillions of dollars daily in banking and government systems.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 65, category: CDN, source_type: "hackernews",
            title: "Lua scripting in games and embedded systems",
            content: "Lua's lightweight footprint makes it ideal for game scripting and embedded configuration.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 66, category: CDN, source_type: "hackernews",
            title: "Perl 5 and the CPAN ecosystem",
            content: "Perl 5 remains active with CPAN providing thousands of modules for web development.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 67, category: CDN, source_type: "hackernews",
            title: "Erlang OTP supervision trees",
            content: "Erlang's OTP framework with supervisor trees, gen_server patterns for building fault-tolerant distributed systems.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 68, category: CDN, source_type: "hackernews",
            title: "F# for domain modeling",
            content: "F# and domain-driven design: discriminated unions, computation expressions, and railway-oriented programming on .NET.",
            expected: [N, N, N, N, N, N, W, N, B],
        },
        LabeledItem { id: 69, category: CDN, source_type: "hackernews",
            title: "Clojure: A practical Lisp for production",
            content: "Clojure in production: immutable data structures, the REPL-driven workflow, and ClojureScript for frontend.",
            expected: [N, N, N, N, N, N, B, N, B],
        },
        LabeledItem { id: 70, category: CDN, source_type: "hackernews",
            title: "Assembly language for x86: A revival",
            content: "Assembly language is having a renaissance in performance-critical code: SIMD intrinsics and hand-optimized routines.",
            expected: [N, N, N, N, N, N, N, N, B],
        },
        LabeledItem { id: 71, category: CDN, source_type: "hackernews",
            title: "Bash scripting patterns for DevOps",
            content: "Production bash scripting: error handling, parameter expansion, and common patterns for automation scripts.",
            expected: [N, N, N, B, N, N, B, N, N],
        },
        LabeledItem { id: 72, category: CDN, source_type: "hackernews",
            title: "PowerShell for Windows automation",
            content: "PowerShell 7 for cross-platform automation: cmdlet design, pipeline patterns, and Azure integration.",
            expected: [N, N, N, B, N, N, N, N, N],
        },
        LabeledItem { id: 73, category: CDN, source_type: "hackernews",
            title: "Fortran in scientific computing: Still alive",
            content: "Fortran remains relevant in climate models, finite element analysis, and numerical linear algebra.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 74, category: CDN, source_type: "hackernews",
            title: "Ada for safety-critical systems",
            content: "Ada's strong type system and SPARK subset make it ideal for aerospace, railways, and defense applications.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 75, category: CDN, source_type: "hackernews",
            title: "Crystal language: Fast as C, slick as Ruby",
            content: "Crystal is a statically-typed compiled language with Ruby-like syntax and C-level performance.",
            expected: [N, N, N, N, N, N, N, N, N],
        },

        // ====================================================================
        // Borderline (20) — id 76-95
        // ====================================================================
        LabeledItem { id: 76, category: BDL, source_type: "hackernews",
            title: "AI coding assistants: Are they worth it?",
            content: "Comparing GitHub Copilot, Cursor, and Codeium for developer productivity. When AI suggestions help and when they hurt.",
            expected: [B, B, B, B, B, B, S, B, B],
        },
        LabeledItem { id: 77, category: BDL, source_type: "hackernews",
            title: "Monorepos: Tools and tradeoffs",
            content: "Monorepo tooling with Turborepo, Nx, and Bazel. When monorepos help and when they create complexity.",
            expected: [B, B, B, B, B, N, W, B, N],
        },
        LabeledItem { id: 78, category: BDL, source_type: "hackernews",
            title: "CI/CD pipeline optimization",
            content: "Speeding up CI/CD pipelines: caching strategies, parallelization, selective testing, and build artifact reuse.",
            expected: [B, B, B, W, B, N, W, W, B],
        },
        LabeledItem { id: 79, category: BDL, source_type: "hackernews",
            title: "API design: REST principles revisited",
            content: "REST API design best practices: resource naming, HTTP methods, versioning strategies, and pagination approaches.",
            expected: [B, B, W, W, B, N, W, W, N],
        },
        LabeledItem { id: 80, category: BDL, source_type: "hackernews",
            title: "Database indexing strategies",
            content: "Database indexing fundamentals: B-tree vs hash indexes, covering indexes, partial indexes for PostgreSQL, MySQL, and SQLite.",
            expected: [B, B, B, B, N, N, W, W, N],
        },
        LabeledItem { id: 81, category: BDL, source_type: "hackernews",
            title: "Software architecture patterns: When to use each",
            content: "Hexagonal, onion, clean, and layered architectures compared. Practical guidance for production systems.",
            expected: [B, B, B, B, N, N, W, W, B],
        },
        LabeledItem { id: 82, category: BDL, source_type: "hackernews",
            title: "Testing strategies: Unit vs integration vs E2E",
            content: "The testing pyramid revisited: when unit tests give false confidence and when E2E tests are worth the investment.",
            expected: [B, B, B, B, B, N, W, W, B],
        },
        LabeledItem { id: 83, category: BDL, source_type: "hackernews",
            title: "Performance profiling: Finding real bottlenecks",
            content: "Profiling methodology for Rust (flamegraph), Python (py-spy), and Node.js (clinic.js). Finding actual bottlenecks.",
            expected: [W, B, B, B, N, N, W, W, B],
        },
        LabeledItem { id: 84, category: BDL, source_type: "hackernews",
            title: "Open source sustainability and funding",
            content: "How open source projects survive: GitHub Sponsors, Open Collective, and commercial dual-licensing.",
            expected: [B, B, B, B, B, N, B, B, B],
        },
        LabeledItem { id: 85, category: BDL, source_type: "hackernews",
            title: "Developer experience: What actually matters",
            content: "Developer experience measurement: DORA metrics, cycle time, deployment frequency, and change failure rate.",
            expected: [B, B, B, W, B, N, B, B, N],
        },
        LabeledItem { id: 86, category: BDL, source_type: "hackernews",
            title: "Git workflows: Trunk-based vs feature branches",
            content: "Comparing trunk-based development and gitflow: release cadence, team size considerations.",
            expected: [B, B, B, B, B, N, B, B, N],
        },
        LabeledItem { id: 87, category: BDL, source_type: "hackernews",
            title: "Code review: Making it effective",
            content: "Effective code review practices: reviewer selection, review depth vs speed, and constructive feedback.",
            expected: [B, B, B, B, B, N, B, B, B],
        },
        LabeledItem { id: 88, category: BDL, source_type: "hackernews",
            title: "Technical debt: When to pay it down",
            content: "Managing technical debt strategically: identifying high-leverage refactors and making the business case.",
            expected: [B, B, B, B, B, N, B, B, N],
        },
        LabeledItem { id: 89, category: BDL, source_type: "hackernews",
            title: "Observability vs monitoring: The difference",
            content: "The three pillars of observability: metrics, logs, and traces. OpenTelemetry as the emerging standard.",
            expected: [B, N, B, W, N, N, W, W, N],
        },
        LabeledItem { id: 90, category: BDL, source_type: "hackernews",
            title: "Local-first software: Principles and practices",
            content: "Local-first principles: data ownership, offline capability, sync protocols, and conflict resolution with CRDTs.",
            expected: [W, N, B, N, N, N, W, W, N],
        },
        LabeledItem { id: 91, category: BDL, source_type: "hackernews",
            title: "Vector databases: The hype and the reality",
            content: "Vector databases for semantic search: Pinecone, Weaviate, and Chroma vs SQLite-vec or pgvector.",
            expected: [W, W, B, N, N, N, S, W, N],
        },
        LabeledItem { id: 92, category: BDL, source_type: "hackernews",
            title: "Functional programming patterns in imperative languages",
            content: "Applying FP patterns in Rust, Python, and TypeScript: immutability, higher-order functions, and composition.",
            expected: [W, B, B, N, N, N, W, W, W],
        },
        LabeledItem { id: 93, category: BDL, source_type: "hackernews",
            title: "WebSockets vs Server-Sent Events vs polling",
            content: "Real-time communication patterns: WebSockets for bidirectional, SSE for server-push, and polling for simplicity.",
            expected: [N, N, W, N, B, N, W, W, N],
        },
        LabeledItem { id: 94, category: BDL, source_type: "hackernews",
            title: "Dependency management: Staying secure and current",
            content: "Managing dependencies: semantic versioning, lock files, automated updates with Renovate/Dependabot.",
            expected: [B, B, B, W, B, N, W, W, N],
        },
        LabeledItem { id: 95, category: BDL, source_type: "hackernews",
            title: "Developer tools: The 2024 landscape",
            content: "The state of developer tooling in 2024: editors, terminals, AI assistants, and the shift toward native performance.",
            expected: [B, B, B, B, B, B, B, B, B],
        },

        // ====================================================================
        // CareerNoise (15) — id 96-110
        // ====================================================================
        LabeledItem { id: 96, category: CB, source_type: "hackernews",
            title: "Senior Rust Engineer at Cloudflare — remote",
            content: "Cloudflare is hiring Senior Rust Engineers. 5+ years experience, distributed systems background required. $180-250k.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 97, category: CB, source_type: "hackernews",
            title: "Staff ML Engineer — Series B startup — $200k+",
            content: "Looking for a Staff ML Engineer with PyTorch experience and production ML systems expertise.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 98, category: CB, source_type: "hackernews",
            title: "Ask HN: Who is hiring? (February 2024)",
            content: "Monthly hiring thread. Software engineers, data scientists, DevOps engineers across all technology stacks.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 99, category: CB, source_type: "hackernews",
            title: "Software Engineer compensation: How to negotiate",
            content: "Salary negotiation strategies: total compensation packages, equity vesting, sign-on bonuses, and competing offers.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 100, category: CB, source_type: "hackernews",
            title: "Tech layoffs: How to prepare and recover",
            content: "Navigating tech layoffs: financial preparation, job search strategies, and career transitions.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 101, category: CB, source_type: "hackernews",
            title: "DevOps Engineer at fintech startup — equity heavy",
            content: "Infrastructure team building payments. Kubernetes, Terraform, AWS required. Series A, strong equity.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 102, category: CB, source_type: "hackernews",
            title: "Remote React Native engineer — EdTech company",
            content: "Building educational apps for K-12 students with React Native and Expo. Impact-driven company.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 103, category: CB, source_type: "hackernews",
            title: "Ask HN: Who wants to be hired? (February 2024)",
            content: "Monthly thread for candidates. Looking for Rust, Python, TypeScript, and Go opportunities. Remote preferred.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 104, category: CB, source_type: "hackernews",
            title: "Visa sponsorship for software engineers in the US",
            content: "Guide to H-1B, O-1, and EB-2/EB-3 visas for international software engineers.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 105, category: CB, source_type: "hackernews",
            title: "Engineering manager transition: From IC to leadership",
            content: "Making the IC to EM transition: what to expect, common pitfalls, and whether management is right for you.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 106, category: CB, source_type: "hackernews",
            title: "System design interviews: A practical guide",
            content: "Preparing for system design interviews: distributed systems fundamentals, CAP theorem, and scaling patterns.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 107, category: CB, source_type: "hackernews",
            title: "Freelancing as a software developer in 2024",
            content: "Building a freelance software business: finding clients, setting rates, contracts, and managing independent work.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 108, category: CB, source_type: "hackernews",
            title: "Staff engineer: What the role actually involves",
            content: "The staff engineer role in practice: technical strategy, cross-team influence, and career trajectory.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 109, category: CB, source_type: "hackernews",
            title: "Open to work: Haskell and functional programming expert",
            content: "10 years of Haskell, PureScript, and Scala. Looking for remote functional programming positions.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 110, category: CB, source_type: "hackernews",
            title: "Interview prep: LeetCode vs system design vs behavioral",
            content: "Balancing interview preparation: when algorithmic practice matters vs system design vs behavioral.",
            expected: [N, N, N, N, N, N, N, N, N],
        },

        // ====================================================================
        // SecurityAdvisory (15) — id 111-125
        // ====================================================================
        LabeledItem { id: 111, category: SA, source_type: "hackernews",
            title: "CVE-2024-1234: Critical vulnerability in popular Rust crate",
            content: "A critical deserialization vulnerability was discovered in a widely-used Rust serialization crate. CVSS score: 9.8. Update immediately.",
            expected: [S, N, N, N, N, N, S, W, N],
        },
        LabeledItem { id: 112, category: SA, source_type: "hackernews",
            title: "Supply chain attack on PyPI package with 10M weekly downloads",
            content: "A malicious version of a popular Python package was published to PyPI containing code that exfiltrated environment variables.",
            expected: [N, S, N, N, N, N, S, W, N],
        },
        LabeledItem { id: 113, category: SA, source_type: "hackernews",
            title: "npm package hijacking: Critical vulnerability in React ecosystem",
            content: "A popular npm package in the React ecosystem was compromised with malicious code targeting CI/CD environments.",
            expected: [N, N, S, N, W, N, S, W, N],
        },
        LabeledItem { id: 114, category: SA, source_type: "hackernews",
            title: "Kubernetes API server vulnerability: Remote code execution",
            content: "A critical vulnerability in the Kubernetes API server allows unauthenticated remote code execution on < 1.28.4.",
            expected: [N, N, N, S, N, N, S, W, N],
        },
        LabeledItem { id: 115, category: SA, source_type: "hackernews",
            title: "Docker Desktop security update: Privilege escalation",
            content: "Docker Desktop on macOS contains a privilege escalation vulnerability. Update to Docker Desktop 4.26.0 or later.",
            expected: [N, N, N, W, N, N, W, W, N],
        },
        LabeledItem { id: 116, category: SA, source_type: "hackernews",
            title: "SQLite integer overflow vulnerability — low severity",
            content: "A low-severity integer overflow in SQLite's query parser was responsibly disclosed. Fix available in SQLite 3.45.0.",
            expected: [W, N, N, N, N, N, W, W, N],
        },
        LabeledItem { id: 117, category: SA, source_type: "hackernews",
            title: "Terraform provider vulnerability: AWS credentials leak",
            content: "A vulnerability in a popular Terraform AWS provider could expose IAM credentials in state files.",
            expected: [N, N, N, S, N, N, W, W, N],
        },
        LabeledItem { id: 118, category: SA, source_type: "hackernews",
            title: "GitHub Actions: Secret injection via pull requests",
            content: "A configuration weakness in GitHub Actions allows malicious pull requests to access repository secrets.",
            expected: [B, B, B, W, B, N, W, W, N],
        },
        LabeledItem { id: 119, category: SA, source_type: "hackernews",
            title: "XSS vulnerability in React markdown renderer",
            content: "A cross-site scripting vulnerability in a popular React markdown library. User-controlled content can inject JavaScript.",
            expected: [N, N, W, N, N, N, W, N, N],
        },
        LabeledItem { id: 120, category: SA, source_type: "hackernews",
            title: "iOS SDK vulnerability: WebView JavaScript bridge",
            content: "Apple patched a vulnerability in WKWebView allowing malicious web content to access native app data.",
            expected: [N, N, N, N, W, N, W, N, N],
        },
        LabeledItem { id: 121, category: SA, source_type: "hackernews",
            title: "Log4Shell: Two years later, still being exploited",
            content: "Two years after Log4Shell, unpatched systems continue to be exploited across millions of internet-facing systems.",
            expected: [N, N, N, W, N, N, W, N, N],
        },
        LabeledItem { id: 122, category: SA, source_type: "hackernews",
            title: "OpenSSL critical vulnerability affects embedded devices",
            content: "A critical buffer overflow in OpenSSL affects embedded systems that cannot be easily updated.",
            expected: [W, N, N, W, N, N, W, W, N],
        },
        LabeledItem { id: 123, category: SA, source_type: "hackernews",
            title: "PyTorch remote code execution via pickle deserialization",
            content: "PyTorch model files can contain malicious pickle payloads. Use safetensors format for untrusted models.",
            expected: [N, S, N, N, N, N, S, N, N],
        },
        LabeledItem { id: 124, category: SA, source_type: "hackernews",
            title: "Node.js CVE: Path traversal in static file serving",
            content: "A path traversal vulnerability in Node.js allows serving files outside the intended directory.",
            expected: [N, N, W, N, N, N, W, W, N],
        },
        LabeledItem { id: 125, category: SA, source_type: "hackernews",
            title: "Heimdal Kerberos vulnerability: Authentication bypass",
            content: "A critical vulnerability in Heimdal Kerberos allows authentication bypass in enterprise environments.",
            expected: [N, N, N, W, N, N, N, N, N],
        },

        // ====================================================================
        // IntroductoryNoise (15) — id 126-140
        // ====================================================================
        LabeledItem { id: 126, category: INTRO, source_type: "hackernews",
            title: "Rust for beginners: Hello World explained",
            content: "Your first Rust program: understanding the main function and how Rust programs compile. A gentle introduction for new programmers.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 127, category: INTRO, source_type: "hackernews",
            title: "What is machine learning? A beginner's guide",
            content: "Machine learning explained for non-technical audiences: supervised learning, neural networks, and how AI systems learn.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 128, category: INTRO, source_type: "hackernews",
            title: "Learn Python in 30 days",
            content: "A structured 30-day Python curriculum for complete beginners: syntax, control flow, functions, and your first web scraper.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 129, category: INTRO, source_type: "hackernews",
            title: "What is Docker? Containers explained simply",
            content: "Docker explained for beginners: what containers are, how they differ from VMs, and your first Dockerfile.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 130, category: INTRO, source_type: "hackernews",
            title: "Git for beginners: Version control fundamentals",
            content: "Git fundamentals: commits, branches, merging, and remotes. Understanding version control for the first time.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 131, category: INTRO, source_type: "hackernews",
            title: "JavaScript for complete beginners",
            content: "JavaScript from zero: variables, functions, objects, and the DOM. Building your first interactive webpage.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 132, category: INTRO, source_type: "hackernews",
            title: "How the internet works: A visual guide",
            content: "Understanding TCP/IP, DNS, and HTTP. How your browser loads a webpage explained with simple diagrams.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 133, category: INTRO, source_type: "hackernews",
            title: "Introduction to databases: SQL basics",
            content: "SQL fundamentals: SELECT, INSERT, UPDATE, DELETE, and JOINs. Your first steps with relational databases.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 134, category: INTRO, source_type: "hackernews",
            title: "What is an API? REST explained for beginners",
            content: "APIs demystified: HTTP methods, JSON, status codes. No programming experience required to understand the concepts.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 135, category: INTRO, source_type: "hackernews",
            title: "Getting started with React in 2024",
            content: "React for beginners: components, props, state, and your first interactive UI. Building a todo app.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 136, category: INTRO, source_type: "hackernews",
            title: "Learn TypeScript: From JavaScript to types",
            content: "TypeScript for JavaScript developers: type annotations, interfaces, generics, and static typing benefits.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 137, category: INTRO, source_type: "hackernews",
            title: "Your first mobile app with React Native",
            content: "Building your first mobile app: setting up the development environment and deploying to an iOS simulator.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 138, category: INTRO, source_type: "hackernews",
            title: "Kubernetes explained in simple terms",
            content: "Kubernetes for beginners: pods, deployments, services, and why container orchestration matters.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 139, category: INTRO, source_type: "hackernews",
            title: "Introduction to machine learning with Python",
            content: "Your first ML model with scikit-learn: training a classification model and evaluating accuracy.",
            expected: [N, N, N, N, N, B, N, N, N],
        },
        LabeledItem { id: 140, category: INTRO, source_type: "hackernews",
            title: "Linux command line for beginners",
            content: "The essential Linux commands every developer needs: navigation, file manipulation, permissions, and pipes.",
            expected: [N, N, N, N, N, B, N, N, N],
        },

        // ====================================================================
        // ShowHNNoise (15) — id 141-155
        // ====================================================================
        LabeledItem { id: 141, category: SHN, source_type: "hackernews",
            title: "Show HN: I built a to-do app in Rust",
            content: "Show HN: Built a command-line todo app in Rust for learning. Uses serde for JSON storage. First Rust project.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 142, category: SHN, source_type: "hackernews",
            title: "Show HN: My side project — another note-taking app",
            content: "Show HN: Note-taking app for 6 months. Like Notion but simpler. Built with React and Node.js.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 143, category: SHN, source_type: "hackernews",
            title: "Show HN: AI-generated daily news summary",
            content: "Show HN: Weekend project using GPT-4 to summarize tech news. Deployed on Vercel with a Next.js frontend.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 144, category: SHN, source_type: "hackernews",
            title: "Show HN: Browser extension for focus mode",
            content: "Show HN: Browser extension that blocks distracting sites during focus sessions using the Pomodoro technique.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 145, category: SHN, source_type: "hackernews",
            title: "Show HN: Open source alternative to Notion",
            content: "Show HN: AppFlowy, an open-source Notion alternative built with Flutter and Rust. Self-hostable.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 146, category: SHN, source_type: "hackernews",
            title: "Show HN: I reimplemented grep in Rust",
            content: "Show HN: ripgrep-like tool as a learning exercise using Rust's regex crate and rayon for parallel file walking.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 147, category: SHN, source_type: "hackernews",
            title: "Show HN: URL shortener in Go as my first project",
            content: "Show HN: URL shortener as my first Go project using PostgreSQL for storage. Still learning.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 148, category: SHN, source_type: "hackernews",
            title: "Show HN: My ML model that predicts stock prices",
            content: "Show HN: LSTM trained on 5 years of stock data. Backtested on historical data. Not financial advice.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 149, category: SHN, source_type: "hackernews",
            title: "Show HN: CLI tool for managing dotfiles",
            content: "Show HN: A Rust CLI for managing dotfiles across machines using symlinks and TOML config.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 150, category: SHN, source_type: "hackernews",
            title: "Show HN: Personal finance tracker in plain HTML",
            content: "Show HN: Single-file HTML app for tracking expenses. No backend, no dependencies. Data in localStorage.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 151, category: SHN, source_type: "hackernews",
            title: "Show HN: Chat app built in a weekend",
            content: "Show HN: Real-time chat app with WebSockets and Svelte. My first full-stack project.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 152, category: SHN, source_type: "hackernews",
            title: "Show HN: I made a terminal Wordle clone",
            content: "Show HN: Wordle in your terminal, written in Python. 50 lines of code.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 153, category: SHN, source_type: "hackernews",
            title: "Show HN: Recipe manager with ingredient matching",
            content: "Show HN: Tell it what ingredients you have, it finds recipes. React frontend with Python ML backend.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 154, category: SHN, source_type: "hackernews",
            title: "Show HN: Pomodoro timer with Spotify integration",
            content: "Show HN: Pomodoro timer that pauses your Spotify during breaks. Electron app.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 155, category: SHN, source_type: "hackernews",
            title: "Show HN: My first iOS app — habit tracker",
            content: "Show HN: A habit tracking app for iOS built with SwiftUI. My first published app.",
            expected: [N, N, N, N, N, N, N, N, N],
        },

        // ====================================================================
        // MetaNoise (15) — id 156-170
        // ====================================================================
        LabeledItem { id: 156, category: MT, source_type: "hackernews",
            title: "The death of the 40-hour work week in tech",
            content: "How remote work and always-on culture have eroded the 40-hour week. Burnout and sustainable productivity.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 157, category: MT, source_type: "hackernews",
            title: "10x engineers: Myth or reality?",
            content: "Examining the 10x engineer concept: is exceptional productivity real and how should teams think about it.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 158, category: MT, source_type: "hackernews",
            title: "Is college still worth it for software engineers?",
            content: "The ROI of computer science degrees vs bootcamps vs self-teaching. Entry barriers and salary trajectories.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 159, category: MT, source_type: "hackernews",
            title: "Remote work: The great experiment's results",
            content: "Three years of remote work in tech: productivity studies, mental health impacts, and the return-to-office debate.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 160, category: MT, source_type: "hackernews",
            title: "The problem with scrum in software teams",
            content: "Critiquing scrum: cargo-culting agile ceremonies, estimation theater, and what actually works.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 161, category: MT, source_type: "hackernews",
            title: "Imposter syndrome in software engineering",
            content: "Imposter syndrome affects most developers. Strategies for recognizing cognitive distortions and building confidence.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 162, category: MT, source_type: "hackernews",
            title: "The future of software engineering with AI",
            content: "How AI coding assistants will reshape the profession: what will be automated and how to position yourself.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 163, category: MT, source_type: "hackernews",
            title: "Measuring developer productivity: DORA vs SPACE",
            content: "DORA metrics vs the SPACE framework for measuring developer productivity and what each captures.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 164, category: MT, source_type: "hackernews",
            title: "Why software estimates are always wrong",
            content: "The psychology of software estimation: planning fallacy, unknown unknowns, and why story points don't help.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 165, category: MT, source_type: "hackernews",
            title: "On being a senior engineer: What it actually means",
            content: "Defining senior engineering beyond years of experience: technical judgment, communication, and mentorship.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 166, category: MT, source_type: "hackernews",
            title: "The mythical man-month: 50 years later",
            content: "Brooks' Law revisited: which insights from 1975 remain valid in modern software development.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 167, category: MT, source_type: "hackernews",
            title: "Burnout in software engineering: Warning signs",
            content: "Recognizing and preventing burnout: chronic stress indicators and organizational factors.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 168, category: MT, source_type: "hackernews",
            title: "Documentation: Why developers hate writing it",
            content: "Why documentation falls behind and strategies: docs-as-code and living documentation approaches.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 169, category: MT, source_type: "hackernews",
            title: "Pair programming: Does it work?",
            content: "The research on pair programming: code quality outcomes, knowledge transfer, and the productivity tradeoff.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 170, category: MT, source_type: "hackernews",
            title: "Open plan offices are bad for developers",
            content: "The research against open plan offices: interruption costs, deep work, and the case for private offices.",
            expected: [N, N, N, N, N, N, N, N, N],
        },

        // ====================================================================
        // BusinessNoise (10) — id 171-180
        // ====================================================================
        LabeledItem { id: 171, category: BC, source_type: "hackernews",
            title: "Startup funding: Series A to IPO explained",
            content: "The funding journey from seed to IPO: valuation mechanics, dilution, term sheets, and investor expectations.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 172, category: BC, source_type: "hackernews",
            title: "SaaS pricing strategies: Per-seat vs usage-based",
            content: "Choosing a SaaS pricing model: per-seat, usage-based, flat-rate, and hybrid approaches.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 173, category: BC, source_type: "hackernews",
            title: "Product-market fit: How to know when you have it",
            content: "Measuring product-market fit: NPS, retention curves, and the Sean Ellis test.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 174, category: BC, source_type: "hackernews",
            title: "Microsoft acquires another developer tools company",
            content: "Microsoft continues its acquisition strategy in developer tools. The deal values the company at $2.4 billion.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 175, category: BC, source_type: "hackernews",
            title: "Google Cloud vs AWS vs Azure: Enterprise comparison 2024",
            content: "Comparing the three major cloud providers for enterprise workloads: pricing, service breadth, and migration costs.",
            expected: [N, N, N, B, N, N, B, B, N],
        },
        LabeledItem { id: 176, category: BC, source_type: "hackernews",
            title: "The economics of open source: How companies make money",
            content: "Business models for open source companies: open core, dual licensing, hosted services, and support contracts.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 177, category: BC, source_type: "hackernews",
            title: "Big Tech regulation: EU Digital Markets Act impact",
            content: "The EU Digital Markets Act's impact on Apple, Google, and Meta. Gatekeepers and interoperability requirements.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 178, category: BC, source_type: "hackernews",
            title: "Venture capital dries up for developer tools",
            content: "VC investment in developer tools is down 60% from peak. Which companies are cutting staff and consolidating.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 179, category: BC, source_type: "hackernews",
            title: "FAANG compensation: 2024 levels",
            content: "Updated compensation data from levels.fyi for major tech companies. Total compensation changes since layoffs.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 180, category: BC, source_type: "hackernews",
            title: "The rise of AI infrastructure startups",
            content: "Investment in AI infrastructure is accelerating. GPU clouds, model serving platforms, and MLOps tools attract VC.",
            expected: [N, B, N, N, N, N, B, N, N],
        },

        // ====================================================================
        // ReleaseNotes (5) — id 181-185
        // ====================================================================
        LabeledItem { id: 181, category: RN, source_type: "blog",
            title: "Rust 1.76.0 release notes",
            content: "Rust 1.76.0 stabilizes ABI compatibility reference, adds type_name_of_val, and improves diagnostics.",
            expected: [S, N, N, N, N, N, S, S, B],
        },
        LabeledItem { id: 182, category: RN, source_type: "blog",
            title: "Python 3.13 release announcement",
            content: "Python 3.13 ships with experimental free-threaded mode, improved REPL, better error messages, and a new JIT.",
            expected: [N, S, N, N, N, N, S, W, N],
        },
        LabeledItem { id: 183, category: RN, source_type: "blog",
            title: "TypeScript 5.4 is now available",
            content: "TypeScript 5.4: NoInfer utility type, improved type narrowing in closures, and import attributes.",
            expected: [N, N, S, N, W, N, S, W, N],
        },
        LabeledItem { id: 184, category: RN, source_type: "blog",
            title: "Kubernetes 1.29 changelog",
            content: "Kubernetes 1.29 Mandala: 49 enhancements, improved sidecars, ReadWriteOncePod GA, and API removals.",
            expected: [N, N, N, S, N, N, W, W, N],
        },
        LabeledItem { id: 185, category: RN, source_type: "blog",
            title: "React Native 0.73 release",
            content: "React Native 0.73 introduces stable Metro with symlinks support and improved debugging.",
            expected: [N, N, W, N, S, N, W, W, N],
        },

        // ====================================================================
        // HNDiscussion (10) — id 186-195
        // ====================================================================
        LabeledItem { id: 186, category: HI, source_type: "hackernews",
            title: "Ask HN: What's your morning routine as a developer?",
            content: "Discussion about morning routines among HN developers: exercise, reading, and how to start the workday.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 187, category: HI, source_type: "hackernews",
            title: "Ask HN: Best books for software architects?",
            content: "HN thread recommending books for software architects: Designing Data-Intensive Applications and Clean Architecture.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 188, category: HI, source_type: "hackernews",
            title: "Ask HN: How do you manage information overload?",
            content: "Managing information overload as a developer: RSS feeds, newsletters, read-later apps, and staying current.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 189, category: HI, source_type: "hackernews",
            title: "Ask HN: Is Rust worth learning in 2024?",
            content: "Community discussion on whether Rust is worth learning. Consensus leans positive for systems and web developers.",
            expected: [B, N, N, N, N, N, B, B, N],
        },
        LabeledItem { id: 190, category: HI, source_type: "hackernews",
            title: "Ask HN: How do you handle legacy codebases?",
            content: "Strategies for legacy codebases: strangler fig pattern, test retrofitting, and incremental refactoring.",
            expected: [N, N, N, N, N, N, B, N, N],
        },
        LabeledItem { id: 191, category: HI, source_type: "hackernews",
            title: "Ask HN: What's your favorite obscure Unix command?",
            content: "HN community shares lesser-known Unix commands: column, sponge, pv, tsort, and other gems.",
            expected: [N, N, N, B, N, N, N, N, N],
        },
        LabeledItem { id: 192, category: HI, source_type: "hackernews",
            title: "Ask HN: What was your worst production incident?",
            content: "War stories from production incidents: cascading failures, accidental data deletions, and lessons learned.",
            expected: [N, N, N, B, N, N, N, N, N],
        },
        LabeledItem { id: 193, category: HI, source_type: "hackernews",
            title: "Ask HN: How do you stay motivated on long projects?",
            content: "Strategies for maintaining motivation on multi-year projects: milestone celebrations and preventing burnout.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 194, category: HI, source_type: "hackernews",
            title: "Tell HN: I quit FAANG to work on open source full time",
            content: "Developer shares experience leaving FAANG to work on open source via GitHub Sponsors and Open Collective.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 195, category: HI, source_type: "hackernews",
            title: "Ask HN: Favorite keyboard shortcuts for productivity?",
            content: "HN discussion on keyboard shortcuts: tmux, vim, IDE shortcuts, and terminal emulator tricks.",
            expected: [N, N, N, N, N, N, N, N, N],
        },

        // ====================================================================
        // DistantlyRelevant (10) — id 196-205
        // ====================================================================
        LabeledItem { id: 196, category: DI, source_type: "hackernews",
            title: "Distributed systems fundamentals: CAP theorem",
            content: "Understanding the CAP theorem: consistency, availability, and partition tolerance in distributed databases.",
            expected: [W, N, N, W, N, N, S, W, N],
        },
        LabeledItem { id: 197, category: DI, source_type: "hackernews",
            title: "Formal verification: TLA+ for distributed systems",
            content: "TLA+ for specifying and verifying distributed systems: how AWS uses formal methods to find bugs before implementation.",
            expected: [W, N, N, N, N, N, W, N, W],
        },
        LabeledItem { id: 198, category: DI, source_type: "hackernews",
            title: "Garbage collection algorithms: A deep dive",
            content: "GC algorithms compared: reference counting, mark-sweep, generational collection. Understanding what Rust avoids.",
            expected: [W, N, N, N, N, N, W, W, W],
        },
        LabeledItem { id: 199, category: DI, source_type: "hackernews",
            title: "CPU architecture: RISC-V vs ARM vs x86",
            content: "Comparing CPU architectures and why RISC-V is disrupting the embedded and server markets.",
            expected: [W, N, N, N, N, N, W, N, B],
        },
        LabeledItem { id: 200, category: DI, source_type: "hackernews",
            title: "Compilers: How LLVM changed everything",
            content: "LLVM's impact on compiler development: Rust, Swift, and Clang all target LLVM's backend.",
            expected: [W, N, N, N, N, N, W, N, W],
        },
        LabeledItem { id: 201, category: DI, source_type: "hackernews",
            title: "Networking fundamentals: How TCP really works",
            content: "TCP internals: three-way handshake, congestion control, and why head-of-line blocking motivated HTTP/3.",
            expected: [N, N, N, W, N, N, W, N, N],
        },
        LabeledItem { id: 202, category: DI, source_type: "hackernews",
            title: "Cryptography fundamentals for developers",
            content: "Essential cryptography: symmetric vs asymmetric encryption, hashing, digital signatures, and common mistakes.",
            expected: [B, N, N, W, N, N, W, N, N],
        },
        LabeledItem { id: 203, category: DI, source_type: "hackernews",
            title: "Operating systems design: Microkernel vs monolithic",
            content: "OS design philosophy: microkernel security vs monolithic performance. seL4, Redox, and the ongoing debate.",
            expected: [W, N, N, N, N, N, W, N, B],
        },
        LabeledItem { id: 204, category: DI, source_type: "hackernews",
            title: "Type systems: An overview across languages",
            content: "Comparing type systems: nominative vs structural, gradual typing, dependent types, and linear types.",
            expected: [W, N, N, N, N, N, W, N, S],
        },
        LabeledItem { id: 205, category: DI, source_type: "hackernews",
            title: "Concurrency models: Threads, events, and actors",
            content: "Comparing concurrency models: POSIX threads, event loops, actor model, and CSP in Rust, Node.js, Erlang, Go.",
            expected: [W, N, N, N, N, N, W, W, B],
        },

        // ====================================================================
        // ReverseEngineering (10) — id 206-215
        // ====================================================================
        LabeledItem { id: 206, category: RE, source_type: "hackernews",
            title: "Reverse engineering a proprietary binary protocol",
            content: "Methodology for reverse engineering protocols: packet capture, entropy analysis, and building open implementations.",
            expected: [N, N, N, N, N, N, B, N, B],
        },
        LabeledItem { id: 207, category: RE, source_type: "hackernews",
            title: "Ghidra vs IDA Pro: Disassembler comparison",
            content: "Comparing NSA's Ghidra with IDA Pro: feature sets, scripting APIs, decompiler quality, and cost.",
            expected: [N, N, N, N, N, N, B, N, B],
        },
        LabeledItem { id: 208, category: RE, source_type: "hackernews",
            title: "Fuzzing with libFuzzer and AFL++",
            content: "Coverage-guided fuzzing: libFuzzer integration, AFL++ corpus management, and CI pipeline integration.",
            expected: [W, N, N, N, N, N, W, N, N],
        },
        LabeledItem { id: 209, category: RE, source_type: "hackernews",
            title: "Malware analysis: Understanding ransomware",
            content: "Technical analysis of a ransomware sample: unpacking, disassembly, and encryption implementation.",
            expected: [N, N, N, W, N, N, N, N, N],
        },
        LabeledItem { id: 210, category: RE, source_type: "hackernews",
            title: "Decompiling Java bytecode with CFR",
            content: "CFR and other Java decompilers: how bytecode is decompiled and limitations when obfuscation is applied.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 211, category: RE, source_type: "hackernews",
            title: "Game hacking: How aimbots work",
            content: "Technical explanation of game hacks: memory reading, hooking DirectX, and anti-cheat countermeasures.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 212, category: RE, source_type: "hackernews",
            title: "iOS jailbreaking: The current state",
            content: "Current state of iOS jailbreaking: kernel exploits, PAC bypass techniques, and Apple security countermeasures.",
            expected: [N, N, N, N, B, N, N, N, N],
        },
        LabeledItem { id: 213, category: RE, source_type: "hackernews",
            title: "Binary exploitation: Return-oriented programming",
            content: "Return-oriented programming (ROP): bypassing NX/DEP protections and how ASLR makes exploitation harder.",
            expected: [N, N, N, N, N, N, N, N, B],
        },
        LabeledItem { id: 214, category: RE, source_type: "hackernews",
            title: "Hardware hacking: JTAG debugging embedded devices",
            content: "Using JTAG interfaces to debug and reverse engineer embedded devices and extract firmware.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 215, category: RE, source_type: "hackernews",
            title: "Symbolic execution with KLEE",
            content: "Symbolic execution for finding bugs: KLEE's approach to exploring program paths with SMT constraint solving.",
            expected: [N, N, N, N, N, N, N, N, B],
        },

        // ====================================================================
        // ReleaseNotes expansion (5) — id 216-220
        // ====================================================================
        LabeledItem { id: 216, category: RN, source_type: "hackernews",
            title: "Go 1.23 Release Notes",
            content: "Go 1.23 brings range-over-func iterators, unique package, and timer changes. Improved generics type inference and new standard library additions.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     N,     B,   B,    S,     N],
        },
        LabeledItem { id: 217, category: RN, source_type: "hackernews",
            title: "GHC 9.10 Release Announcement",
            content: "GHC 9.10 brings LinearTypes improvements, JavaScript backend enhancements, and new type-level features for Haskell developers.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     N,     N,   N,    N,     S],
        },
        LabeledItem { id: 218, category: RN, source_type: "hackernews",
            title: "Grafana 11 Release: Unified Alerting and Explore Metrics",
            content: "Grafana 11 introduces unified alerting GA, Explore Metrics for PromQL, dashboard improvements, and enhanced Kubernetes monitoring dashboards.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   S,     N,     N,   N,    N,     N],
        },
        LabeledItem { id: 219, category: RN, source_type: "hackernews",
            title: "Docker Compose v2.27: Build Improvements and GPU Support",
            content: "Docker Compose v2.27 adds GPU device support, build provenance attestation, improved secrets handling, and faster container startup.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   S,     N,     N,   N,    N,     N],
        },
        LabeledItem { id: 220, category: RN, source_type: "hackernews",
            title: "Hugging Face Transformers 4.40: New Model Architectures",
            content: "Transformers 4.40 adds Gemma, Mamba, Jamba model support, improved quantization with GGUF, and faster generation with speculative decoding.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  S,   N,   N,     N,     N,   B,    N,     N],
        },

        // ====================================================================
        // ReleaseNotes expansion (5 more) — id 221-225
        // ====================================================================
        LabeledItem { id: 221, category: RN, source_type: "blog",
            title: "Deno 2.0: Node compatibility and npm support",
            content: "Deno 2.0 ships with full Node.js compatibility, npm package support, stable KV database, and improved JSR publishing workflow.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   W,   N,     N,     N,   W,    N,     N],
        },
        LabeledItem { id: 222, category: RN, source_type: "blog",
            title: "Rails 8.0: Solid Queue and Solid Cache",
            content: "Rails 8.0 introduces Solid Queue for background jobs, Solid Cache for caching, and Kamal 2 for deployment without Docker.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     N,     N,   N,    N,     N],
        },
        LabeledItem { id: 223, category: RN, source_type: "blog",
            title: "PostgreSQL 17: Incremental backup and JSON_TABLE",
            content: "PostgreSQL 17 adds incremental backup, JSON_TABLE for SQL/JSON queries, improved COPY performance, and memory management.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   W,     N,     N,   W,    N,     N],
        },
        LabeledItem { id: 224, category: RN, source_type: "blog",
            title: "Expo SDK 51: New Architecture by default",
            content: "Expo SDK 51 enables React Native New Architecture by default, adds Expo Router v3, and improves EAS Build performance.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     S,     N,   N,    N,     N],
        },
        LabeledItem { id: 225, category: RN, source_type: "blog",
            title: "Svelte 5: Runes and fine-grained reactivity",
            content: "Svelte 5 introduces runes for fine-grained reactivity, replaces stores with $state and $derived, improved TypeScript support.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   W,   N,     N,     N,   N,    N,     N],
        },

        // ====================================================================
        // BusinessNoise expansion (5 more) — id 226-230
        // ====================================================================
        LabeledItem { id: 226, category: BC, source_type: "hackernews",
            title: "Stripe raises Series I at $65B valuation",
            content: "Stripe closes new funding round at $65 billion valuation, plans expansion into banking and treasury services.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 227, category: BC, source_type: "hackernews",
            title: "How we grew from 0 to $1M ARR in 6 months",
            content: "Founder shares growth playbook: product-led growth, community-driven acquisition, and pricing experiments that worked.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 228, category: BC, source_type: "hackernews",
            title: "The SaaS metrics that actually matter",
            content: "Beyond MRR and churn: net revenue retention, payback period, and burn multiple for evaluating SaaS health.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 229, category: BC, source_type: "hackernews",
            title: "Why enterprise sales cycles are getting longer",
            content: "Enterprise sales cycles have increased by 40%. Budget scrutiny, procurement changes, and security review bottlenecks.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 230, category: BC, source_type: "hackernews",
            title: "Bootstrapped vs VC-funded: A 5-year retrospective",
            content: "Founder compares bootstrapped and VC-funded paths after running both. Revenue, control, and lifestyle tradeoffs.",
            expected: [N, N, N, N, N, N, N, N, N],
        },

        // ====================================================================
        // HNDiscussion expansion (5 more) — id 231-235
        // ====================================================================
        LabeledItem { id: 231, category: HI, source_type: "hackernews",
            title: "Ask HN: How do you handle imposter syndrome?",
            content: "Community discussion on imposter syndrome in tech: coping strategies, prevalence among senior engineers, and normalization.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 232, category: HI, source_type: "hackernews",
            title: "Ask HN: Best resources for learning distributed systems?",
            content: "HN recommends distributed systems resources: DDIA book, MIT 6.824, Jepsen blog, and hands-on projects with Raft consensus.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     N,     N,   B,    B,     N],
        },
        LabeledItem { id: 233, category: HI, source_type: "hackernews",
            title: "Tell HN: I built a programming language in a weekend",
            content: "Developer shares experience building a toy language: parser combinators, tree-walking interpreter, and surprising lessons learned.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     N,     N,   B,    N,     B],
        },
        LabeledItem { id: 234, category: HI, source_type: "hackernews",
            title: "Ask HN: What's your unpopular tech opinion?",
            content: "Controversial tech opinions: microservices are overused, TDD is cargo cult, Rust is overhyped, and Go is underrated.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 235, category: HI, source_type: "hackernews",
            title: "Tell HN: After 10 years of Go, switching to Rust",
            content: "A Go developer's journey to Rust: ownership model challenges, performance gains, and ecosystem comparison after a decade of Go.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [B,  N,   N,   N,     N,     N,   B,    B,     N],
        },

        // ====================================================================
        // DistantlyRelevant expansion (5 more) — id 236-240
        // ====================================================================
        LabeledItem { id: 236, category: DI, source_type: "hackernews",
            title: "How DNS actually works: A visual guide",
            content: "Visual explanation of DNS resolution: recursive resolvers, authoritative nameservers, caching layers, and common misconfigurations.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   W,     N,     N,   W,    N,     N],
        },
        LabeledItem { id: 237, category: DI, source_type: "hackernews",
            title: "Understanding CPU branch prediction",
            content: "CPU branch prediction internals: branch target buffers, speculative execution, and why sorted arrays are faster to process.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [W,  N,   N,   N,     N,     N,   W,    N,     B],
        },
        LabeledItem { id: 238, category: DI, source_type: "hackernews",
            title: "The history of version control: RCS to Git",
            content: "Version control evolution: RCS, CVS, Subversion, Mercurial, and Git. How distributed VCS changed software development.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 239, category: DI, source_type: "hackernews",
            title: "How databases use B-trees for indexing",
            content: "B-tree data structure in databases: insertion, splitting, rebalancing, and why B+ trees are preferred for disk-based storage.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [W,  N,   N,   N,     N,     N,   W,    N,     B],
        },
        LabeledItem { id: 240, category: DI, source_type: "hackernews",
            title: "POSIX signals explained: from SIGTERM to SIGKILL",
            content: "POSIX signal handling: signal types, default actions, graceful shutdown patterns, and signal safety in multithreaded programs.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [W,  N,   N,   W,     N,     N,   W,    N,     N],
        },

        // ====================================================================
        // ReverseEngineering expansion (5 more) — id 241-245
        // ====================================================================
        LabeledItem { id: 241, category: RE, source_type: "hackernews",
            title: "Reverse engineering a wireless protocol with SDR",
            content: "Using software-defined radio to reverse engineer a proprietary wireless protocol: signal capture, demodulation, and packet parsing.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     N,     N,   B,    N,     N],
        },
        LabeledItem { id: 242, category: RE, source_type: "hackernews",
            title: "Binary exploitation CTF walkthrough: stack pivoting",
            content: "CTF writeup demonstrating stack pivoting technique: ROP chain construction, gadget finding, and defeating ASLR on modern Linux.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 243, category: RE, source_type: "hackernews",
            title: "Analyzing iOS app traffic with mitmproxy",
            content: "Using mitmproxy to intercept and analyze iOS app network traffic: certificate pinning bypass, API discovery, and protocol analysis.",
            //        rust py   ts   devops mobile boot power switch niche
            expected: [N,  N,   N,   N,     B,     N,   N,    N,     N],
        },
        LabeledItem { id: 244, category: RE, source_type: "hackernews",
            title: "Decompiling Java bytecode: tools and techniques",
            content: "Java decompilation tools compared: CFR, Procyon, Fernflower. Handling obfuscation, lambda expressions, and modern Java features.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
        LabeledItem { id: 245, category: RE, source_type: "hackernews",
            title: "Hardware hacking: extracting firmware from IoT devices",
            content: "Extracting firmware from IoT devices using UART, SPI flash dumping, and JTAG. Analyzing embedded Linux filesystems for vulnerabilities.",
            expected: [N, N, N, N, N, N, N, N, N],
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn corpus_minimum_size() {
        let c = corpus();
        assert!(
            c.len() >= 245,
            "Corpus must have 245+ items, got {}",
            c.len()
        );
    }

    #[test]
    fn corpus_ids_unique() {
        let c = corpus();
        let mut seen = std::collections::HashSet::new();
        for item in &c {
            assert!(seen.insert(item.id), "Duplicate id: {}", item.id);
        }
    }

    #[test]
    fn corpus_has_all_categories() {
        let c = corpus();
        let categories = [
            ContentCategory::DirectMatch,
            ContentCategory::AdjacentMatch,
            ContentCategory::CrossDomainNoise,
            ContentCategory::Borderline,
            ContentCategory::CareerNoise,
            ContentCategory::SecurityAdvisory,
            ContentCategory::IntroductoryNoise,
            ContentCategory::ShowHNNoise,
            ContentCategory::MetaNoise,
            ContentCategory::BusinessNoise,
            ContentCategory::ReleaseNotes,
            ContentCategory::HNDiscussion,
            ContentCategory::DistantlyRelevant,
            ContentCategory::ReverseEngineering,
        ];
        for cat in &categories {
            assert!(
                c.iter().any(|i| &i.category == cat),
                "Missing category: {cat:?}"
            );
        }
    }

    #[test]
    fn cross_domain_noise_no_strong_for_rust() {
        let c = corpus();
        for item in c
            .iter()
            .filter(|i| i.category == ContentCategory::CrossDomainNoise)
        {
            assert_ne!(
                item.expected[0],
                ExpectedOutcome::StrongRelevant,
                "CDN item {} has StrongRelevant for rust",
                item.id
            );
        }
    }

    #[test]
    fn hiring_all_not_relevant() {
        let c = corpus();
        for item in c
            .iter()
            .filter(|i| i.category == ContentCategory::CareerNoise)
        {
            for (pi, &e) in item.expected.iter().enumerate() {
                assert_eq!(
                    e,
                    ExpectedOutcome::NotRelevant,
                    "CareerNoise item {} persona {} should be NotRelevant, got {e:?}",
                    item.id,
                    pi
                );
            }
        }
    }

    #[test]
    fn showhn_all_not_relevant() {
        let c = corpus();
        for item in c
            .iter()
            .filter(|i| i.category == ContentCategory::ShowHNNoise)
        {
            for (pi, &e) in item.expected.iter().enumerate() {
                assert_eq!(
                    e,
                    ExpectedOutcome::NotRelevant,
                    "ShowHNNoise item {} persona {} should be NotRelevant, got {e:?}",
                    item.id,
                    pi
                );
            }
        }
    }
}
