import { lazy } from 'react';
import type { ToolDescriptor } from '../../types/toolkit';

export const TOOLS: ToolDescriptor[] = [
  // Intelligence Tools — 4DA-connected
  {
    id: 'stack-health',
    name: 'Stack Health',
    description: 'Tech stack health across projects — freshness, security, momentum',
    icon: 'heartPulse',
    category: 'intelligence',
    pro: true,
    component: lazy(() => import('./tools/StackHealth')),
    keywords: ['stack', 'health', 'freshness', 'security', 'momentum', 'dependencies'],
  },
  {
    id: 'sovereign-profile',
    name: 'Sovereign Profile',
    description: 'Hardware facts and generated stack document from your sovereign profile',
    icon: 'shield',
    category: 'intelligence',
    pro: false,
    component: lazy(() => import('./tools/SovereignProfileView')),
    keywords: ['sovereign', 'profile', 'hardware', 'cpu', 'gpu', 'ram', 'stack', 'document'],
  },
  {
    id: 'source-debugger',
    name: 'Source Debugger',
    description: 'Test any RSS/Atom URL and see what 4DA extracts',
    icon: 'rss',
    category: 'intelligence',
    pro: false,
    component: lazy(() => import('./tools/SourceDebugger')),
    keywords: ['rss', 'atom', 'feed', 'source', 'debug', 'test', 'xml'],
  },
  {
    id: 'scoring-sandbox',
    name: 'Scoring Sandbox',
    description: 'Paste a title and see how your interest profile scores it',
    icon: 'target',
    category: 'intelligence',
    pro: false,
    component: lazy(() => import('./tools/ScoringSandbox')),
    keywords: ['score', 'scoring', 'relevance', 'interest', 'pasifa', 'test'],
  },
  {
    id: 'decision-log',
    name: 'Decision Log',
    description: 'Track tech decisions with confidence scoring and rationale',
    icon: 'scale',
    category: 'intelligence',
    pro: false,
    component: lazy(() => import('./tools/DecisionLog')),
    keywords: ['decision', 'log', 'architecture', 'tech', 'choice', 'rationale'],
  },
  {
    id: 'export-pack',
    name: 'Export Pack',
    description: 'Shareable developer profile: DNA, radar, and decisions as markdown',
    icon: 'package',
    category: 'intelligence',
    pro: true,
    component: lazy(() => import('./tools/ExportPack')),
    keywords: ['export', 'profile', 'dna', 'radar', 'share', 'markdown', 'download'],
  },
  // Utility Tools — Generic developer utilities
  // Phase 1 — Pure Frontend
  {
    id: 'json-yaml',
    name: 'JSON Viewer',
    description: 'Format, minify, diff, and explore JSON with a collapsible tree',
    icon: 'braces',
    category: 'formatters',
    pro: false,
    component: lazy(() => import('./tools/JsonYamlViewer')),
    keywords: ['json', 'yaml', 'format', 'minify', 'tree', 'diff', 'prettify'],
  },
  {
    id: 'regex',
    name: 'Regex Playground',
    description: 'Test patterns with live highlighting, capture groups, and match indices',
    icon: 'regex',
    category: 'formatters',
    pro: false,
    component: lazy(() => import('./tools/RegexPlayground')),
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test', 'capture'],
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors, convert formats, and check WCAG contrast',
    icon: 'palette',
    category: 'formatters',
    pro: false,
    component: lazy(() => import('./tools/ColorPicker')),
    keywords: ['color', 'hex', 'rgb', 'hsl', 'contrast', 'wcag', 'palette'],
  },
  {
    id: 'encoder-decoder',
    name: 'Encode / Decode',
    description: 'Base64, URL encode, JWT decode, SHA-256/512 hashing',
    icon: 'lock',
    category: 'encoders',
    pro: false,
    component: lazy(() => import('./tools/EncoderDecoder')),
    keywords: ['base64', 'url', 'encode', 'decode', 'jwt', 'hash', 'sha'],
  },
  // Phase 3
  {
    id: 'diff-viewer',
    name: 'Diff Viewer',
    description: 'Compare two texts with unified or side-by-side diff',
    icon: 'diff',
    category: 'formatters',
    pro: false,
    component: lazy(() => import('./tools/DiffViewer')),
    keywords: ['diff', 'compare', 'text', 'merge'],
  },
  // Phase 5 — Generators
  {
    id: 'cron-builder',
    name: 'Cron Builder',
    description: 'Build cron expressions visually with human-readable output',
    icon: 'clock',
    category: 'generators',
    pro: false,
    component: lazy(() => import('./tools/CronBuilder')),
    keywords: ['cron', 'schedule', 'timer', 'job'],
  },
  {
    id: 'mock-data',
    name: 'Mock Data',
    description: 'Generate names, emails, UUIDs, timestamps, and JSON payloads',
    icon: 'database',
    category: 'generators',
    pro: false,
    component: lazy(() => import('./tools/MockDataGenerator')),
    keywords: ['mock', 'fake', 'data', 'uuid', 'name', 'email', 'generate'],
  },
  // Phase 2 — System Integration
  {
    id: 'port-scanner',
    name: 'Port Scanner',
    description: 'Scan listening ports, identify processes, and kill rogue services',
    icon: 'network',
    category: 'system',
    pro: false,
    component: lazy(() => import('./tools/PortScanner')),
    keywords: ['port', 'network', 'process', 'pid', 'listen', 'kill', 'netstat'],
  },
  {
    id: 'env-snapshot',
    name: 'Env Snapshot',
    description: 'Capture git, runtime versions, and OS info — copy as markdown',
    icon: 'terminal',
    category: 'system',
    pro: false,
    component: lazy(() => import('./tools/EnvironmentSnapshot')),
    keywords: ['env', 'environment', 'git', 'node', 'version', 'snapshot', 'system'],
  },
  {
    id: 'http-probe',
    name: 'HTTP Probe',
    description: 'Send HTTP requests with full headers, body, and response inspection',
    icon: 'globe',
    category: 'system',
    pro: true,
    component: lazy(() => import('./tools/HttpProbe')),
    keywords: ['http', 'api', 'request', 'rest', 'get', 'post', 'curl', 'fetch'],
  },
];

export function getToolById(id: string): ToolDescriptor | undefined {
  return TOOLS.find((t) => t.id === id);
}
