//! Sovereign Content Engine — personalized STREETS module content.
//!
//! Five-level pipeline that transforms static markdown into personalized lessons
//! using sovereign profile data, tech radar, regional info, and playbook progress.
//!
//! - L1: Value interpolation (`{= path | fallback("...") =}`)
//! - L2: Conditional sections (`{? if condition ?}...{? endif ?}`)
//! - L3: Computed insight cards (no-LLM structured data)
//! - L4: Sovereign connection blocks (cross-data correlations)
//! - L5: Temporal evolution (diff ribbons, feed echoes, progressive reveals)

pub mod cache;
pub mod commands;
pub mod context;
pub mod llm_engine;
pub mod nollm_engine;
pub mod template_processor;
pub mod temporal;

use serde::{Deserialize, Serialize};

// ============================================================================
// Core Response Types
// ============================================================================

/// Top-level response returned to the frontend for a personalized lesson.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PersonalizedLesson {
    /// L1/L2-processed markdown content (immediate render).
    pub content: String,
    /// L3 insight cards computed from sovereign data.
    pub insight_blocks: Vec<InsightBlock>,
    /// L4 cross-data sovereign connection blocks.
    pub mirror_blocks: Vec<MirrorBlock>,
    /// L5 temporal evolution blocks.
    pub temporal_blocks: Vec<TemporalBlock>,
    /// How deep personalization reached (depends on available data).
    pub depth: PersonalizationDepth,
    /// Context hash for cache key (SHA-256 of PersonalizationContext).
    pub context_hash: String,
}

/// How much personalization was applied to this lesson.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PersonalizationDepth {
    /// Number of L1 tokens successfully resolved.
    pub l1_resolved: u32,
    /// Number of L1 tokens that fell back to default text.
    pub l1_fallbacks: u32,
    /// Number of L2 conditional sections evaluated.
    pub l2_evaluated: u32,
    /// Number of L3 insight cards generated.
    pub l3_cards: u32,
    /// Number of L4 connection blocks generated.
    pub l4_connections: u32,
    /// Number of L5 temporal blocks generated.
    pub l5_temporal: u32,
    /// Whether LLM upgrades are pending (async hydration).
    pub llm_pending: bool,
}

// ============================================================================
// L3: Insight Blocks
// ============================================================================

/// A computed insight block placed at an injection point in the lesson.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InsightBlock {
    /// Unique block ID matching the `{@ insight id @}` marker.
    pub block_id: String,
    /// Position in the lesson content (for frontend placement).
    pub position: BlockPosition,
    /// The actual content — either a structured card or LLM prose.
    pub content: InsightContent,
    /// Which data sources contributed to this block.
    pub source_labels: Vec<String>,
    /// Data coverage confidence (0.0 = guessing, 1.0 = full data).
    pub confidence: f64,
}

/// Where an insight block should appear relative to the lesson content.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BlockPosition {
    /// Replace the injection marker in-place.
    #[serde(rename = "injection")]
    Injection { marker_id: String },
    /// Append after the lesson content.
    #[serde(rename = "end")]
    End,
}

/// Content of an insight block — either structured data or prose.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum InsightContent {
    /// Structured data card (no-LLM path). Always available.
    #[serde(rename = "card")]
    Card(SovereignInsightCard),
    /// Rich prose generated by LLM. Replaces card when available.
    #[serde(rename = "prose")]
    Prose { text: String, model: String },
}

// ============================================================================
// No-LLM Insight Cards
// ============================================================================

/// A structured data card computed from sovereign data (no LLM required).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SovereignInsightCard {
    /// Card type determines visualization and layout.
    pub card_type: CardType,
    /// Title displayed on the card.
    pub title: String,
    /// Structured data points (label → value with context).
    pub data_points: Vec<DataPoint>,
    /// Optional visualization data.
    pub visualization: Option<Visualization>,
}

/// Type of sovereign insight card.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CardType {
    HardwareBenchmark,
    StackFit,
    CostProjection,
    TShapeDiagram,
    EngineRanking,
    BlindSpotAlert,
    CompetitivePosition,
    TemporalDelta,
    FeedEcho,
    ProgressGate,
}

/// A single data point in an insight card.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataPoint {
    pub label: String,
    pub value: String,
    /// Additional context shown on hover or expansion.
    pub context: Option<String>,
    /// Whether this data point should be visually highlighted.
    pub highlight: bool,
}

/// Visualization data for rendering charts/diagrams.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Visualization {
    #[serde(rename = "bar_chart")]
    BarChart {
        bars: Vec<BarEntry>,
        max_value: f64,
        unit: String,
    },
    #[serde(rename = "rank_list")]
    RankList { items: Vec<RankItem> },
    #[serde(rename = "t_shape")]
    TShape {
        primary: String,
        depth_label: String,
        adjacent: Vec<String>,
        breadth_label: String,
    },
    #[serde(rename = "rate_table")]
    RateTable {
        headers: Vec<String>,
        rows: Vec<TableRow>,
    },
    #[serde(rename = "diff_ribbon")]
    DiffRibbon {
        added: Vec<String>,
        removed: Vec<String>,
        changed: Vec<DiffChange>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BarEntry {
    pub label: String,
    pub value: f64,
    pub highlight: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RankItem {
    pub rank: u32,
    pub name: String,
    pub score: f64,
    /// Whether this item matches the user's stack.
    pub matches_stack: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableRow {
    pub cells: Vec<String>,
    pub highlight: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffChange {
    pub field: String,
    pub old_value: String,
    pub new_value: String,
}

// ============================================================================
// L4: Mirror / Sovereign Connection Blocks
// ============================================================================

/// A cross-data correlation insight (L4).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MirrorBlock {
    /// Unique block ID.
    pub block_id: String,
    /// Connection type determines the analysis pattern.
    pub connection_type: ConnectionType,
    /// Human-readable headline for the connection.
    pub headline: String,
    /// The computed insight text.
    pub insight: String,
    /// Which data sources were correlated.
    pub data_sources: Vec<String>,
    /// Optional structured content for detailed view.
    pub content: Option<InsightContent>,
}

/// Types of cross-data sovereign connections.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConnectionType {
    /// Blind spot that could become a competitive moat.
    BlindSpotMoat,
    /// Feed engagement patterns that predict engine fit.
    FeedPredictsEngine,
    /// Tech radar momentum that suggests timing.
    RadarMomentum,
}

// ============================================================================
// L5: Temporal Evolution Blocks
// ============================================================================

/// A temporal evolution block showing changes since last read.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemporalBlock {
    /// Unique block ID.
    pub block_id: String,
    /// The type of temporal block.
    pub block_type: TemporalBlockType,
}

/// Types of temporal evolution blocks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TemporalBlockType {
    /// Profile changes since last lesson read.
    #[serde(rename = "diff_ribbon")]
    DiffRibbon {
        added: Vec<String>,
        removed: Vec<String>,
        changed: Vec<DiffChange>,
    },
    /// New content unlocked by upstream module completion.
    #[serde(rename = "progressive_reveal")]
    ProgressiveReveal {
        newly_completed: Vec<String>,
        unlocked_content: Vec<String>,
    },
    /// Feed items matching lesson topics since last read.
    #[serde(rename = "feed_echo")]
    FeedEcho { items: Vec<FeedEchoItem> },
}

/// A feed item that echoes a lesson topic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedEchoItem {
    pub title: String,
    pub source: String,
    pub url: Option<String>,
    pub matched_topic: String,
    pub fetched_at: String,
}
