// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActiveConcern = { subject: string, concern_type: string, summary: string, priority: string, related_decision_id: bigint | null, };
