// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { 
/**
 * Canonical id. Must be in `ACTION_IDS`.
 */
action_id: string, label: string, description: string, };
