// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One advisor's opinion on an artifact, stamped with provenance.
 *
 * Advisors are LLM sensors in the Intelligence Mesh. They produce a raw
 * score (their native 1-5 or 0-1 output) plus a `normalized_score`
 * (the same value mapped onto the canonical 0-1 scale via that model's
 * calibration curve). If calibration is absent the two are equal and
 * `calibration_id` is the `PRE_MESH_CALIBRATION_ID` sentinel.
 */
export type AdvisorSignal = { 
/**
 * Provider + model identity (not the full hash — UI-friendly).
 */
provider: string, model: string, 
/**
 * Task this signal pertains to: "judge", "rerank", "summarize", etc.
 */
task: string, 
/**
 * Advisor's raw confidence or score (0.0-1.0 after normalization
 * to that scale; some providers output 1-5 which the caller
 * normalizes before storing here).
 */
raw_score: number, 
/**
 * Calibrated score on the canonical 0-1 scale. Equal to `raw_score`
 * when no calibration curve has been computed for this model+task.
 */
normalized_score: number, 
/**
 * Confidence in the signal itself (distinct from the score value).
 * 0.0 means "no judgment was produced"; 1.0 means "high confidence".
 */
confidence: number, 
/**
 * Human-readable rationale, if the advisor produced one.
 */
reason: string | null, 
/**
 * Prompt version used to elicit the signal, e.g. "judge-v1-2026-04-15".
 */
prompt_version: string | null, 
/**
 * Calibration curve applied (or `PRE_MESH_CALIBRATION_ID` sentinel).
 */
calibration_id: string | null, };
