// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveConcern } from "./ActiveConcern";
import type { AgentMemoryEntry } from "./AgentMemoryEntry";
import type { DecisionSummary } from "./DecisionSummary";
import type { EcosystemChange } from "./EcosystemChange";
import type { SignalSummary } from "./SignalSummary";

export type AgentSessionBrief = { generated_at: string, version: string, agent_type: string | null, active_decisions: Array<DecisionSummary>, ecosystem_changes: Array<EcosystemChange>, active_concerns: Array<ActiveConcern>, open_signals: Array<SignalSummary>, recent_briefing: string | null, agent_memories: Array<AgentMemoryEntry>, };
