// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryType } from "./MemoryType";

export type AgentMemoryEntry = { id: bigint, session_id: string, agent_type: string, memory_type: MemoryType, subject: string, content: string, context_tags: Array<string>, created_at: string, expires_at: string | null, promoted_to_decision_id: bigint | null, };
