// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignmentConflict } from "./AlignmentConflict";
import type { DeveloperDecision } from "./DeveloperDecision";

export type AlignmentResult = { aligned: boolean, relevant_decisions: Array<DeveloperDecision>, conflicts: Array<AlignmentConflict>, confidence: number, };
