// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status update for the UI (sent via events)
 */
export type AnalysisStatus = { stage: string, progress: number, message: string, items_processed: number, items_total: number, };
