// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceRelevance } from "./SourceRelevance";

/**
 * Background analysis state
 */
export type AnalysisState = { running: boolean, completed: boolean, error: string | null, results: Array<SourceRelevance> | null, 
/**
 * When analysis started (unix timestamp seconds)
 */
started_at: bigint | null, 
/**
 * When analysis last completed successfully (ISO string for DB query compat)
 */
last_completed_at: string | null, 
/**
 * Top items that fell just below the relevance threshold (for zero-result guidance)
 */
near_misses: Array<SourceRelevance> | null, };
