// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Categories of AI-influenced artifacts that carry provenance.
 *
 * Adding a new variant is a semver-adjacent change: the underlying text
 * value is written to SQL and must remain stable across releases. When
 * adding a variant, also update `as_sql_str` and `from_sql_str`.
 */
export type ArtifactKind = "Score" | "Rerank" | "Summary" | "Briefing" | "SearchSynthesis" | "ChannelOverview" | "Translation" | "Embed" | "Chat";
