// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated audit summary over a time window.
 */
export type AuditSummary = { total_events: bigint, events_by_action: Array<[string, bigint]>, events_by_actor: Array<[string, bigint]>, events_by_day: Array<[string, bigint]>, };
