// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single audit log entry.
 */
export type AuditEntry = { id: bigint, event_id: string, team_id: string, actor_id: string, actor_display_name: string, action: string, resource_type: string, resource_id: string | null, details: any | null, created_at: string, };
