// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a complete autophagy cycle, surfaced to the frontend.
 */
export type AutophagyCycleResult = { items_analyzed: bigint, items_pruned: bigint, calibrations_produced: bigint, topic_decay_rates_updated: bigint, source_autopsies_produced: bigint, anti_patterns_detected: bigint, decision_outcomes_analyzed: bigint, duration_ms: bigint, };
