// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutophagyCycleResult } from "./AutophagyCycleResult";

/**
 * Autophagy system status overview.
 */
export type AutophagyStatus = { last_cycle: AutophagyCycleResult | null, total_cycles: bigint, total_calibrations: bigint, total_anti_patterns: bigint, };
