// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlindSpotRecommendation = { 
/**
 * e.g., "Set up a watch for Rust security"
 */
action: string, reason: string, 
/**
 * high, medium, low
 */
priority: string, };
