// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlindSpotRecommendation } from "./BlindSpotRecommendation";
import type { MissedSignal } from "./MissedSignal";
import type { StaleTopic } from "./StaleTopic";
import type { UncoveredDep } from "./UncoveredDep";

export type BlindSpotReport = { 
/**
 * 0-100, higher = more blind spots
 */
overall_score: number, uncovered_dependencies: Array<UncoveredDep>, stale_topics: Array<StaleTopic>, missed_signals: Array<MissedSignal>, recommendations: Array<BlindSpotRecommendation>, generated_at: string, };
