// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Honest progress toward the first calibration fit. Every number here
 * is real and actionable: `labeled_total` is distinct items with
 * explicit feedback, `min_fit_samples` is the fitter's actual floor,
 * `curve_fitted` reports whether a curve file exists on disk.
 */
export type CalibrationSprintStatus = { 
/**
 * Distinct source items the user has explicitly labeled. Distinct
 * (not raw row count) because one item's label resolves ALL of
 * that item's calibration samples — repeat labels on the same
 * item add no new fitter signal.
 */
labeledTotal: number, 
/**
 * Read from [`crate::calibration_fitter::MIN_FIT_SAMPLES`], never
 * hardcoded here.
 */
minFitSamples: number, 
/**
 * Whether any calibration curve has been fit and persisted.
 */
curveFitted: boolean, };
