// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One labeling card in the review sprint. Plain card struct, NOT an
 * EvidenceItem — see module docs.
 */
export type CalibrationSprintCard = { 
/**
 * Serialized as a plain JSON number (i64 ids fit comfortably).
 */
sourceItemId: number, title: string, snippet: string, sourceType: string, url: string | null, };
