// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single calibration insight: how far off the system was for a topic.
 */
export type CalibrationInsight = { topic: string, 
/**
 * positive = under-scored (should rank higher), negative = over-scored
 */
delta: number, sample_size: bigint, confidence: number, };
