// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractStatus } from "./ContractStatus";

export type CommitmentContract = { id: bigint, decision_statement: string, refutation_condition: string, subject: string, status: ContractStatus, created_at: string, triggered_at: string | null, trigger_item_id: bigint | null, };
