// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compound advantage metric — measures cumulative value of the intelligence pipeline.
 */
export type CompoundAdvantageScore = { 
/**
 * 0 - 100 composite score
 */
score: number, 
/**
 * Period this score covers: daily, weekly, monthly
 */
period: string, items_surfaced: bigint, avg_lead_time_hours: number, windows_opened: bigint, windows_acted: bigint, windows_expired: bigint, knowledge_gaps_closed: bigint, 
/**
 * How well the system's predictions match reality (0.0 - 1.0)
 */
calibration_accuracy: number, 
/**
 * -1.0 (declining) to +1.0 (growing) trend vs previous period
 */
trend: number, };
