// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidenceProvenance } from "./ConfidenceProvenance";

export type Confidence = { 
/**
 * 0.0–1.0.
 */
value: number, 
/**
 * Where this number came from.
 */
provenance: ConfidenceProvenance, 
/**
 * If provenance is `Calibrated`, the N of samples. `None` for others.
 */
sample_size: number | null, };
