// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cross-team signal correlation detected across an organization.
 */
export type CrossTeamCorrelation = { correlation_id: string, signal_type: string, teams_affected: Array<[string, number]>, org_severity: string, first_detected: string, recommendation: string, };
