// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summarizes the staleness of source data. Attached to briefings and blind spot
 * reports so the frontend can distinguish "nothing happening" from "data pipeline
 * is broken / sources are offline."
 */
export type DataFreshness = { 
/**
 * Hours since the newest item was first discovered (None if table is empty).
 */
newest_item_age_hours: number | null, 
/**
 * Number of source items first discovered in the last 24 hours.
 */
items_last_24h: number, 
/**
 * Number of source items first discovered in the last 72 hours.
 */
items_last_72h: number, 
/**
 * Hours since any source adapter last succeeded (None if health has never run).
 */
newest_source_check_age_hours: number | null, 
/**
 * Number of successful source checks in the last 24 hours.
 */
source_checks_last_24h: number, 
/**
 * Number of successful source checks in the last 72 hours.
 */
source_checks_last_72h: number, 
/**
 * Source adapters currently reporting failures or open circuits.
 */
failing_sources: number, 
/**
 * Source adapters with no successful check in more than seven days.
 */
stale_sources: number, 
/**
 * Total registered source adapters (for computing health percentage).
 */
total_sources: number, 
/**
 * True when neither source items nor successful source checks have appeared in 3 days.
 */
is_stale: boolean, 
/**
 * True when no source adapter has succeeded in the last 24 hours,
 * even if the system is not fully stale. Signals degraded freshness.
 */
no_recent_fetches: boolean, 
/**
 * Items scored in the most recent fetch+score cycle, read from the latest
 * `engine_runs` receipt (Verax ground truth). Written by BOTH the in-app
 * background scheduler AND the headless engine — so it is populated even when
 * the external Verax verifier / headless task is disabled. None only when no
 * cycle has ever recorded a receipt (brand-new install); the freshness line
 * then falls back to the `newest_item_age_hours` watermark.
 */
last_run_items_scored: number | null, 
/**
 * Source adapters that succeeded in the most recent recorded cycle.
 */
last_run_sources_succeeded: number | null, 
/**
 * Source adapters that failed in the most recent recorded cycle.
 */
last_run_sources_failed: number | null, 
/**
 * Minutes since the most recent recorded cycle completed. None with no receipt.
 */
last_run_age_minutes: number | null, };
