// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbStats } from "./DbStats";

/**
 * Data health overview: DB stats + retention settings.
 */
export type DataHealth = { stats: DbStats, retention_days: number, db_size_mb: number, health_status: string, };
