// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summarizes the staleness of source data. Attached to briefings and blind spot
 * reports so the frontend can distinguish "nothing happening" from "data pipeline
 * is broken / sources are offline."
 */
export type DataFreshness = { 
/**
 * Hours since the newest item was ingested (None if table is empty).
 */
newest_item_age_hours: number | null, 
/**
 * Number of source items created in the last 24 hours.
 */
items_last_24h: number, 
/**
 * Number of source items created in the last 72 hours.
 */
items_last_72h: number, 
/**
 * True when items_last_72h == 0 — the system has received no data in 3 days.
 */
is_stale: boolean, };
