// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbStats = { source_items: bigint, context_chunks: bigint, feedback_count: bigint, sources_count: bigint, embeddings_count: bigint, digested_intelligence: bigint, decision_windows: bigint, autophagy_cycles: bigint, necessity_scores: bigint, db_size_bytes: bigint, oldest_item_date: string | null, };
