// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionType = "tech_choice" | "architecture" | "workflow" | "pattern" | "dependency";
