// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time-bounded decision opportunity surfaced by the intelligence pipeline.
 */
export type DecisionWindow = { id: bigint, 
/**
 * One of: security_patch, migration, adoption, knowledge
 */
window_type: string, title: string, description: string, 
/**
 * 0.0 - 1.0 urgency score
 */
urgency: number, 
/**
 * 0.0 - 1.0 relevance to user's context
 */
relevance: number, 
/**
 * Package name or topic that triggered this window
 */
dependency: string | null, 
/**
 * One of: open, acted, expired, closed
 */
status: string, opened_at: string, expires_at: string | null, 
/**
 * Hours between window open and now (or when acted)
 */
lead_time_hours: number | null, 
/**
 * STREETS engine mapping (Automation, Consulting, Digital Products, Education)
 */
streets_engine: string | null, };
