// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionSummary = { id: bigint, subject: string, decision: string, decision_type: string, confidence: number, status: string, };
