// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DelegationRec = "fully_delegate" | "delegate_with_review" | "collaborate_realtime" | "human_only";
