// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegationFactors } from "./DelegationFactors";
import type { DelegationRec } from "./DelegationRec";

export type DelegationScore = { subject: string, overall_score: number, factors: DelegationFactors, recommendation: DelegationRec, caveats: Array<string>, };
