// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DelegationFactors = { pattern_stability: number, security_sensitivity: number, codebase_complexity: number, decision_density: number, ai_track_record: number, };
