// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-dependency AI verdict. `dep_name` is the DISPLAY name ("libc (crates.io)")
 * so the frontend can join it back to the rendered row.
 */
export type DepAssessment = { dep_name: string, worth_reviewing: boolean, recommendation: string, };
