// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionStatus } from "./DecisionStatus";
import type { DecisionType } from "./DecisionType";

export type DeveloperDecision = { id: bigint, decision_type: DecisionType, subject: string, decision: string, rationale: string | null, alternatives_rejected: Array<string>, context_tags: Array<string>, confidence: number, status: DecisionStatus, superseded_by: bigint | null, created_at: string, updated_at: string, };
