// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes why pipeline and advisor(s) disagreed about an item.
 *
 * Surfaced to the UI as a "judges split" badge. Always a *signal*, never
 * an override — the pipeline's score stands; the flag just tells the
 * reader that judgment on this item is contested.
 */
export type DisagreementKind = "AdvisorSkeptical" | "AdvisorEnthusiastic" | "AdvisorsInternal";
