// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EcosystemChange = { change_type: string, subject: string, summary: string, relevance: number, since: string, };
