// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LLMJudgment } from "./LLMJudgment";
import type { RelevanceMatch } from "./RelevanceMatch";

/**
 * Enhanced relevance result with optional LLM judgment
 */
export type EnhancedRelevance = { id: bigint, title: string, url: string | null, embedding_score: number, matches: Array<RelevanceMatch>, embedding_relevant: boolean, 
/**
 * LLM re-ranking judgment (if enabled)
 */
llm_judgment: LLMJudgment | null, 
/**
 * Final relevance after both stages
 */
final_relevant: boolean, };
