// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvidenceKind = "alert" | "gap" | "missed_signal" | "chain" | "decision" | "retrospective" | "refutation" | "precedent";
