// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Confidence } from "./Confidence";
import type { EvidenceCitation } from "./EvidenceCitation";
import type { EvidenceKind } from "./EvidenceKind";
import type { LensHints } from "./LensHints";
import type { PrecedentRef } from "./PrecedentRef";
import type { Urgency } from "./Urgency";

/**
 * A single unit of actionable intelligence surfaced to the user.
 * Produced by any `EvidenceMaterializer`. Consumed by any lens.
 */
export type EvidenceItem = { 
/**
 * Stable identifier derived from content hash + source. Survives restart.
 */
id: string, 
/**
 * The category of evidence. Determines default rendering hints.
 */
kind: EvidenceKind, 
/**
 * One-line summary. ≤ 120 chars. No trailing period.
 */
title: string, 
/**
 * Full explanation. May be empty during early transition phases.
 */
explanation: string, 
/**
 * Calibrated confidence with provenance.
 */
confidence: Confidence, 
/**
 * Shared urgency scale.
 */
urgency: Urgency, 
/**
 * 0.0 = fully reversible, 1.0 = irreversible. `None` only when
 * reversibility is conceptually N/A for this kind.
 */
reversibility: number | null, 
/**
 * Citations backing the claim. Non-empty for all user-surfaced kinds
 * except `Retrospective`.
 */
evidence: Array<EvidenceCitation>, 
/**
 * Projects this touches (empty if not project-scoped).
 */
affected_projects: Array<string>, 
/**
 * Dependencies this touches (empty if not dep-scoped).
 */
affected_deps: Array<string>, 
/**
 * Actions the user can take. Required for actionable kinds.
 */
suggested_actions: Array<Action>, 
/**
 * Precedents from the Wisdom Graph. Empty allowed on cold-start;
 * should populate after Phase 8.
 */
precedents: Array<PrecedentRef>, 
/**
 * User-set refutation condition. Only populated for accepted
 * `Decision` items tracked by the commitment-contract watcher.
 */
refutation_condition: string | null, 
/**
 * Which lenses this item is a candidate for.
 */
lens_hints: LensHints, 
/**
 * Unix timestamp in millis.
 */
created_at: bigint, 
/**
 * Unix timestamp in millis. `None` for durable items (decisions,
 * retrospectives).
 */
expires_at: bigint | null, };
