// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceItem } from "./EvidenceItem";

/**
 * Standard envelope every lens-backing command returns. Carries the items
 * plus precomputed summary counts (so the UI can render a summary bar
 * without traversing the items list). Emitted by `get_preemption_alerts`,
 * `get_blind_spots`, and Phase 12's Evidence lens command.
 */
export type EvidenceFeed = { items: Array<EvidenceItem>, total: number, critical_count: number, high_count: number, };
