// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalibrationInsight } from "./CalibrationInsight";
import type { SourceQuality } from "./SourceQuality";

/**
 * Rich intelligence pulse: a 7-day snapshot of how the system is performing.
 */
export type IntelligencePulse = { 
/**
 * Total items seen (last_seen) in the last 7 days
 */
items_analyzed_7d: bigint, 
/**
 * Total items that received positive feedback in the last 7 days (proxy for surfaced)
 */
items_surfaced_7d: bigint, 
/**
 * Rejection rate as a percentage (e.g. 99.2)
 */
rejection_rate: number, 
/**
 * Calibration accuracy (0.0–1.0) — average confidence of active calibrations
 */
calibration_accuracy: number, 
/**
 * Top calibration deltas by absolute value (up to 3)
 */
top_calibrations: Array<CalibrationInsight>, 
/**
 * Source quality rankings from stored autopsies
 */
source_quality: Array<SourceQuality>, 
/**
 * Total anti-patterns currently detected (non-superseded)
 */
anti_patterns_detected: bigint, 
/**
 * Total autophagy cycles ever run
 */
total_cycles: bigint, };
