// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntelligenceSnapshot } from "./IntelligenceSnapshot";

/**
 * Intelligence growth data returned to the frontend.
 */
export type IntelligenceGrowth = { snapshots: Array<IntelligenceSnapshot>, current_accuracy: number, total_topics: bigint, total_analyzed: bigint, total_relevant: bigint, };
