// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single point in the intelligence growth trajectory.
 */
export type IntelligenceSnapshot = { recorded_at: string, accuracy: number, topics_learned: bigint, items_analyzed: bigint, relevant_found: bigint, };
