// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LensHints = { briefing: boolean, preemption: boolean, blind_spots: boolean, evidence: boolean, };
