// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LLM judgment attached to a relevance result
 */
export type LLMJudgment = { relevant: boolean, confidence: number, reasoning: string, key_connections: Array<string>, };
