// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MaintenanceResult = { deleted_items: number, deleted_feedback: number, deleted_void: number, deleted_intelligence: number, deleted_windows: number, deleted_cycles: number, deleted_necessity: number, vacuumed: boolean, };
