// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissedSignal = { item_id: bigint, title: string, url: string | null, source_type: string, relevance_score: number, created_at: string, why_relevant: string, 
/**
 * The dependency name this signal relates to (if identified).
 * Used by the frontend to group missed signals under their coverage gap.
 */
dep_name: string | null, };
