// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissedSignal = { item_id: bigint, title: string, url: string | null, source_type: string, relevance_score: number, created_at: string, why_relevant: string, };
