// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identity for a model instance, used as a cross-reference key
 * between provenance rows, calibration curves, and shadow-arena peers.
 *
 * The hash is `sha256(provider + ":" + model + ":" + base_url)`. Two
 * models with the same provider/name served from different base_urls
 * (e.g. Ollama on two different hosts) get distinct identities — which
 * is correct, because they are different runtime entities and may have
 * different calibrations.
 */
export type ModelIdentity = { provider: string, model: string, base_url: string | null, };
