// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamActivity } from "./TeamActivity";

/**
 * Aggregated analytics for an organization over a time period.
 */
export type OrgAnalytics = { 
/**
 * Human-readable period label (e.g. "Last 30 days").
 */
period: string, 
/**
 * Number of seats with activity in the period.
 */
active_seats: number, 
/**
 * Total provisioned seats across all org teams.
 */
total_seats: number, 
/**
 * Total signals detected across all teams.
 */
signals_detected: number, 
/**
 * Signals marked as resolved.
 */
signals_resolved: number, 
/**
 * Decisions tracked across all teams.
 */
decisions_tracked: number, 
/**
 * AI briefings generated across all teams.
 */
briefings_generated: number, 
/**
 * Top signal categories with counts.
 */
top_signal_categories: Array<[string, number]>, 
/**
 * Per-team activity breakdown.
 */
team_activity: Array<TeamActivity>, };
