// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level organization that groups multiple teams.
 */
export type Organization = { id: string, name: string, team_count: number, total_seats: number, created_at: string, };
