// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Organization-level policy configuration (stored as JSON in `organizations.settings`).
 */
export type OrgPolicies = { default_retention_days: { [key in string]?: number }, min_monitoring_interval: bigint | null, require_decision_tracking: boolean, };
