// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a team within an organization.
 */
export type OrgTeamSummary = { team_id: string, member_count: number, last_active: string | null, };
