// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrecedentOutcome } from "./PrecedentOutcome";

export type PrecedentRef = { decision_id: string, statement: string, outcome: PrecedentOutcome | null, 
/**
 * Origin: "user-history" / "curated-corpus" / "public-corpus".
 */
origin: string, 
/**
 * Similarity to the current situation, 0.0–1.0.
 */
similarity: number, };
