// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKind } from "./ArtifactKind";

/**
 * One persisted provenance record. Maps 1:1 to a row in the `provenance`
 * SQL table created by Phase 56 migration.
 *
 * The `id` is `None` before insert and `Some(rowid)` after. Callers
 * typically don't need the id, but shadow-arena code uses it to link
 * shadow-peer rows via `shadow_peer_id`.
 */
export type Provenance = { id: bigint | null, artifact_kind: ArtifactKind, 
/**
 * String representation of the artifact's primary key. For
 * source_items this is the i64 id stringified; for summaries/
 * briefings this is the DB rowid; for synthetic kinds (embed,
 * chat) this may be any stable identifier the caller provides.
 */
artifact_id: string, model_identity_hash: string, provider: string, model: string, 
/**
 * Versioned prompt identifier, e.g. "judge-v1-2026-04-15".
 */
prompt_version: string | null, 
/**
 * Sentinel `PRE_MESH_CALIBRATION_ID` for uncalibrated artifacts.
 */
calibration_id: string | null, 
/**
 * Task performed. Stable short string ("judge", "rerank", etc.).
 */
task: string, temperature: number | null, 
/**
 * Optional audit trail. SHA-256 of the raw model response. Present
 * only when audit_retention_days > 0 in settings (not implemented
 * yet — reserved for future audit feature).
 */
raw_response_hash: string | null, 
/**
 * If this row represents a shadow-arena run, the id of the peer
 * (baseline) provenance row it was compared against. The baseline
 * row itself has shadow_peer_id = None.
 */
shadow_peer_id: bigint | null, 
/**
 * RFC3339 / SQLite `datetime('now')` timestamp. Populated by the
 * DB default when None is passed to `record`.
 */
created_at: string | null, };
