// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RadarMovement } from "./RadarMovement";
import type { RadarQuadrant } from "./RadarQuadrant";
import type { RadarRing } from "./RadarRing";

export type RadarEntry = { name: string, ring: RadarRing, quadrant: RadarQuadrant, movement: RadarMovement, signals: Array<string>, decision_ref: bigint | null, score: number, };
