// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relevance match between an HN item and context
 */
export type RelevanceMatch = { source_file: string, matched_text: string, similarity: number, };
