// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A retention policy for a specific resource type within a team.
 */
export type RetentionPolicy = { resource_type: string, retention_days: number, };
