// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detailed breakdown of score components
 */
export type ScoreBreakdown = { context_score: number, interest_score: number, keyword_score: number, ace_boost: number, affinity_mult: number, anti_penalty: number, freshness_mult: number, feedback_boost: number, source_quality_boost: number, confidence_by_signal: { [key in string]?: number }, 
/**
 * Number of independent signal axes that confirmed relevance (0-5)
 */
signal_count: number, 
/**
 * Names of confirmed signal axes (e.g. ["context", "ace", "dependency"])
 */
confirmed_signals: Array<string>, 
/**
 * Multiplier applied by confirmation gate
 */
confirmation_mult: number, 
/**
 * Dependency match score (0.0-1.0): how strongly content matches user's installed packages
 */
dep_match_score: number, 
/**
 * Package names from user's dependency graph that matched this content
 */
matched_deps: Array<string>, 
/**
 * Domain relevance (0.15 off-domain to 1.0 primary stack match)
 */
domain_relevance: number, 
/**
 * Content quality multiplier (0.5 clickbait to 1.2 authoritative)
 */
content_quality_mult: number, 
/**
 * Novelty multiplier (0.6 introductory to 1.15 release)
 */
novelty_mult: number, 
/**
 * Intent boost from recent work topics (0.0 to 0.15)
 */
intent_boost: number, 
/**
 * Content type classification (e.g. "security_advisory", "show_and_tell")
 */
content_type: string | null, 
/**
 * Content DNA utility multiplier (0.3 hiring to 1.3 security)
 */
content_dna_mult: number, 
/**
 * Competing tech penalty multiplier (0.5 or 1.0)
 */
competing_mult: number, 
/**
 * Stack intelligence: pain point and keyword boost (0.0-0.20)
 */
stack_boost: number, 
/**
 * Stack intelligence: ecosystem shift multiplier (0.95-1.25, default 1.0)
 */
ecosystem_shift_mult: number, 
/**
 * LLM relevance score (1-5 scale, None if LLM skipped)
 */
llm_score: number | null, 
/**
 * LLM's one-sentence explanation
 */
llm_reason: string | null, };
