// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvisorSignal } from "./AdvisorSignal";
import type { DisagreementKind } from "./DisagreementKind";

/**
 * Detailed breakdown of score components
 */
export type ScoreBreakdown = { context_score: number, interest_score: number, keyword_score: number, ace_boost: number, affinity_mult: number, anti_penalty: number, freshness_mult: number, feedback_boost: number, source_quality_boost: number, confidence_by_signal: { [key in string]?: number }, 
/**
 * Number of independent signal axes that confirmed relevance (0-5)
 */
signal_count: number, 
/**
 * Names of confirmed signal axes (e.g. ["context", "ace", "dependency"])
 */
confirmed_signals: Array<string>, 
/**
 * Multiplier applied by confirmation gate
 */
confirmation_mult: number, 
/**
 * Dependency match score (0.0-1.0): how strongly content matches user's installed packages
 */
dep_match_score: number, 
/**
 * Package names from user's dependency graph that matched this content
 */
matched_deps: Array<string>, 
/**
 * Domain relevance (0.15 off-domain to 1.0 primary stack match)
 */
domain_relevance: number, 
/**
 * Content quality multiplier (0.5 clickbait to 1.2 authoritative)
 */
content_quality_mult: number, 
/**
 * Novelty multiplier (0.6 introductory to 1.15 release)
 */
novelty_mult: number, 
/**
 * Intent boost from recent work topics (0.0 to 0.25)
 */
intent_boost: number, 
/**
 * Content type classification (e.g. "security_advisory", "show_and_tell")
 */
content_type: string | null, 
/**
 * Content DNA utility multiplier (0.3 hiring to 1.3 security)
 */
content_dna_mult: number, 
/**
 * Competing tech penalty multiplier (0.5 or 1.0)
 */
competing_mult: number, 
/**
 * Stack intelligence: pain point and keyword boost (0.0-0.20)
 */
stack_boost: number, 
/**
 * Stack intelligence: ecosystem shift multiplier (0.95-1.25, default 1.0)
 */
ecosystem_shift_mult: number, 
/**
 * Stack intelligence: competing tech suppression (0.95 or 1.0)
 */
stack_competing_mult: number, 
/**
 * LLM relevance score (1-5 scale, None if LLM skipped)
 */
llm_score: number | null, 
/**
 * LLM's one-sentence explanation
 */
llm_reason: string | null, 
/**
 * Decision window boost applied (0.0-0.20)
 */
window_boost: number, 
/**
 * ID of matched decision window
 */
matched_window_id: bigint | null, 
/**
 * Skill gap boost from sovereign profile intelligence (0.0-0.20)
 */
skill_gap_boost: number, 
/**
 * Necessity score: "what you'd regret missing" (0.0-1.0)
 */
necessity_score: number, 
/**
 * One-line explanation of why this item is necessary
 */
necessity_reason: string | null, 
/**
 * Necessity category (security_vulnerability, breaking_change, etc.)
 */
necessity_category: string | null, 
/**
 * Necessity urgency (immediate, this_week, awareness, none)
 */
necessity_urgency: string | null, 
/**
 * Signal strength bonus: ceiling adjustment for strong confirmed signals (0.0-0.08).
 * Creates mid-band spread — strong 2-signal items score higher than weak 2-signal items.
 */
signal_strength_bonus: number, 
/**
 * Content analysis multiplier from cached LLM pre-analysis (0.55-1.15, default 1.0).
 * Adjusts score based on technical depth and audience level.
 */
content_analysis_mult: number, 
/**
 * Intelligence Mesh advisory signals (Phase 3+). Each entry is an
 * opinion from an LLM advisor with its own provenance stamp. The
 * deterministic pipeline remains authoritative — advisors CANNOT
 * set the score directly. Reconciliation (Phase 2) bounds the
 * advisor adjustment to ±0.15 and surfaces disagreements as UI
 * signals rather than blending them into the scalar.
 *
 * Empty on the current 50/50-blend code path; populated as mesh
 * phases roll out. See `docs/strategy/INTELLIGENCE-MESH.md` §3.
 */
advisor_signals: Array<AdvisorSignal>, 
/**
 * Phase 2: reconciler disagreement flag. Set when the pipeline and
 * an advisor (or two advisors) produced normalized scores that
 * differed by more than the disagreement threshold (0.30 by default).
 * This item stays in the pipeline-authoritative rank but the UI
 * surfaces it as "judges split" — a killer feature no titan can
 * easily copy because their architecture has one model, not a mesh.
 *
 * `None` means agreement or no advisor opinion was produced.
 */
disagreement: DisagreementKind | null, 
/**
 * Advisory source authority (e.g. "GHSA", "RustSec", "npm_advisory", "OSV")
 */
advisory_source: string | null, 
/**
 * CVSS score (0.0-10.0) from the advisory
 */
cvss_score: number | null, 
/**
 * CVSS severity label ("critical", "high", "medium", "low")
 */
cvss_severity: string | null, 
/**
 * Affected version range from advisory (e.g. "< 3.0.0")
 */
affected_versions: string | null, 
/**
 * Fixed version from advisory (e.g. "3.0.1")
 */
fixed_version: string | null, 
/**
 * User's installed version from lockfile (e.g. "2.8.1")
 */
installed_version: string | null, 
/**
 * Whether installed version falls within the affected range
 */
is_version_affected: boolean | null, 
/**
 * Dependency path description ("direct" | "transitive via X" | "dev-only")
 */
dependency_path: string | null, 
/**
 * How many of the user's scanned projects are affected
 */
affected_project_count: number | null, 
/**
 * Negative stack suppression multiplier (0.15-1.0). Values below 1.0
 * mean the item matched a competing technology or anti-topic. Exposed
 * for debugging — verify the negative stack is actually penalising
 * off-stack content.
 */
negative_stack_prior: number, };
