// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Diff between the two most recent intelligence snapshots.
 * Powers the "what changed since last session" display.
 */
export type SessionDiff = { new_items: bigint, new_relevant: bigint, hours_since_last: number, has_previous: boolean, };
