// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignalSummary = { title: string, source_type: string, signal_type: string, priority: string, url: string | null, };
