// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-source engagement quality for the intelligence pulse.
 */
export type SourceQuality = { source_type: string, items_surfaced: bigint, items_engaged: bigint, engagement_rate: number, };
