// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelevanceMatch } from "./RelevanceMatch";
import type { ScoreBreakdown } from "./ScoreBreakdown";

/**
 * Full relevance result for a source item (HN, arXiv, Reddit, etc.)
 */
export type SourceRelevance = { id: bigint, title: string, url: string | null, top_score: number, matches: Array<RelevanceMatch>, relevant: boolean, 
/**
 * Score from context files (what you're working on)
 */
context_score: number, 
/**
 * Score from explicit interests (what you care about)
 */
interest_score: number, 
/**
 * Whether this item was filtered by an exclusion
 */
excluded: boolean, 
/**
 * The exclusion that blocked this item (if any)
 */
excluded_by: string | null, 
/**
 * Source type (hackernews, arxiv, reddit)
 */
source_type: string, 
/**
 * Human-readable explanation of why this item was surfaced
 */
explanation: string | null, 
/**
 * Overall confidence score (0.0-1.0)
 */
confidence: number | null, 
/**
 * Detailed score breakdown for debugging
 */
score_breakdown: ScoreBreakdown | null, 
/**
 * Signal classification type (security_alert, breaking_change, etc.)
 */
signal_type: string | null, 
/**
 * Signal priority level (critical, high, medium, low)
 */
signal_priority: string | null, 
/**
 * Suggested action based on signal classification
 */
signal_action: string | null, 
/**
 * Keywords that triggered the classification
 */
signal_triggers: Array<string> | null, 
/**
 * Signal time horizon (tactical = act now, strategic = plan ahead)
 */
signal_horizon: string | null, 
/**
 * How many similar items were grouped under this representative (topic dedup)
 */
similar_count: number, 
/**
 * Titles of grouped similar items
 */
similar_titles: Array<string>, 
/**
 * Whether this item was injected by the serendipity engine (anti-bubble)
 */
serendipity: boolean, 
/**
 * STREETS revenue engine match (e.g. "Engine 1: Digital Products")
 */
streets_engine: string | null, 
/**
 * Decision window that boosted this item (subject of matched window)
 */
decision_window_match: string | null, 
/**
 * How much boost was applied from the decision window
 */
decision_boost_applied: number, 
/**
 * When this item was first seen (ISO timestamp for age display)
 */
created_at: string | null, };
