// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaleTopic = { topic: string, last_engagement_days: number, active_deps_in_topic: number, missed_signal_count: number, };
