// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Activity metrics for a single team within the analytics period.
 */
export type TeamActivity = { team_id: string, active_members: number, signals_this_period: number, decisions_this_period: number, 
/**
 * Engagement score: 0.0 (dormant) to 1.0 (highly active).
 */
engagement_score: number, };
