// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A persisted triage record for a security alert.
 */
export type TriageRecord = { item_id: bigint, advisory_id: string | null, action: string, reason: string | null, resolved_at: string, expires_at: string | null, };
