// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UncoveredDep = { name: string, 
/**
 * npm, cargo, pip, etc.
 */
dep_type: string, projects_using: Array<string>, days_since_last_signal: number, 
/**
 * Signals that exist but the user didn't see
 */
available_signal_count: number, 
/**
 * critical, high, medium, low
 */
risk_level: string, };
