// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared urgency scale. Replaces AlertUrgency / GapSeverity / risk_level /
 * priority. Ordered from most to least urgent.
 */
export type Urgency = "critical" | "high" | "medium" | "watch";
