//! Tests for license verification, feature gating, and trial management.
//!
//! Split from settings/license.rs to keep the module under 600 lines.

#[cfg(test)]
mod tests {
    use super::super::license::*;
    use super::super::LicenseConfig;

    /// Verify a real license key generated by Node.js activate.js
    /// This proves the Ed25519 cross-platform compatibility.
    #[test]
    fn verify_js_generated_license() {
        let key = "4DA-eyJ0aWVyIjoiY29tbXVuaXR5IiwiZW1haWwiOiJlMmUtdGVzdC0xNzcxNzQ4NDI0MTY1QDRkYS50ZXN0IiwiZXhwaXJlc19hdCI6IjIwMjctMDItMjJUMDg6MjA6MjQuNzM5WiIsImlzc3VlZF9hdCI6IjIwMjYtMDItMjJUMDg6MjA6MjQuNzM5WiIsImZlYXR1cmVzIjpbInN0cmVldHNfY29tbXVuaXR5Il19.1T/4tSaET1tC1z/fuEEGwecSqBd8fIrplHdFxnUW9J0ZIOfWRmKhnJvTIt1i+Q7U3+OkrLBpwl4f8hngo0t6Bg==";
        let result = verify_license_key(key);
        assert!(result.is_ok(), "Verification failed: {:?}", result.err());
        let payload = result.unwrap();
        assert_eq!(payload.tier, "community");
        assert_eq!(payload.email, "e2e-test-1771748424165@4da.test");
        assert!(payload.features.contains(&"streets_community".to_string()));
    }

    #[test]
    fn reject_invalid_key() {
        assert!(verify_license_key("").is_err());
        assert!(verify_license_key("INVALID-key").is_err());
        assert!(verify_license_key("4DA-bad.bad").is_err());
    }

    #[test]
    fn reject_too_long_key() {
        let long = format!("4DA-{}.{}", "A".repeat(600), "B".repeat(600));
        let result = verify_license_key(&long);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("too long"));
    }

    #[test]
    fn trial_lifecycle() {
        // Not started
        let license = LicenseConfig {
            tier: "free".to_string(),
            license_key: String::new(),
            activated_at: None,
            trial_started_at: None,
        };
        assert!(!is_trial_active(&license));
        let status = get_trial_status(&license);
        assert!(!status.active);
        assert_eq!(status.days_remaining, 0);

        // Active trial
        let license = LicenseConfig {
            trial_started_at: Some(chrono::Utc::now().to_rfc3339()),
            ..license
        };
        assert!(is_trial_active(&license));
        let status = get_trial_status(&license);
        assert!(status.active);
        assert!(status.days_remaining >= 29);

        // Expired trial
        let expired = chrono::Utc::now() - chrono::Duration::days(31);
        let license = LicenseConfig {
            trial_started_at: Some(expired.to_rfc3339()),
            ..license
        };
        assert!(!is_trial_active(&license));
        let status = get_trial_status(&license);
        assert!(!status.active);
        assert_eq!(status.days_remaining, 0);
    }

    #[test]
    fn feature_gating() {
        let free = LicenseConfig {
            tier: "free".to_string(),
            license_key: String::new(),
            activated_at: None,
            trial_started_at: None,
        };
        assert!(!is_pro_feature_available("generate_ai_briefing", &free));
        assert!(is_pro_feature_available("some_free_feature", &free));

        let pro = LicenseConfig {
            tier: "pro".to_string(),
            ..free.clone()
        };
        assert!(is_pro_feature_available("generate_ai_briefing", &pro));
    }
}
