//! Tests for license verification, feature gating, and trial management.
//!
//! Split from settings/license.rs to keep the module under 600 lines.

#[cfg(test)]
mod tests {
    use super::super::license::*;
    use super::super::LicenseConfig;

    /// Verify a real license key generated by Node.js activate.js
    /// This proves the Ed25519 cross-platform compatibility.
    #[test]
    fn verify_js_generated_license() {
        let key = "4DA-eyJ0aWVyIjoiY29tbXVuaXR5IiwiZW1haWwiOiJlMmUtdGVzdC0xNzcxNzQ4NDI0MTY1QDRkYS50ZXN0IiwiZXhwaXJlc19hdCI6IjIwMjctMDItMjJUMDg6MjA6MjQuNzM5WiIsImlzc3VlZF9hdCI6IjIwMjYtMDItMjJUMDg6MjA6MjQuNzM5WiIsImZlYXR1cmVzIjpbInN0cmVldHNfY29tbXVuaXR5Il19.1T/4tSaET1tC1z/fuEEGwecSqBd8fIrplHdFxnUW9J0ZIOfWRmKhnJvTIt1i+Q7U3+OkrLBpwl4f8hngo0t6Bg==";
        let result = verify_license_key(key);
        assert!(result.is_ok(), "Verification failed: {:?}", result.err());
        let payload = result.unwrap();
        assert_eq!(payload.tier, "community");
        assert_eq!(payload.email, "e2e-test-1771748424165@4da.test");
        assert!(payload.features.contains(&"streets_community".to_string()));
    }

    #[test]
    fn reject_invalid_key() {
        assert!(verify_license_key("").is_err());
        assert!(verify_license_key("INVALID-key").is_err());
        assert!(verify_license_key("4DA-bad.bad").is_err());
    }

    #[test]
    fn reject_too_long_key() {
        let long = format!("4DA-{}.{}", "A".repeat(600), "B".repeat(600));
        let result = verify_license_key(&long);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("too long"));
    }

    #[test]
    fn trial_lifecycle() {
        // Not started
        let license = LicenseConfig {
            tier: "free".to_string(),
            license_key: String::new(),
            activated_at: None,
            trial_started_at: None,
        };
        assert!(!is_trial_active(&license));
        let status = get_trial_status(&license);
        assert!(!status.active);
        assert_eq!(status.days_remaining, 0);

        // Active trial
        let license = LicenseConfig {
            tier: license.tier.clone(),
            license_key: license.license_key.clone(),
            activated_at: license.activated_at.clone(),
            trial_started_at: Some(chrono::Utc::now().to_rfc3339()),
        };
        assert!(is_trial_active(&license));
        let status = get_trial_status(&license);
        assert!(status.active);
        assert!(status.days_remaining >= 13);

        // Expired trial (must exceed TRIAL_DURATION_DAYS which is 14)
        let expired = chrono::Utc::now() - chrono::Duration::days(15);
        let license = LicenseConfig {
            tier: license.tier.clone(),
            license_key: license.license_key.clone(),
            activated_at: license.activated_at.clone(),
            trial_started_at: Some(expired.to_rfc3339()),
        };
        assert!(!is_trial_active(&license));
        let status = get_trial_status(&license);
        assert!(!status.active);
        assert_eq!(status.days_remaining, 0);
    }

    #[test]
    fn feature_gating() {
        let free = LicenseConfig {
            tier: "free".to_string(),
            license_key: String::new(),
            activated_at: None,
            trial_started_at: None,
        };
        // Signal-gated features should be blocked for free users
        assert!(!is_signal_feature_available("get_attention_report", &free));
        assert!(is_signal_feature_available("some_free_feature", &free));

        let signal = LicenseConfig {
            tier: "signal".to_string(),
            license_key: free.license_key.clone(),
            activated_at: free.activated_at.clone(),
            trial_started_at: free.trial_started_at.clone(),
        };
        assert!(is_signal_feature_available("get_attention_report", &signal));

        // Legacy "pro" tier should still work
        let legacy_pro = LicenseConfig {
            tier: "pro".to_string(),
            license_key: free.license_key.clone(),
            activated_at: free.activated_at.clone(),
            trial_started_at: free.trial_started_at.clone(),
        };
        assert!(is_signal_feature_available(
            "get_attention_report",
            &legacy_pro
        ));
    }

    #[test]
    fn briefing_features_available_to_free_users() {
        let free = LicenseConfig {
            tier: "free".to_string(),
            license_key: String::new(),
            activated_at: None,
            trial_started_at: None,
        };
        // Briefing features use BYOK model — available to all users
        assert!(is_signal_feature_available("generate_ai_briefing", &free));
        assert!(is_signal_feature_available("get_latest_briefing", &free));
        assert!(is_signal_feature_available("generate_weekly_digest", &free));
    }

    /// Verify LicenseConfig survives a JSON serialization roundtrip.
    /// This is the persistence path used by settings.json on disk.
    #[test]
    fn license_config_roundtrip() {
        let activated = chrono::Utc::now().to_rfc3339();
        let original = LicenseConfig {
            tier: "pro".to_string(),
            license_key: "4DA-test-key-abc123".to_string(),
            activated_at: Some(activated.clone()),
            trial_started_at: None,
        };

        let json = serde_json::to_string(&original).expect("serialize LicenseConfig");
        let restored: LicenseConfig =
            serde_json::from_str(&json).expect("deserialize LicenseConfig");

        assert_eq!(restored.tier, "pro");
        assert_eq!(restored.license_key, "4DA-test-key-abc123");
        assert_eq!(restored.activated_at, Some(activated));
        assert_eq!(restored.trial_started_at, None);
    }

    /// Verify the full Settings struct survives a JSON roundtrip.
    /// Guards against serde regressions that could lose user configuration.
    #[test]
    fn settings_json_roundtrip() {
        use super::super::Settings;

        let mut original = Settings::default();
        // Set non-default values across key subsystems
        original.llm.provider = "anthropic".to_string();
        original.llm.api_key = "sk-test-key".to_string();
        original.llm.model = "claude-haiku-4-5-20251001".to_string();
        original.embedding_threshold = 0.42;
        original.monitoring.enabled = false;
        original.monitoring.interval_minutes = 30;
        original.license.tier = "pro".to_string();
        original.license.license_key = "4DA-roundtrip-key".to_string();
        original.license.activated_at = Some("2026-01-15T00:00:00Z".to_string());
        original.rss_feeds = vec!["https://example.com/feed.xml".to_string()];
        original.context_dirs = vec!["/home/dev/project".to_string()];
        original.onboarding_complete = true;
        original.locale.country = "AU".to_string();
        original.locale.language = "en".to_string();
        original.locale.currency = "AUD".to_string();

        let json = serde_json::to_string_pretty(&original).expect("serialize Settings");
        let restored: Settings = serde_json::from_str(&json).expect("deserialize Settings");

        // LLM provider
        assert_eq!(restored.llm.provider, "anthropic");
        assert_eq!(restored.llm.api_key, "sk-test-key");
        assert_eq!(restored.llm.model, "claude-haiku-4-5-20251001");

        // Scoring threshold
        assert!((restored.embedding_threshold - 0.42).abs() < f32::EPSILON);

        // Monitoring
        assert!(!restored.monitoring.enabled);
        assert_eq!(restored.monitoring.interval_minutes, 30);

        // License
        assert_eq!(restored.license.tier, "pro");
        assert_eq!(restored.license.license_key, "4DA-roundtrip-key");
        assert_eq!(
            restored.license.activated_at,
            Some("2026-01-15T00:00:00Z".to_string())
        );

        // Content sources
        assert_eq!(restored.rss_feeds, vec!["https://example.com/feed.xml"]);
        assert_eq!(restored.context_dirs, vec!["/home/dev/project"]);

        // Flags
        assert!(restored.onboarding_complete);

        // Locale
        assert_eq!(restored.locale.country, "AU");
        assert_eq!(restored.locale.language, "en");
        assert_eq!(restored.locale.currency, "AUD");
    }
}
