// SPDX-License-Identifier: FSL-1.1-Apache-2.0
import { useState, useEffect, useCallback } from 'react';
import type { UnlistenFn } from '@tauri-apps/api/event';
import { listen } from '@tauri-apps/api/event';

import type { SourceRelevance, AnalysisProgress } from '../types';
import { useAppStore } from '../store';
import type { NarrationEvent } from './analysis-utils';
import {
  handleAnalysisProgress,
  handleAnalysisComplete,
  handleAnalysisError,
  handleSourceError,
  handleNetworkOffline,
  handleEmbeddingMode,
  handleStartAnalysisFromTray,
  handleNavigateToSignals,
  createBackgroundResultsHandler,
  handleBriefingAutoGenerated,
  handleMorningBriefingReady,
  handleMorningBriefingSynthesis,
  handleAnomalyDetected,
  handleDigestGenerated,
  handlePartialResults,
  handleStacksAutoDetected,
  handleCalibrationDrift,
  createNarrationHandler,
} from './analysis-event-handlers';
import type { MorningBriefingReadyPayload } from './analysis-event-handlers';
export type { NarrationEvent } from './analysis-utils';

/**
 * Analysis hook — thin wrapper around Zustand store.
 * Sets up Tauri event listeners that write directly to the store.
 * All state lives in the store; this hook adds no local state.
 */
export function useAnalysis(
  _addToast?: (type: 'success' | 'error' | 'warning' | 'info', message: string) => void,
  onBackgroundItems?: (itemIds: number[]) => void,
) {
  const state = useAppStore(s => s.appState);
  const expandedItem = useAppStore(s => s.expandedItem);
  const isBrowserMode = useAppStore(s => s.isBrowserMode);
  const setExpandedItem = useAppStore(s => s.setExpandedItem);
  const startAnalysis = useAppStore(s => s.startAnalysis);
  const loadContextFiles = useAppStore(s => s.loadContextFiles);
  const clearContext = useAppStore(s => s.clearContext);
  const indexContext = useAppStore(s => s.indexContext);

  // Live analysis narration events
  const [narrationEvents, setNarrationEvents] = useState<NarrationEvent[]>([]);

  const clearNarrationEvents = useCallback(() => {
    setNarrationEvents([]);
  }, []);

  // Set up event listeners for background analysis — all write to store
  useEffect(() => {
    let unlistens: UnlistenFn[] = [];

    const setupListeners = async () => {
      const results = await Promise.all([
        listen<AnalysisProgress>('analysis-progress', handleAnalysisProgress),
        listen<SourceRelevance[]>('analysis-complete', handleAnalysisComplete),
        listen<string>('analysis-error', handleAnalysisError),
        listen<{ source: string; error: string; retry_count: number }>('source-error', handleSourceError),
        listen('network-offline', handleNetworkOffline),
        listen<{ mode: string; reason?: string }>('embedding-mode', handleEmbeddingMode),
        listen('start-analysis-from-tray', handleStartAnalysisFromTray),
        listen<{ item_id?: number }>('navigate-to-signals', handleNavigateToSignals),
        listen<SourceRelevance[]>('background-results', createBackgroundResultsHandler(onBackgroundItems)),
        listen<{ briefing: string; model?: string }>('briefing-auto-generated', handleBriefingAutoGenerated),
        listen<MorningBriefingReadyPayload>('morning-briefing-ready', handleMorningBriefingReady),
        listen<{ synthesis: string; clusters?: Array<{ insight: string; evidence_ids: number[]; action: string; confidence: number }> }>('morning-briefing-synthesis', handleMorningBriefingSynthesis),
        listen<{ type: string; severity: string; description: string }>('anomaly-detected', handleAnomalyDetected),
        listen<{ item_count: number }>('digest-generated', handleDigestGenerated),
        listen<SourceRelevance[]>('partial-results', handlePartialResults),
        listen<string[]>('stacks-auto-detected', handleStacksAutoDetected),
        listen<{ task: string; reason: string }>('calibration-drift', handleCalibrationDrift),
        listen<{ narration_type: string; message: string; source: string | null; relevance: number | null }>('analysis-narration', createNarrationHandler(setNarrationEvents)),
      ]);

      unlistens = results;
    };

    void setupListeners();

    return () => {
      for (const unlisten of unlistens) unlisten();
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps -- stable callback ref
  }, []);

  useEffect(() => {
    void loadContextFiles();
  }, [loadContextFiles]);

  // Hydration from backend cache is handled by useAppListeners (use-app-listeners.ts)
  // which also handles the auto-analysis fallback — no duplicate fetch needed here.

  const setStatus = useCallback((status: string) => {
    useAppStore.getState().setAppState({ status });
  }, []);

  // setState wrapper for App.tsx compatibility (accepts updater function)
  const setState = useCallback((updater: ((s: typeof state) => typeof state) | Partial<typeof state>) => {
    if (typeof updater === 'function') {
      useAppStore.getState().setAppStateFull(updater);
    } else {
      useAppStore.getState().setAppState(updater);
    }
  }, []);

  return {
    state,
    setState,
    expandedItem,
    setExpandedItem,
    isBrowserMode,
    loadContextFiles,
    clearContext,
    indexContext,
    startAnalysis,
    setStatus,
    narrationEvents,
    clearNarrationEvents,
  };
}
