// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Topic enrichment — maps bare topic names to disambiguating descriptions for embedding quality.

/// Enrich a bare topic/tech name with a descriptive sentence for higher-quality embeddings.
///
/// Bare names like "Rust" or "Go" are ambiguous — "Rust" could mean the game, the chemical
/// process, or the programming language. This function maps known developer topics to concise
/// technical descriptions (15-30 words) that disambiguate meaning for the embedding model.
///
/// Unknown topics get a generic but still-helpful fallback description.
pub(crate) fn enrich_topic_for_embedding(topic: &str) -> String {
    // Case-insensitive lookup: normalize to lowercase for matching
    let key = topic.to_lowercase();

    // Curated descriptions — each one disambiguates the topic in a software-dev context.
    // Sorted alphabetically for maintainability. ~100 entries, all &str — zero heap alloc on match.
    let description: Option<&str> = match key.as_str() {
        "actix" => Some("Actix Web — high-performance Rust web framework built on the actor model with async support"),
        "angular" => Some("Angular — TypeScript-based frontend framework by Google for building structured single-page applications"),
        "ansible" => Some("Ansible — agentless IT automation tool for configuration management, application deployment, and orchestration"),
        "anthropic" => Some("Anthropic — AI safety company developing the Claude family of large language models"),
        "apache" => Some("Apache HTTP Server — widely deployed open-source web server for serving static and dynamic content"),
        "aws" => Some("Amazon Web Services — cloud computing platform offering compute, storage, database, and AI services"),
        "axum" => Some("Axum — ergonomic Rust web framework built on Tokio and Tower for building async HTTP services"),
        "azure" => Some("Microsoft Azure — cloud computing platform for building, deploying, and managing applications and services"),
        "bun" => Some("Bun — fast all-in-one JavaScript runtime, bundler, transpiler, and package manager written in Zig"),
        "c#" => Some("C# — statically typed object-oriented language by Microsoft for .NET platform, game dev, and enterprise software"),
        "c++" => Some("C++ — high-performance compiled language for systems programming, game engines, and performance-critical software"),
        "caddy" => Some("Caddy — modern web server with automatic HTTPS, HTTP/2, and simple configuration via Caddyfile"),
        "cargo" => Some("Cargo — Rust's package manager and build system for managing dependencies, compiling, and publishing crates"),
        "cuda" => Some("CUDA — NVIDIA's parallel computing platform and API for GPU-accelerated computing and deep learning"),
        "cypress" => Some("Cypress — JavaScript end-to-end testing framework for web applications with real browser execution"),
        "deno" => Some("Deno — secure JavaScript and TypeScript runtime by Ryan Dahl with built-in tooling and web-standard APIs"),
        "diesel" => Some("Diesel — safe, extensible Rust ORM and query builder with compile-time query validation"),
        "directx" => Some("DirectX — Microsoft's collection of APIs for multimedia and game programming on Windows platforms"),
        "django" => Some("Django — batteries-included Python web framework with ORM, admin panel, and security best practices"),
        "docker" => Some("Docker — container platform for packaging applications with dependencies into portable, isolated environments"),
        "dynamodb" => Some("DynamoDB — AWS fully managed NoSQL key-value database designed for high-throughput low-latency workloads"),
        "elasticsearch" => Some("Elasticsearch — distributed search and analytics engine for full-text search, log analysis, and observability"),
        "elixir" => Some("Elixir — functional language on the Erlang VM for scalable fault-tolerant distributed systems"),
        "eslint" => Some("ESLint — pluggable JavaScript and TypeScript linter for finding and fixing code quality issues"),
        "express" => Some("Express — minimal Node.js web framework for building RESTful APIs and server-side applications"),
        "fastapi" => Some("FastAPI — modern high-performance Python web framework for building APIs with automatic OpenAPI documentation"),
        "fastembed" => Some("FastEmbed — lightweight library for generating text embeddings locally using ONNX Runtime models"),
        "flask" => Some("Flask — lightweight Python web micro-framework for building APIs and web applications with minimal boilerplate"),
        "gcp" => Some("Google Cloud Platform — cloud computing services for compute, storage, machine learning, and data analytics"),
        "git" => Some("Git — distributed version control system for tracking source code changes and collaborative development"),
        "github" => Some("GitHub — cloud platform for Git repository hosting, code review, CI/CD, and open-source collaboration"),
        "go" => Some("Go — statically typed compiled language by Google designed for concurrency, simplicity, and cloud-native services"),
        "grafana" => Some("Grafana — open-source observability platform for visualizing metrics, logs, and traces from multiple data sources"),
        "graphql" => Some("GraphQL — query language and runtime for APIs allowing clients to request exactly the data they need"),
        "grpc" => Some("gRPC — high-performance RPC framework using Protocol Buffers for efficient service-to-service communication"),
        "haskell" => Some("Haskell — purely functional programming language with strong static typing and lazy evaluation for robust software"),
        "hugging face" => Some("Hugging Face — AI platform and hub for sharing pretrained machine learning models, datasets, and transformers"),
        "hyper" => Some("Hyper — fast and correct HTTP implementation in Rust, used as the foundation for many Rust web frameworks"),
        "java" => Some("Java — object-oriented language on the JVM for enterprise applications, Android development, and large-scale systems"),
        "jest" => Some("Jest — JavaScript testing framework by Meta with snapshot testing, mocking, and zero-configuration setup"),
        "kafka" => Some("Apache Kafka — distributed event streaming platform for high-throughput real-time data pipelines and messaging"),
        "kotlin" => Some("Kotlin — modern JVM language by JetBrains for Android development and server-side applications with null safety"),
        "kubernetes" => Some("Kubernetes — container orchestration system for automating deployment, scaling, and management of containerized applications"),
        "langchain" => Some("LangChain — framework for building applications powered by large language models with chains, agents, and retrieval"),
        "laravel" => Some("Laravel — PHP web framework with elegant syntax, ORM, queue system, and comprehensive ecosystem for web applications"),
        "linux" => Some("Linux — open-source Unix-like operating system kernel powering servers, containers, embedded systems, and cloud infrastructure"),
        "llamaindex" => Some("LlamaIndex — data framework for connecting large language models with external data sources via retrieval-augmented generation"),
        "metal" => Some("Metal — Apple's low-level GPU programming API for high-performance graphics and compute on macOS and iOS"),
        "mongodb" => Some("MongoDB — document-oriented NoSQL database storing data as flexible JSON-like documents for modern applications"),
        "mysql" => Some("MySQL — open-source relational database management system widely used for web applications and data storage"),
        "nats" => Some("NATS — lightweight high-performance messaging system for cloud-native distributed systems and microservices"),
        "next.js" => Some("Next.js — React framework by Vercel for server-side rendering, static generation, and full-stack web applications"),
        "nginx" => Some("Nginx — high-performance HTTP server and reverse proxy for load balancing, caching, and serving web content"),
        "node.js" => Some("Node.js — JavaScript runtime built on V8 for building scalable server-side and networking applications"),
        "npm" => Some("npm — JavaScript package manager and registry for sharing and installing reusable code modules"),
        "numpy" => Some("NumPy — foundational Python library for numerical computing with support for large multi-dimensional arrays and matrices"),
        "ollama" => Some("Ollama — tool for running large language models locally on consumer hardware with a simple API interface"),
        "onnx" => Some("ONNX — open standard format for representing machine learning models enabling interoperability between frameworks"),
        "openai" => Some("OpenAI — AI research company developing the GPT family of large language models and the ChatGPT platform"),
        "opengl" => Some("OpenGL — cross-platform graphics API for rendering 2D and 3D vector graphics in interactive applications"),
        "pandas" => Some("pandas — Python data analysis library providing DataFrames for manipulating structured and tabular data"),
        "php" => Some("PHP — server-side scripting language widely used for web development, powering WordPress and many web applications"),
        "pip" => Some("pip — Python package installer for downloading and managing libraries from the Python Package Index"),
        "playwright" => Some("Playwright — cross-browser end-to-end testing framework by Microsoft for reliable web application testing"),
        "postgresql" => Some("PostgreSQL — advanced open-source relational database with extensibility, JSONB support, and ACID compliance"),
        "prettier" => Some("Prettier — opinionated code formatter supporting JavaScript, TypeScript, CSS, and other web languages"),
        "prometheus" => Some("Prometheus — open-source monitoring system with time-series database for alerting and metrics collection"),
        "python" => Some("Python — high-level interpreted language for web development, data science, machine learning, and automation scripting"),
        "pytorch" => Some("PyTorch — open-source deep learning framework by Meta for building and training neural networks with dynamic computation graphs"),
        "rabbitmq" => Some("RabbitMQ — open-source message broker implementing AMQP for reliable asynchronous communication between services"),
        "rails" => Some("Ruby on Rails — convention-over-configuration web framework for building database-backed web applications in Ruby"),
        "react" => Some("React — JavaScript UI library by Meta for building component-based interactive user interfaces with a virtual DOM"),
        "redis" => Some("Redis — in-memory data structure store used as a cache, message broker, and real-time database"),
        "rest" => Some("REST — architectural style for designing networked applications using stateless HTTP methods and resource URLs"),
        "rocm" => Some("ROCm — AMD's open-source GPU computing platform for machine learning and high-performance computing workloads"),
        "ruby" => Some("Ruby — dynamic interpreted language focused on developer happiness, known for elegant syntax and metaprogramming"),
        "rust" => Some("Rust — systems programming language focused on memory safety, concurrency, and performance without garbage collection"),
        "scala" => Some("Scala — JVM language combining object-oriented and functional programming for scalable concurrent applications"),
        "scikit-learn" => Some("scikit-learn — Python machine learning library providing classification, regression, clustering, and preprocessing algorithms"),
        "seaorm" => Some("SeaORM — async and dynamic Rust ORM built on SQLx for database-agnostic application development"),
        "selenium" => Some("Selenium — browser automation framework for web application testing across multiple browsers and platforms"),
        "serde" => Some("Serde — Rust serialization framework for converting data structures to and from JSON, TOML, and other formats"),
        "spring" => Some("Spring — comprehensive Java framework for enterprise application development with dependency injection and microservices"),
        "sqlite" => Some("SQLite — self-contained embedded relational database engine used for local storage in applications and mobile devices"),
        "sqlx" => Some("SQLx — async Rust SQL toolkit with compile-time checked queries and support for PostgreSQL, MySQL, and SQLite"),
        "svelte" => Some("Svelte — compiler-based frontend framework that shifts work to build time for minimal runtime JavaScript"),
        "swift" => Some("Swift — Apple's compiled language for iOS, macOS, watchOS, and server-side development with safety and performance"),
        "tauri" => Some("Tauri — lightweight framework for building desktop applications with web frontends and Rust backends"),
        "tensorflow" => Some("TensorFlow — open-source machine learning platform by Google for building and deploying neural network models at scale"),
        "terraform" => Some("Terraform — infrastructure-as-code tool by HashiCorp for provisioning and managing cloud resources declaratively"),
        "tokio" => Some("Tokio — asynchronous runtime for Rust providing event-driven non-blocking I/O for building network applications"),
        "typescript" => Some("TypeScript — typed superset of JavaScript by Microsoft that compiles to plain JavaScript for safer large-scale development"),
        "vite" => Some("Vite — fast frontend build tool with instant hot module replacement and native ES module dev server"),
        "vitest" => Some("Vitest — fast Vite-native unit testing framework for JavaScript and TypeScript with Jest-compatible API"),
        "vue" => Some("Vue.js — progressive JavaScript framework for building user interfaces with reactive data binding and component composition"),
        "vulkan" => Some("Vulkan — low-overhead cross-platform graphics and compute API for high-performance GPU-accelerated applications"),
        "wasm" | "webassembly" => Some("WebAssembly — portable binary instruction format for executing high-performance code in web browsers and runtimes"),
        "webpack" => Some("Webpack — JavaScript module bundler for transforming, bundling, and packaging web application assets"),
        "websocket" => Some("WebSocket — communication protocol providing full-duplex bidirectional channels over a single TCP connection"),
        _ => None,
    };

    match description {
        Some(desc) => desc.to_string(),
        None => format!("{topic} — software development technology"),
    }
}
