// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single piece of evidence backing a preemption alert.
 */
export type AlertEvidence = { source: string, title: string, url: string | null, freshness_days: number, relevance_score: number, };
