// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alert policy for a team (admin-configurable).
 */
export type AlertPolicy = { team_id: string, min_seats_to_alert: number, aggregation_window_minutes: number, notification_channels: Array<string>, };
