// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How urgently the user should act on this alert.
 */
export type AlertUrgency = "critical" | "high" | "medium" | "watch";
