// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaMetrics } from "./PersonaMetrics";
import type { Recommendation } from "./Recommendation";
import type { RigRequirements } from "./RigRequirements";

export type CalibrationResult = { grade: string, grade_score: number, aggregate_f1: number, aggregate_precision: number, aggregate_recall: number, mean_separation_gap: number, corpus_items: number, personas_tested: number, per_persona: Array<PersonaMetrics>, worst_persona: string, best_persona: string, rig_requirements: RigRequirements, recommendations: Array<Recommendation>, infrastructure_score: number, context_richness_score: number, signal_coverage_score: number, discrimination_score: number, active_signal_axes: Array<string>, nearest_persona: string, };
