// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The runtime state of a single capability.
 */
export type CapabilityState = { "state": "full" } | { "state": "degraded", 
/**
 * Why the capability degraded (e.g. "Ollama not reachable").
 */
reason: string, 
/**
 * ISO-8601 timestamp of when the degradation was first reported.
 */
since: string, 
/**
 * Description of the fallback behavior in use.
 */
fallback: string, } | { "state": "unavailable", 
/**
 * Why the capability is unavailable.
 */
reason: string, 
/**
 * User-actionable remediation step.
 */
remediation: string, };
