// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate counts of capability states — used by the frontend status bar.
 */
export type CapabilitySummary = { full: number, degraded: number, unavailable: number, total: number, };
