// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every discrete subsystem that can independently degrade.
 */
export type Capability = "embedding_search" | "llm_reranking" | "briefing_generation" | "source_fetching" | "ace_context" | "system_tray" | "notifications" | "credential_storage" | "vector_search";
