// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness indicator for UI display.
 */
export type ChannelFreshness = "fresh" | "stale" | "never_rendered";
