// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Changelog between two render versions.
 */
export type ChannelChangelog = { channel_id: bigint, from_version: bigint, to_version: bigint, summary: string, added_lines: Array<string>, removed_lines: Array<string>, changed_at: string, };
