// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelFreshness } from "./ChannelFreshness";

/**
 * Lightweight summary for list views (cheaper to transfer than full Channel).
 */
export type ChannelSummary = { id: bigint, slug: string, title: string, description: string, source_count: bigint, render_count: bigint, freshness: ChannelFreshness, last_rendered_at: string | null, };
