// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rendered snapshot of channel content — immutable once saved.
 */
export type ChannelRender = { id: bigint, channel_id: bigint, version: bigint, content_markdown: string, content_hash: string, source_item_ids: Array<bigint>, model: string | null, tokens_used: bigint | null, latency_ms: bigint | null, rendered_at: string, };
