// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelStatus } from "./ChannelStatus";

/**
 * Full channel record as stored in the database.
 */
export type Channel = { id: bigint, slug: string, title: string, description: string, topic_query: Array<string>, status: ChannelStatus, source_count: bigint, render_count: bigint, last_rendered_at: string | null, created_at: string, updated_at: string, };
