// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source item matched to a channel via topic relevance.
 */
export type ChannelSourceMatch = { channel_id: bigint, source_item_id: bigint, title: string, url: string | null, source_type: string, match_score: number, matched_at: string, };
