// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A color with its weight in the palette
 */
export type ColorWeight = { 
/**
 * Hex color code (e.g., "#D4AF37")
 */
hex: string, 
/**
 * Weight in the palette (0.0-1.0)
 */
weight: number, };
