// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact summary of a calibration curve, suitable for rendering in the
 * advisor receipts panel. `None` from `get_calibration_curve_status` means
 * "no curve on disk for this (model, task)" — UI should show the
 * "pre-mesh" tag. Drift is handled separately via the `calibration-drift`
 * event; once a curve drifts, `get_calibration_curve_status` will still
 * return its metadata (so the UI can show "fit 3 days ago, now stale —
 * recalibrating"), but the mesh has already invalidated it at read time.
 */
export type CurveStatus = { curve_id: string, task: string, prompt_version: string, brier_score: number, ece: number, sample_count: number, 
/**
 * RFC3339 timestamp of fit.
 */
created_at: string, 
/**
 * Rounded days since the fit. The UI renders this as "3d ago".
 */
age_days: number, 
/**
 * True when the curve on disk was fit against a different
 * prompt_version than the current advisor uses. The apply layer
 * has invalidated it; receipts should show "stale, refitting".
 */
is_stale: boolean, };
