// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry per (model_identity, task) pair that was considered for a
 * fit. Returned by `fit_calibration_curves_now` as a summary so the UI
 * can render a "last fit" table ("llama3.2 / judge: 142 samples → fit,
 * Brier 0.14" or "qwen / judge: 8 samples → skipped, need 50").
 */
export type CurveFitSummary = { model_identity_hash: string, provider: string, model: string, task: string, samples_scanned: number, samples_labeled: number, curve_saved: boolean, curve_id: string | null, brier_score: number | null, ece: number | null, skipped_reason: string | null, };
