// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Diagnostic describing why a curve was rejected at load time.
 *
 * Today only prompt-version drift is detected (model identity
 * divergence shows up as a different filename and produces `Missing`
 * via the underlying `load_curve`, which has no drift signal to
 * report). Expanding the enum for new drift kinds (temperature,
 * calibration-id mismatch, etc.) should be additive.
 */
export type CurveDrift = { curve_id: string, task: string, model_identity_hash: string, stored_prompt_version: string, current_prompt_version: string, 
/**
 * Stable reason code the UI can switch on for localized copy.
 * "prompt_version_mismatch" is the only variant today.
 */
reason: string, };
