// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionVote } from "./DecisionVote";

/**
 * Detailed view of a team decision including all votes.
 */
export type DecisionDetail = { id: string, team_id: string, title: string, decision_type: string, rationale: string, proposed_by: string, status: string, created_at: string, resolved_at: string | null, votes: Array<DecisionVote>, };
