// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single vote on a team decision.
 */
export type DecisionVote = { voter_id: string, stance: string, rationale: string, voted_at: string, };
