// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DomainPrecision = { domain: string, precision: number, total_surfaced: number, acted_on: number, false_positives: number, };
