// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Manifest describing a completed data export.
 */
export type ExportManifest = { export_id: string, created_at: string, format: string, sections: Array<string>, total_records: number, };
