// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report from a pack extraction run
 */
export type ExtractionReport = { total: number, succeeded: number, failed: number, skipped: number, };
