// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extraction pipeline status
 */
export type ExtractionStatus = "pending" | "processing" | "done" | "failed";
