// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceFpRate } from "./SourceFpRate";
import type { TopicFpRate } from "./TopicFpRate";

export type FalsePositiveAnalysis = { total_fp: number, by_source: Array<SourceFpRate>, by_topic: Array<TopicFpRate>, recommendations: Array<string>, };
