// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generation outcome for feedback loop
 */
export type GenerationOutcome = "kept" | "rejected" | "modified" | "unknown";
