// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackConcept } from "./PackConcept";

export type IntelligencePack = { id: string, name: string, description: string, icon: string, concepts: Array<PackConcept>, default_watches: Array<string>, active: boolean, activated_at: string | null, };
