// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackBucket } from "./FeedbackBucket";
import type { TierMetrics } from "./TierMetrics";

export type IntelligenceMetrics = { verified: TierMetrics, ai_assessed: TierMetrics, developing: TierMetrics, feedback_distribution: Array<FeedbackBucket>, prompt_versions_active: Array<string>, };
