// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single member's detection of a shared signal.
 */
export type MemberDetection = { client_id: string, display_name: string, detected_at: string, };
