// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Motion/temporal characteristics extracted from video content
 */
export type MotionProfile = { 
/**
 * Average cuts per minute
 */
cuts_per_minute: number, 
/**
 * Median shot duration in seconds
 */
shot_duration_median: number, 
/**
 * Energy arc description
 */
energy_arc: string | null, 
/**
 * Hard cut ratio (0.0-1.0)
 */
hard_cut_ratio: number, 
/**
 * Dissolve ratio (0.0-1.0)
 */
dissolve_ratio: number, 
/**
 * Camera movement intensity: 0.0 (static) to 1.0 (dynamic)
 */
movement_intensity: number, 
/**
 * Camera stability: 0.0 (handheld) to 1.0 (locked)
 */
stability: number, };
