// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of adding sources to a pack
 */
export type MuseAddResult = { added: number, skipped: number, total: number, };
