// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionStatus } from "./ExtractionStatus";
import type { MuseMediaType } from "./MuseMediaType";

/**
 * A source file contributing to a MUSE pack
 */
export type MusePackSource = { 
/**
 * Unique ID
 */
id: bigint, 
/**
 * Pack this source belongs to
 */
pack_id: string, 
/**
 * Path to the source file
 */
file_path: string, 
/**
 * Media type category
 */
file_type: MuseMediaType, 
/**
 * Extraction status
 */
extraction_status: ExtractionStatus, 
/**
 * Individual file confidence
 */
confidence: number, 
/**
 * File content hash for change detection
 */
file_hash: string | null, };
