// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationOutcome } from "./GenerationOutcome";

/**
 * Generation record for feedback learning
 */
export type MuseGeneration = { 
/**
 * Unique generation ID
 */
id: string, 
/**
 * Pack used for this generation
 */
pack_id: string | null, 
/**
 * Generation provider (e.g., "runway", "midjourney")
 */
provider: string, 
/**
 * Original user prompt
 */
prompt: string, 
/**
 * Enriched prompt after MUSE influence
 */
enriched_prompt: string | null, 
/**
 * User outcome: kept, rejected, modified
 */
outcome: GenerationOutcome | null, 
/**
 * Outcome signal strength (-1.0 to 1.0)
 */
outcome_signal: number | null, 
/**
 * Timestamp
 */
created_at: string, };
