// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pack type classification
 */
export type MusePackType = "custom" | "auto" | "imported" | "marketplace" | "blend";
