// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Media type categories MUSE understands
 */
export type MuseMediaType = "image" | "video" | "audio" | "document" | "project_file";
