// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotionProfile } from "./MotionProfile";
import type { MusePackType } from "./MusePackType";
import type { SonicProfile } from "./SonicProfile";
import type { VisualProfile } from "./VisualProfile";
import type { WeightedTopic } from "./WeightedTopic";

/**
 * A MUSE Context Pack — the atomic unit of creative context.
 *
 * Derived from user files, not a folder of files. Contains semantic
 * distillation: embeddings, color profiles, compositional tendencies,
 * thematic topics, and anti-patterns.
 */
export type MusePack = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Human-readable name (e.g., "Meridian Album Art")
 */
name: string, 
/**
 * Optional description
 */
description: string | null, 
/**
 * Pack type
 */
pack_type: MusePackType, 
/**
 * Whether this pack is currently active for generation influence
 */
is_active: boolean, 
/**
 * Number of source files that contributed to this pack
 */
source_count: number, 
/**
 * Overall confidence in the pack's signals (0.0-1.0)
 */
confidence: number, 
/**
 * Visual signals: color, composition, texture
 */
visual: VisualProfile | null, 
/**
 * Sonic signals: timbre, rhythm, harmony, production
 */
sonic: SonicProfile | null, 
/**
 * Motion signals: pacing, transitions, camera
 */
motion: MotionProfile | null, 
/**
 * Thematic topics derived from the work
 */
topics: Array<WeightedTopic>, 
/**
 * Anti-patterns — what to explicitly avoid
 */
anti_patterns: Array<WeightedTopic>, 
/**
 * Style embedding centroid (384-dim, base64 encoded for serialization)
 */
style_centroid: string | null, 
/**
 * Creation timestamp
 */
created_at: string, 
/**
 * Last update timestamp
 */
updated_at: string, };
