// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Count of notifications grouped by type.
 */
export type NotificationTypeCount = { notification_type: string, count: number, };
