// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationTypeCount } from "./NotificationTypeCount";

/**
 * Summary of unread notifications.
 */
export type NotificationSummary = { total_unread: number, by_type: Array<NotificationTypeCount>, };
