// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A topic tracked by 3 or more team members.
 */
export type OverlapZone = { topic: string, members: Array<string>, member_count: number, };
