// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary statistics for MUSE packs
 */
export type PackStats = { total_packs: number, active_packs: number, total_sources: number, total_generations: number, };
