// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackConcept = { name: string, keywords: Array<string>, importance: number, };
