// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaMetrics = { name: string, display_name: string, f1: number, precision: number, recall: number, separation_gap: number, tp: number, fp: number, tn: number, fn: number, };
