// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preemption win â€” record of a case where 4DA caught something before it became urgent.
 * Populated by the background validator (Phase 2 plan, scheduled task runs weekly)
 * that checks whether past preemption alerts were later validated by reality
 * (e.g. a CVE we warned about was published, a breaking change actually shipped).
 */
export type PreemptionWin = { alert_id: string, alert_title: string, alerted_at: string, incident_at: string | null, lead_time_hours: number | null, verified: boolean, };
