// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreemptionAlert } from "./PreemptionAlert";

/**
 * The full preemption feed with summary counts.
 */
export type PreemptionFeed = { alerts: Array<PreemptionAlert>, total: number, critical_count: number, high_count: number, };
