// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category of preemption alert.
 */
export type PreemptionType = "SecurityAdvisory" | "BreakingChange" | "MigrationWindow" | "EcosystemShift" | "MaintainerDecline" | "KnowledgeBlindSpot";
