// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreemptionWin = { alert_id: string, alert_title: string, alerted_at: string, incident_at: string | null, lead_time_hours: number | null, verified: boolean, };
