// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance: maps a claim in the render to its source items.
 */
export type RenderProvenance = { render_id: bigint, claim_index: bigint, claim_text: string, source_item_ids: Array<bigint>, source_titles: Array<string>, source_urls: Array<string>, };
