// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RigRequirements = { ollama_running: boolean, ollama_url: string, embedding_model: string | null, embedding_available: boolean, gpu_detected: boolean, recommended_model: string, estimated_ram_gb: number, can_reach_grade_a: boolean, grade_a_requirements: Array<string>, };
