// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source shared by a team member for others to discover and adopt.
 */
export type SharedSource = { id: string, team_id: string, source_type: string, 
/**
 * JSON string of non-sensitive source configuration
 */
config_summary: string, recommendation: string, shared_by: string, upvotes: number, created_at: string, };
