// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audio characteristics extracted from music/sound files
 */
export type SonicProfile = { 
/**
 * Spectral brightness: 0.0 (dark) to 1.0 (bright)
 */
brightness: number, 
/**
 * Warmth: 0.0 (cold/digital) to 1.0 (warm/analog)
 */
warmth: number, 
/**
 * Sonic density: 0.0 (sparse) to 1.0 (dense)
 */
density: number, 
/**
 * Tempo range in BPM [min, max]
 */
tempo_range: [number, number] | null, 
/**
 * Most common tempo
 */
tempo_center: number | null, 
/**
 * Grid strictness: 0.0 (free) to 1.0 (quantized)
 */
grid_strictness: number, 
/**
 * Key affinities (e.g., ["Dm", "Am", "F"])
 */
key_affinities: Array<string>, 
/**
 * Mode preference
 */
mode_preference: string | null, 
/**
 * Stereo width: 0.0 (mono) to 1.0 (wide)
 */
stereo_width: number, 
/**
 * Dynamic range: 0.0 (compressed) to 1.0 (dynamic)
 */
dynamic_range: number, };
