// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceFpRate = { source_type: string, total: number, fp_count: number, fp_rate: number, };
