// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSO provider configuration (SAML or OIDC).
 */
export type SsoConfig = { 
/**
 * Provider type: "saml" or "oidc"
 */
provider_type: string, 
/**
 * Identity Provider URL (SAML SSO endpoint or OIDC authorization endpoint)
 */
idp_url: string, 
/**
 * Service Provider entity ID (default: com.4da.app)
 */
entity_id: string, 
/**
 * IdP certificate in PEM format (SAML only)
 */
certificate: string | null, 
/**
 * OIDC client ID
 */
client_id: string | null, 
/**
 * OIDC issuer URL
 */
issuer: string | null, 
/**
 * Whether SSO is enabled
 */
enabled: boolean, };
