// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An active SSO session with extracted identity.
 */
export type SsoSession = { 
/**
 * User email from IdP assertion
 */
email: string, 
/**
 * Display name from IdP assertion
 */
display_name: string, 
/**
 * Group memberships from IdP assertion
 */
groups: Array<string>, 
/**
 * ISO 8601 timestamp of authentication
 */
authenticated_at: string, 
/**
 * Optional expiry (ISO 8601) — session invalid after this time
 */
expires_at: string | null, 
/**
 * Provider that authenticated this session ("saml" or "oidc")
 */
provider_type: string, };
