// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action the user can take in response to an alert.
 */
export type SuggestedAction = { 
/**
 * One of: "dismiss", "watch", "investigate", "review_decision"
 */
action_type: string, label: string, description: string, };
