// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of team monitoring activity.
 */
export type TeamMonitoringSummary = { total_signals: bigint, unresolved_signals: bigint, critical_count: bigint, high_count: bigint, multi_seat_count: bigint, avg_resolution_hours: number | null, most_active_topics: Array<[string, bigint]>, };
