// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operations that can be synced between team members.
 * Each variant carries only metadata — never raw content or file paths.
 */
export type TeamOp = { "type": "ShareDnaSummary", primary_stack: Array<string>, interests: Array<string>, blind_spots: Array<string>, identity_summary: string, } | { "type": "ShareSignal", signal_id: string, chain_name: string, priority: string, tech_topics: Array<string>, suggested_action: string, } | { "type": "ResolveSignal", signal_id: string, resolution_notes: string, } | { "type": "ProposeDecision", decision_id: string, title: string, decision_type: string, rationale: string, } | { "type": "VoteOnDecision", decision_id: string, stance: string, rationale: string, } | { "type": "ShareContextSummary", active_topics: Array<string>, tech_scores: Array<[string, number]>, } | { "type": "DeliverTeamKey", target_client_id: string, 
/**
 * XChaCha20Poly1305 encrypted team key (encrypted with DH shared secret)
 */
encrypted_team_key: Array<number>, } | { "type": "ShareSource", source_type: string, config_summary: string, recommendation: string, } | { "type": "MemberJoined", display_name: string, role: string, } | { "type": "MemberLeft", reason: string, } | { "type": "RoleChanged", target_member_id: string, new_role: string, };
