// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberDetection } from "./MemberDetection";

/**
 * Aggregated signal summary across the team.
 */
export type TeamSignalSummary = { signal_id: string, chain_name: string, priority: string, tech_topics: Array<string>, detected_by: Array<MemberDetection>, 
/**
 * Higher when multiple seats confirm (base 0.5 + 0.15 per additional detector, capped 1.0).
 */
team_confidence: number, first_detected_at: string, suggested_action: string, resolved: boolean, };
