// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlapZone } from "./OverlapZone";
import type { TeamBlindSpot } from "./TeamBlindSpot";
import type { TeamTechEntry } from "./TeamTechEntry";
import type { UniqueStrength } from "./UniqueStrength";

/**
 * Aggregated team intelligence profile.
 */
export type TeamProfile = { team_id: string, member_count: number, 
/**
 * Collective tech stack with per-member confidence.
 */
collective_stack: Array<TeamTechEntry>, 
/**
 * Fraction of the team's adjacent ecosystem covered (0.0–1.0).
 */
stack_coverage: number, 
/**
 * Topics relevant to the team's stack that no member tracks.
 */
blind_spots: Array<TeamBlindSpot>, 
/**
 * Topics watched by 3+ members (redundancy / shared interest).
 */
overlap_zones: Array<OverlapZone>, 
/**
 * Tech known by exactly one member (bus-factor = 1).
 */
unique_strengths: Array<UniqueStrength>, 
/**
 * ISO-8601 timestamp when this profile was computed.
 */
generated_at: string, };
