// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the team sync system
 */
export type TeamSyncStatus = { enabled: boolean, connected: boolean, team_id: string | null, client_id: string | null, display_name: string | null, role: string | null, member_count: number, pending_outbound: number, last_sync_at: string | null, last_relay_seq: bigint, };
