// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamOp } from "./TeamOp";

/**
 * A single metadata entry queued for sync with the team relay.
 */
export type TeamMetadataEntry = { 
/**
 * UUID — idempotency key for deduplication
 */
entry_id: string, 
/**
 * UUID of the team member who created this entry
 */
client_id: string, 
/**
 * Hybrid Logical Clock timestamp for Last-Write-Wins ordering
 */
hlc_timestamp: bigint, 
/**
 * The operation to apply
 */
operation: TeamOp, };
