// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A technology in the collective stack.
 */
export type TeamTechEntry = { tech: string, 
/**
 * Members who list this in their primary stack.
 */
members: Array<string>, 
/**
 * Fraction of team that knows this tech (0.0–1.0).
 */
team_confidence: number, };
