// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A team-level signal aggregated from individual member detections.
 */
export type TeamSignal = { id: string, team_id: string, signal_type: string, title: string, severity: string, tech_topics: Array<string>, detected_by_count: number, first_detected: string, last_detected: string, resolved: boolean, resolved_by: string | null, resolved_at: string | null, resolution_notes: string | null, };
