// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered team member visible to all seats
 */
export type TeamMember = { client_id: string, display_name: string, role: string, last_seen: string | null, };
