// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A team decision with vote count for list views.
 */
export type TeamDecision = { id: string, team_id: string, title: string, decision_type: string, rationale: string, proposed_by: string, status: string, created_at: string, resolved_at: string | null, vote_count: bigint, };
