// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single team notification.
 */
export type TeamNotification = { id: string, team_id: string, notification_type: string, title: string, body: string | null, severity: string, read: boolean, created_at: string, metadata: any, };
