// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A topic adjacent to the team's stack that nobody monitors.
 */
export type TeamBlindSpot = { topic: string, 
/**
 * The stack entry/entries that make this topic relevant.
 */
related_to: Array<string>, 
/**
 * "high" if related to 3+ team members' stack, else "medium".
 */
severity: string, };
