// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrustEventType } from "./TrustEventType";

export type TrustEvent = { event_type: TrustEventType, signal_id: string | null, alert_id: string | null, source_type: string | null, topic: string | null, user_action: string | null, confidence_at_surface: number | null, notes: string | null, };
