// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrustSummary = { period_days: number, total_surfaced: number, acted_on: number, dismissed: number, false_positives: number, 
/**
 * Precision score: 0.0–1.0 (TP / (TP + FP))
 */
precision: number, action_conversion_rate: number, preemption_wins: number, avg_lead_time_hours: number | null, 
/**
 * One of: "improving", "stable", "declining"
 */
trend: string, };
