// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A technology known by exactly one member (bus-factor risk).
 */
export type UniqueStrength = { tech: string, sole_expert: string, risk_level: string, };
