// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorWeight } from "./ColorWeight";

/**
 * Visual characteristics extracted from image/video content
 */
export type VisualProfile = { 
/**
 * Dominant colors with weights (sum to 1.0)
 */
dominant_colors: Array<ColorWeight>, 
/**
 * Color temperature: 0.0 (cool) to 1.0 (warm)
 */
temperature: number, 
/**
 * Contrast level: 0.0 (flat) to 1.0 (high contrast)
 */
contrast: number, 
/**
 * Saturation level: 0.0 (monochrome) to 1.0 (vivid)
 */
saturation: number, 
/**
 * Palette harmony type
 */
harmony: string | null, 
/**
 * Symmetry tendency: 0.0 (asymmetric) to 1.0 (symmetric)
 */
symmetry: number, 
/**
 * Negative space: 0.0 (dense) to 1.0 (spacious)
 */
negative_space: number, 
/**
 * Dominant focal point positioning
 */
focal_point: string | null, 
/**
 * Perceived depth: 0.0 (flat) to 1.0 (deep)
 */
depth: number, 
/**
 * Grain/noise tendency: 0.0 (clean) to 1.0 (heavy grain)
 */
grain: number, 
/**
 * Organic vs geometric: 0.0 (geometric) to 1.0 (organic)
 */
organic_vs_geometric: number, };
