// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebhookDelivery = { id: string, webhook_id: string, event_type: string, status: string, http_status: number | null, attempt_count: number, created_at: string, delivered_at: string | null, };
