// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Webhook = { id: string, team_id: string, name: string, url: string, events: Array<string>, active: boolean, failure_count: number, last_fired_at: string | null, last_status_code: number | null, created_at: string, };
