// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A topic or anti-pattern with a weight/strength
 */
export type WeightedTopic = { 
/**
 * Topic label (e.g., "organic forms", "corporate")
 */
label: string, 
/**
 * Weight or strength (0.0-1.0)
 */
weight: number, };
