import { useState, useRef, memo } from 'react';
import { useTranslation } from 'react-i18next';
import { cmd } from '../lib/commands';
import type { DeveloperDna } from '../types';
import { getSourceFullName } from '../config/sources';
import { useAppStore } from '../store';
import { ProGate } from './ProGate';

export const DeveloperDnaPanel = memo(function DeveloperDnaPanel() {
  const { t } = useTranslation();
  const addToast = useAppStore(s => s.addToast);
  const [dna, setDna] = useState<DeveloperDna | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const loaded = useRef(false);

  const loadDna = async () => {
    setLoading(true);
    setError(null);
    try {
      const d = await cmd('get_developer_dna');
      setDna(d);
      loaded.current = true;
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  const copyAsMarkdown = async () => {
    try {
      const md = await cmd('export_developer_dna_markdown');
      await window.navigator.clipboard.writeText(md);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard may not be available
    }
  };

  const downloadCard = async (format: 'svg' | 'png') => {
    try {
      const svg = await cmd('export_developer_dna_card');
      if (format === 'svg') {
        const blob = new Blob([svg], { type: 'image/svg+xml' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'developer-dna-card.svg';
        a.click();
        URL.revokeObjectURL(url);
      } else {
        // Rasterize SVG to PNG via canvas
        const canvas = document.createElement('canvas');
        canvas.width = 1600; // 2x for retina
        canvas.height = 840;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;
        const img = document.createElement('img');
        const svgBlob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
        const svgUrl = URL.createObjectURL(svgBlob);
        img.onload = () => {
          ctx.drawImage(img, 0, 0, 1600, 840);
          URL.revokeObjectURL(svgUrl);
          canvas.toBlob((blob) => {
            if (!blob) return;
            const pngUrl = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = pngUrl;
            a.download = 'developer-dna-card.png';
            a.click();
            URL.revokeObjectURL(pngUrl);
          }, 'image/png');
        };
        img.src = svgUrl;
      }
      addToast('success', t('dna.cardDownloaded'));
    } catch {
      addToast('error', t('dna.cardDownloadFailed'));
    }
  };

  const handleCopyCard = async () => {
    if (!dna) return;
    const summary = [
      dna.identity_summary,
      '',
      `Primary: ${dna.primary_stack.join(', ')}`,
      dna.adjacent_tech.length > 0 ? `Adjacent: ${dna.adjacent_tech.join(', ')}` : null,
      dna.blind_spots.length > 0 ? `Blind spots: ${dna.blind_spots.map(s => s.dependency).join(', ')}` : null,
      '',
      'Generated by 4DA — Sovereign Developer Intelligence',
    ].filter(Boolean).join('\n');
    await navigator.clipboard.writeText(summary);
    addToast('success', t('dna.copiedToClipboard'));
  };

  return (
    <ProGate feature="Developer DNA">
    <div className="bg-bg-secondary rounded-lg border border-border overflow-hidden">
      <button
        onClick={() => {
          const willExpand = !expanded;
          setExpanded(willExpand);
          if (willExpand && !loaded.current) {
            loadDna();
          }
        }}
        className="w-full px-5 py-4 flex items-center justify-between hover:bg-[#1A1A1A] transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-bg-tertiary rounded-lg flex items-center justify-center">
            <span className="text-sm">&#x1F9EC;</span>
          </div>
          <div className="text-left">
            <h2 className="font-medium text-white text-sm">{t('dna.title')}</h2>
            <p className="text-xs text-text-muted">
              {dna ? dna.identity_summary : t('dna.defaultSubtitle')}
            </p>
          </div>
        </div>
        <span className="text-text-muted text-sm">{expanded ? '\u25BE' : '\u25B8'}</span>
      </button>

      {expanded && (
        <div className="border-t border-border">
          {loading && (
            <div className="flex items-center gap-2 py-8 justify-center">
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              <span className="text-xs text-text-muted">{t('dna.building')}</span>
            </div>
          )}

          {error && (
            <div className="m-4 text-xs text-red-400 p-3 bg-red-500/10 rounded border border-red-500/20">
              {error}
            </div>
          )}

          {dna && !loading && (
            <div className="p-5 space-y-6">
              {/* Identity Header */}
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold text-white">{dna.identity_summary}</h3>
                  <p className="text-xs text-text-muted mt-1">
                    {t('dna.statsLine', { days: dna.stats.days_active, items: dna.stats.total_items_processed.toLocaleString(), rate: dna.stats.rejection_rate.toFixed(1) })}
                  </p>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={() => downloadCard('png')}
                    className="px-3 py-1.5 text-xs bg-[#D4AF37]/10 hover:bg-[#D4AF37]/20 border border-[#D4AF37]/30 rounded-lg text-[#D4AF37] transition-colors font-medium"
                  >
                    {t('dna.downloadPng')}
                  </button>
                  <button
                    onClick={() => downloadCard('svg')}
                    className="px-3 py-1.5 text-xs bg-white/10 hover:bg-white/15 text-white border border-white/20 rounded-lg transition-colors"
                  >
                    {t('dna.downloadSvg')}
                  </button>
                  <button
                    onClick={handleCopyCard}
                    className="px-3 py-1.5 text-xs bg-bg-tertiary hover:bg-border border border-border rounded-lg text-text-secondary transition-colors"
                  >
                    {t('dna.copyDna')}
                  </button>
                  <button
                    onClick={copyAsMarkdown}
                    className="px-3 py-1.5 text-xs bg-bg-tertiary hover:bg-border border border-border rounded-lg text-text-secondary transition-colors"
                  >
                    {copied ? t('action.copied') : t('dna.markdown')}
                  </button>
                </div>
              </div>

              {/* Primary Stack */}
              {dna.primary_stack.length > 0 && (
                <Section title={t('dna.primaryStack')}>
                  <div className="flex flex-wrap gap-2">
                    {dna.primary_stack.map((tech) => (
                      <Tag key={tech} label={tech} variant="primary" />
                    ))}
                  </div>
                </Section>
              )}

              {/* Adjacent Tech */}
              {dna.adjacent_tech.length > 0 && (
                <Section title={t('dna.ecosystem')}>
                  <div className="flex flex-wrap gap-2">
                    {dna.adjacent_tech.map((tech) => (
                      <Tag key={tech} label={tech} variant="secondary" />
                    ))}
                  </div>
                </Section>
              )}

              {/* Top Dependencies */}
              {dna.top_dependencies.length > 0 && (
                <Section title={t('dna.keyDependencies')}>
                  <div className="flex flex-wrap gap-2">
                    {dna.top_dependencies.slice(0, 20).map((dep) => (
                      <Tag key={`${dep.name}-${dep.project_path}`} label={dep.name} variant="dep" />
                    ))}
                    {dna.top_dependencies.length > 20 && (
                      <span className="text-xs text-text-muted self-center">
                        {t('dna.moreItems', { count: dna.top_dependencies.length - 20 })}
                      </span>
                    )}
                  </div>
                </Section>
              )}

              {/* Interests */}
              {dna.interests.length > 0 && (
                <Section title={t('dna.interests')}>
                  <div className="flex flex-wrap gap-2">
                    {dna.interests.map((topic) => (
                      <Tag key={topic} label={topic} variant="interest" />
                    ))}
                  </div>
                </Section>
              )}

              {/* Attention Distribution */}
              {dna.top_engaged_topics.length > 0 && (
                <Section title={t('dna.attentionDistribution')}>
                  <div className="space-y-2">
                    {dna.top_engaged_topics.slice(0, 8).map((topic) => (
                      <div key={topic.topic} className="flex items-center gap-3">
                        <span className="text-xs text-text-secondary w-28 truncate">{topic.topic}</span>
                        <div className="flex-1 h-2 bg-bg-tertiary rounded-full overflow-hidden">
                          <div
                            className="h-full bg-white/20 rounded-full"
                            style={{ width: `${Math.min(100, topic.percent_of_total)}%` }}
                          />
                        </div>
                        <span className="text-xs text-text-muted w-10 text-right">
                          {topic.percent_of_total.toFixed(0)}%
                        </span>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Blind Spots */}
              {dna.blind_spots.length > 0 && (
                <Section title={t('dna.blindSpots')}>
                  <div className="space-y-1">
                    {dna.blind_spots.slice(0, 5).map((spot) => (
                      <div
                        key={spot.dependency}
                        className="flex items-center justify-between px-3 py-2 bg-amber-500/5 rounded border border-amber-500/10"
                      >
                        <span className="text-xs text-amber-300 font-mono">{spot.dependency}</span>
                        <span className="text-xs text-text-muted">{spot.severity} &middot; {t('dna.daysStale', { days: spot.days_stale })}</span>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Source Engagement */}
              {dna.source_engagement.length > 0 && (
                <Section title={t('dna.sourceEngagement')}>
                  <div className="grid grid-cols-2 gap-2">
                    {dna.source_engagement.map((src) => (
                      <div
                        key={src.source_type}
                        className="px-3 py-2 bg-[#1A1A1A] rounded border border-border"
                      >
                        <div className="text-xs font-medium text-text-secondary">
                          {getSourceFullName(src.source_type)}
                        </div>
                        <div className="text-xs text-text-muted mt-0.5">
                          {t('dna.sourceStats', { seen: src.items_seen.toLocaleString(), saved: src.items_saved })}
                        </div>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {/* Stats Footer */}
              <div className="pt-4 border-t border-border flex items-center justify-between">
                <div className="flex gap-6">
                  <Stat label={t('dna.projects')} value={dna.stats.project_count} />
                  <Stat label={t('dna.dependencies')} value={dna.stats.dependency_count} />
                  <Stat label={t('dna.rejectionRate')} value={`${dna.stats.rejection_rate.toFixed(1)}%`} />
                </div>
                <span className="text-xs text-text-muted">
                  {t('dna.generatedAt', { date: dna.generated_at.slice(0, 10) })}
                </span>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
    </ProGate>
  );
});

// ============================================================================
// Sub-components
// ============================================================================

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h4 className="text-xs font-medium text-text-muted uppercase tracking-wider mb-2">{title}</h4>
      {children}
    </div>
  );
}

const TAG_VARIANTS: Record<string, string> = {
  primary: 'bg-white/10 text-white border-white/20',
  secondary: 'bg-white/5 text-text-secondary border-white/10',
  dep: 'bg-blue-500/10 text-blue-300 border-blue-500/20',
  interest: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20',
};

function Tag({ label, variant }: { label: string; variant: string }) {
  const cls = TAG_VARIANTS[variant] || TAG_VARIANTS.secondary;
  return (
    <span className={`px-2 py-1 text-xs rounded border font-mono ${cls}`}>
      {label}
    </span>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div>
      <div className="text-sm font-medium text-white">{typeof value === 'number' ? value.toLocaleString() : value}</div>
      <div className="text-xs text-text-muted">{label}</div>
    </div>
  );
}
