#!/usr/bin/env node
/**
 * i18n Guard — prevents untranslatable code from entering the codebase.
 *
 * Runs in pre-commit. Two modes:
 *   BLOCK:  defaultValue usage in t() calls (must use locale files)
 *   WARN:   new English keys missing from other locales (batch-translate later)
 *
 * Usage:
 *   node scripts/i18n-guard.cjs                # check staged files
 *   node scripts/i18n-guard.cjs --all          # check entire codebase
 *   node scripts/i18n-guard.cjs --fix-report   # generate .ai/I18N-DEBT.md
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const LOCALES_DIR = path.join(ROOT, 'src', 'locales');
const SRC_DIR = path.join(ROOT, 'src');
const DEBT_FILE = path.join(ROOT, '.ai', 'I18N-DEBT.md');

const ALL_MODE = process.argv.includes('--all');
const FIX_REPORT = process.argv.includes('--fix-report');

// ============================================================================
// 1. Detect defaultValue usage in TSX/TS files (BLOCKING)
// ============================================================================

function findDefaultValueUsage(files) {
  const violations = [];
  const pattern = /defaultValue\s*[:=]\s*['"`]/;

  for (const file of files) {
    if (!file.endsWith('.tsx') && !file.endsWith('.ts')) continue;
    if (file.includes('node_modules') || file.includes('.test.')) continue;

    let content;
    try {
      content = fs.readFileSync(path.join(ROOT, file), 'utf-8');
    } catch { continue; }

    const lines = content.split('\n');
    for (let i = 0; i < lines.length; i++) {
      if (pattern.test(lines[i])) {
        // Extract the defaultValue string
        const match = lines[i].match(/defaultValue\s*[:=]\s*['"`]([^'"`]*)/);
        const value = match ? match[1].substring(0, 60) : '(complex expression)';
        violations.push({ file, line: i + 1, value });
      }
    }
  }

  return violations;
}

// ============================================================================
// 2. Find missing translation keys (WARNING)
// ============================================================================

function findMissingKeys() {
  const namespaces = ['ui', 'errors', 'streets', 'coach', 'signals'];
  const languages = fs.readdirSync(LOCALES_DIR)
    .filter(d => {
      try { return fs.statSync(path.join(LOCALES_DIR, d)).isDirectory() && d !== 'en'; }
      catch { return false; }
    });

  const missing = [];

  for (const ns of namespaces) {
    const enPath = path.join(LOCALES_DIR, 'en', `${ns}.json`);
    if (!fs.existsSync(enPath)) continue;

    let enKeys;
    try { enKeys = Object.keys(JSON.parse(fs.readFileSync(enPath, 'utf-8'))); }
    catch { continue; }

    for (const lang of languages) {
      const langPath = path.join(LOCALES_DIR, lang, `${ns}.json`);
      if (!fs.existsSync(langPath)) {
        missing.push({ lang, ns, keys: enKeys, count: enKeys.length });
        continue;
      }

      let langKeys;
      try { langKeys = new Set(Object.keys(JSON.parse(fs.readFileSync(langPath, 'utf-8')))); }
      catch { continue; }

      const missingKeys = enKeys.filter(k => !langKeys.has(k));
      if (missingKeys.length > 0) {
        missing.push({ lang, ns, keys: missingKeys, count: missingKeys.length });
      }
    }
  }

  return { missing, languages };
}

// ============================================================================
// 3. Get staged files (for commit-time checking)
// ============================================================================

function getStagedFiles() {
  try {
    const output = execSync('git diff --cached --name-only --diff-filter=ACM', {
      encoding: 'utf-8',
      cwd: ROOT,
    });
    return output.trim().split('\n').filter(Boolean);
  } catch {
    return [];
  }
}

function getAllSourceFiles() {
  const files = [];
  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!entry.name.startsWith('.') && entry.name !== 'node_modules' && entry.name !== 'target' && entry.name !== 'dist') {
          walk(full);
        }
      } else if (entry.name.endsWith('.tsx') || entry.name.endsWith('.ts')) {
        files.push(path.relative(ROOT, full).replace(/\\/g, '/'));
      }
    }
  }
  walk(SRC_DIR);
  return files;
}

// ============================================================================
// 4. Generate debt report
// ============================================================================

function generateDebtReport(violations, missingData) {
  const now = new Date().toISOString().split('T')[0];
  const lines = [
    '# i18n Translation Debt',
    '',
    `> Auto-generated by \`scripts/i18n-guard.cjs --fix-report\` on ${now}`,
    '> Do not edit manually — regenerate with the command above.',
    '',
  ];

  // defaultValue violations
  if (violations.length > 0) {
    lines.push(`## defaultValue Bypasses (${violations.length})`, '');
    lines.push('These t() calls use defaultValue, bypassing the locale system:', '');
    for (const v of violations) {
      lines.push(`- \`${v.file}:${v.line}\` — "${v.value}"`);
    }
    lines.push('');
  } else {
    lines.push('## defaultValue Bypasses: NONE', '');
  }

  // Missing translations
  if (missingData.missing.length > 0) {
    const totalMissing = missingData.missing.reduce((sum, m) => sum + m.count, 0);
    lines.push(`## Missing Translation Keys (${totalMissing} total)`, '');
    lines.push('| Language | Namespace | Missing |');
    lines.push('|----------|-----------|---------|');
    for (const m of missingData.missing) {
      lines.push(`| ${m.lang} | ${m.ns}.json | ${m.count} |`);
    }
    lines.push('');

    // List actual keys per language (top 5 per lang)
    const byLang = {};
    for (const m of missingData.missing) {
      if (!byLang[m.lang]) byLang[m.lang] = [];
      byLang[m.lang].push(...m.keys.slice(0, 5));
    }
    lines.push('### Sample missing keys:', '');
    for (const [lang, keys] of Object.entries(byLang)) {
      lines.push(`**${lang}**: ${keys.slice(0, 5).map(k => '`' + k + '`').join(', ')}${keys.length > 5 ? '...' : ''}`);
    }
    lines.push('');
  } else {
    lines.push('## Missing Translation Keys: NONE', '');
  }

  lines.push('## How to fix', '');
  lines.push('1. **defaultValue bypasses**: Move the string to `src/locales/en/ui.json`, then remove `defaultValue` from the t() call');
  lines.push('2. **Missing keys**: Add translations to each locale file. Use Claude: "translate these keys to all locales"');
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// Main
// ============================================================================

const files = ALL_MODE ? getAllSourceFiles() : getStagedFiles();
const violations = findDefaultValueUsage(files);
const missingData = findMissingKeys();

// Generate debt report if requested
if (FIX_REPORT) {
  const allFiles = getAllSourceFiles();
  const allViolations = findDefaultValueUsage(allFiles);
  const report = generateDebtReport(allViolations, missingData);
  fs.mkdirSync(path.dirname(DEBT_FILE), { recursive: true });
  fs.writeFileSync(DEBT_FILE, report, 'utf-8');
  console.log(`i18n debt report written to ${path.relative(ROOT, DEBT_FILE)}`);
  console.log(`  ${allViolations.length} defaultValue bypasses`);
  console.log(`  ${missingData.missing.reduce((s, m) => s + m.count, 0)} missing translation keys`);
  process.exit(0);
}

// Report results
let exitCode = 0;

if (violations.length > 0) {
  console.log('');
  console.log('i18n GUARD: defaultValue usage detected in staged files!');
  console.log('Move these strings to src/locales/en/ui.json instead:');
  console.log('');
  for (const v of violations) {
    console.log(`  ${v.file}:${v.line} — "${v.value}"`);
  }
  console.log('');
  exitCode = 1;
}

// Missing keys are warnings only (non-blocking)
const totalMissing = missingData.missing.reduce((s, m) => s + m.count, 0);
if (totalMissing > 0 && files.some(f => f.includes('locales/'))) {
  console.log(`i18n: ${totalMissing} translation keys missing across ${missingData.missing.length} locale/namespace pairs`);
}

if (exitCode === 0 && violations.length === 0) {
  // Silent success — don't clutter output
}

process.exit(exitCode);
