//! Developer DNA — Shareable Technology Identity Profile
//!
//! Aggregates data from domain profile, attention tracking, knowledge gaps,
//! and source engagement into a single shareable snapshot of the developer's
//! technology identity. Think "Spotify Wrapped for developers."

use serde::{Deserialize, Serialize};
use tracing::info;

use crate::domain_profile;
use crate::error::Result;

// ============================================================================
// Types
// ============================================================================

/// Complete Developer DNA snapshot
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeveloperDna {
    /// When this snapshot was generated
    pub generated_at: String,
    /// Primary tech stack (from onboarding + ACE detection)
    pub primary_stack: Vec<String>,
    /// Adjacent/ecosystem technologies inferred from primary stack
    pub adjacent_tech: Vec<String>,
    /// Top dependencies from project manifests (notable ones only)
    pub top_dependencies: Vec<DependencyEntry>,
    /// Declared interest topics
    pub interests: Vec<String>,
    /// Top engaged topics from behavior (what you actually click/save)
    pub top_engaged_topics: Vec<EngagedTopic>,
    /// Knowledge blind spots (dependencies you use but don't track)
    pub blind_spots: Vec<BlindSpotEntry>,
    /// Source preferences: which sources you engage with most
    pub source_engagement: Vec<SourceEngagement>,
    /// Overall stats
    pub stats: DnaStats,
    /// Tech identity summary line (e.g. "Rust/TypeScript systems developer")
    pub identity_summary: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DependencyEntry {
    pub name: String,
    pub project_path: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagedTopic {
    pub topic: String,
    pub interactions: u32,
    pub percent_of_total: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlindSpotEntry {
    pub dependency: String,
    pub severity: String,
    pub days_stale: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceEngagement {
    pub source_type: String,
    pub items_seen: u32,
    pub items_saved: u32,
    pub engagement_rate: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DnaStats {
    /// Total items processed by the system
    pub total_items_processed: u32,
    /// Total items marked relevant
    pub total_relevant: u32,
    /// System rejection rate (as percentage, e.g. 99.2)
    pub rejection_rate: f32,
    /// Number of monitored projects
    pub project_count: u32,
    /// Number of unique dependencies tracked
    pub dependency_count: u32,
    /// Days since first use
    pub days_active: u32,
}

// ============================================================================
// Implementation
// ============================================================================

/// Generate a complete Developer DNA snapshot
pub fn generate_dna() -> Result<DeveloperDna> {
    let conn = crate::open_db_connection()?;

    info!(target: "4da::dna", "Generating Developer DNA snapshot");

    // 1. Domain profile
    let profile = domain_profile::build_domain_profile(&conn);

    let mut primary_stack: Vec<String> = profile.primary_stack.into_iter().collect();
    primary_stack.sort();

    let mut adjacent_tech: Vec<String> = profile.adjacent_tech.into_iter().collect();
    adjacent_tech.sort();

    let mut interests: Vec<String> = profile.interest_topics.into_iter().collect();
    interests.sort();

    // 2. Top dependencies (from project_dependencies, limit 30)
    let mut top_dependencies = get_top_dependencies(&conn)?;
    // Dedup dependencies by name (case-insensitive, keep first occurrence)
    let mut seen_deps = std::collections::HashSet::new();
    top_dependencies.retain(|d| seen_deps.insert(d.name.to_lowercase()));

    // 3. Engagement data (from feedback/interactions)
    let top_engaged_topics = get_top_engaged_topics(&conn)?;

    // 4. Blind spots (from knowledge gaps)
    let blind_spots = get_blind_spots(&conn)?;

    // 5. Source engagement stats
    let source_engagement = get_source_engagement(&conn)?;

    // 6. Overall stats
    let stats = compute_stats(&conn)?;

    // 7. Identity summary
    let identity_summary = build_identity_summary(&primary_stack, &top_dependencies);

    Ok(DeveloperDna {
        generated_at: chrono::Utc::now().to_rfc3339(),
        primary_stack,
        adjacent_tech,
        top_dependencies,
        interests,
        top_engaged_topics,
        blind_spots,
        source_engagement,
        stats,
        identity_summary,
    })
}

/// Export Developer DNA as shareable markdown
pub fn export_as_markdown(dna: &DeveloperDna) -> String {
    let mut md = String::new();

    md.push_str("# Developer DNA\n\n");
    md.push_str(&format!("**{}**\n\n", dna.identity_summary));
    md.push_str(&format!(
        "*Generated by [4DA](https://github.com/4da-dev/4da-home) on {}*\n\n",
        &dna.generated_at[..10]
    ));

    // Primary Stack
    if !dna.primary_stack.is_empty() {
        md.push_str("## Primary Stack\n\n");
        for tech in &dna.primary_stack {
            md.push_str(&format!("- {}\n", capitalize(tech)));
        }
        md.push('\n');
    }

    // Top Dependencies
    if !dna.top_dependencies.is_empty() {
        md.push_str("## Key Dependencies\n\n");
        for dep in dna.top_dependencies.iter().take(15) {
            md.push_str(&format!("- `{}`\n", dep.name));
        }
        md.push('\n');
    }

    // Interests
    if !dna.interests.is_empty() {
        md.push_str("## Interests\n\n");
        for topic in &dna.interests {
            md.push_str(&format!("- {}\n", capitalize(topic)));
        }
        md.push('\n');
    }

    // Top Engaged Topics
    if !dna.top_engaged_topics.is_empty() {
        md.push_str("## Where My Attention Goes\n\n");
        md.push_str("| Topic | Engagement |\n|-------|------------|\n");
        for topic in dna.top_engaged_topics.iter().take(10) {
            let bar = bar_chart(topic.percent_of_total);
            md.push_str(&format!(
                "| {} | {} {:.0}% |\n",
                capitalize(&topic.topic),
                bar,
                topic.percent_of_total
            ));
        }
        md.push('\n');
    }

    // Blind Spots
    if !dna.blind_spots.is_empty() {
        md.push_str("## Blind Spots\n\n");
        for spot in dna.blind_spots.iter().take(5) {
            md.push_str(&format!(
                "- **{}** — {} severity, {}d stale\n",
                spot.dependency, spot.severity, spot.days_stale
            ));
        }
        md.push('\n');
    }

    // Stats
    md.push_str("## Stats\n\n");
    md.push_str(&format!(
        "- Items processed: {}\n",
        dna.stats.total_items_processed
    ));
    md.push_str(&format!(
        "- Rejection rate: {:.1}%\n",
        dna.stats.rejection_rate
    ));
    md.push_str(&format!(
        "- Projects monitored: {}\n",
        dna.stats.project_count
    ));
    md.push_str(&format!(
        "- Dependencies tracked: {}\n",
        dna.stats.dependency_count
    ));
    md.push_str(&format!("- Days active: {}\n", dna.stats.days_active));

    md
}

// ============================================================================
// Internal helpers
// ============================================================================

fn get_top_dependencies(conn: &rusqlite::Connection) -> Result<Vec<DependencyEntry>> {
    let mut deps = Vec::new();
    let mut stmt = conn.prepare(
        "SELECT DISTINCT package_name, project_path FROM project_dependencies
             WHERE is_dev = 0
             ORDER BY package_name
             LIMIT 50",
    )?;

    let rows = stmt.query_map([], |row| {
        Ok(DependencyEntry {
            name: row.get(0)?,
            project_path: row.get(1)?,
        })
    })?;

    for row in rows.flatten() {
        deps.push(row);
    }
    Ok(deps)
}

fn get_top_engaged_topics(conn: &rusqlite::Connection) -> Result<Vec<EngagedTopic>> {
    // Pull from topic_affinities (learned behavior)
    let mut topics = Vec::new();

    let query =
        "SELECT topic, affinity_score FROM topic_affinities ORDER BY affinity_score DESC LIMIT 20";
    if let Ok(mut stmt) = conn.prepare(query) {
        if let Ok(rows) = stmt.query_map([], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, f64>(1)?))
        }) {
            let all: Vec<(String, f64)> = rows.flatten().collect();
            let total_weight: f64 = all.iter().map(|(_, w)| w).sum();

            for (topic, weight) in all {
                let pct = if total_weight > 0.0 {
                    (weight / total_weight * 100.0) as f32
                } else {
                    0.0
                };
                topics.push(EngagedTopic {
                    topic,
                    interactions: weight as u32,
                    percent_of_total: pct,
                });
            }
        }
    }

    Ok(topics)
}

fn get_blind_spots(conn: &rusqlite::Connection) -> Result<Vec<BlindSpotEntry>> {
    // Simplified: find dependencies we haven't engaged with recently
    let mut spots = Vec::new();

    let query = "
        SELECT pd.package_name, MAX(pd.project_path) as project_path
        FROM project_dependencies pd
        WHERE pd.is_dev = 0
        AND pd.package_name NOT IN (
            SELECT DISTINCT topic FROM topic_affinities WHERE weight > 0.3
        )
        AND LENGTH(pd.package_name) >= 4
        GROUP BY pd.package_name
        ORDER BY pd.package_name
        LIMIT 10
    ";

    if let Ok(mut stmt) = conn.prepare(query) {
        if let Ok(rows) = stmt.query_map([], |row| {
            Ok(BlindSpotEntry {
                dependency: row.get(0)?,
                severity: "medium".to_string(),
                days_stale: 30, // Approximate; would need temporal tracking for precision
            })
        }) {
            for row in rows.flatten() {
                spots.push(row);
            }
        }
    }

    Ok(spots)
}

fn get_source_engagement(conn: &rusqlite::Connection) -> Result<Vec<SourceEngagement>> {
    let mut sources = Vec::new();

    // Total items by source
    let query = "
        SELECT source_type, COUNT(*) as total,
               SUM(CASE WHEN id IN (SELECT item_id FROM feedback WHERE action = 'save') THEN 1 ELSE 0 END) as saved
        FROM source_items
        GROUP BY source_type
        ORDER BY total DESC
    ";

    if let Ok(mut stmt) = conn.prepare(query) {
        if let Ok(rows) = stmt.query_map([], |row| {
            let total: u32 = row.get(1)?;
            let saved: u32 = row.get(2)?;
            let rate = if total > 0 {
                saved as f32 / total as f32 * 100.0
            } else {
                0.0
            };
            Ok(SourceEngagement {
                source_type: row.get(0)?,
                items_seen: total,
                items_saved: saved,
                engagement_rate: rate,
            })
        }) {
            for row in rows.flatten() {
                sources.push(row);
            }
        }
    }

    Ok(sources)
}

fn compute_stats(conn: &rusqlite::Connection) -> Result<DnaStats> {
    let total_items: u32 = conn
        .query_row("SELECT COUNT(*) FROM source_items", [], |row| row.get(0))
        .unwrap_or(0);

    let feedback_relevant: u32 = conn
        .query_row(
            "SELECT COUNT(*) FROM source_items WHERE id IN (SELECT item_id FROM feedback WHERE action IN ('save', 'click'))",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    // Also check AnalysisState for scoring-engine relevant count
    let scoring_relevant = {
        let state = crate::get_analysis_state();
        let guard = state.lock();
        guard
            .results
            .as_ref()
            .map(|r| r.iter().filter(|s| s.relevant).count() as u32)
            .unwrap_or(0)
    };
    let total_relevant = feedback_relevant.max(scoring_relevant);

    // Use analysis-scanned count as denominator (same as boot/status endpoints)
    // to avoid inflated rejection rate from accumulated DB items
    let analysis_total = {
        let state = crate::get_analysis_state();
        let guard = state.lock();
        guard.results.as_ref().map(|r| r.len() as u32).unwrap_or(0)
    };
    let effective_total = if analysis_total > 0 {
        analysis_total
    } else {
        total_items
    };

    let rejection_rate = if effective_total > 0 {
        ((1.0 - total_relevant as f32 / effective_total as f32) * 100.0)
            .min(100.0)
            .max(0.0)
    } else {
        0.0
    };

    let project_count: u32 = conn
        .query_row(
            "SELECT COUNT(DISTINCT project_path) FROM project_dependencies",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    let dependency_count: u32 = conn
        .query_row(
            "SELECT COUNT(DISTINCT package_name) FROM project_dependencies WHERE is_dev = 0",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    // Days active: difference between earliest and latest source_items
    let days_active: u32 = conn
        .query_row(
            "SELECT CAST((julianday('now') - julianday(MIN(created_at))) AS INTEGER) FROM source_items",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    Ok(DnaStats {
        total_items_processed: total_items,
        total_relevant,
        rejection_rate,
        project_count,
        dependency_count,
        days_active,
    })
}

fn build_identity_summary(primary_stack: &[String], deps: &[DependencyEntry]) -> String {
    if primary_stack.is_empty() {
        return "Developer (no stack configured yet)".to_string();
    }

    let top_langs: Vec<String> = primary_stack
        .iter()
        .take(3)
        .map(|s| capitalize(s))
        .collect();

    // Try to infer domain from dependencies
    let domain = infer_domain(primary_stack, deps);

    format!("{} {} developer", top_langs.join("/"), domain)
}

fn infer_domain(stack: &[String], deps: &[DependencyEntry]) -> &'static str {
    let all: Vec<String> = stack
        .iter()
        .chain(deps.iter().map(|d| &d.name))
        .map(|s| s.to_lowercase())
        .collect();

    let has = |term: &str| all.iter().any(|s| s.contains(term));

    if has("tauri") || has("electron") || has("wry") {
        "desktop"
    } else if has("react-native") || has("flutter") || has("swift") || has("kotlin") {
        "mobile"
    } else if has("tensorflow") || has("pytorch") || has("scikit") || has("transformers") {
        "ML/AI"
    } else if has("kubernetes") || has("terraform") || has("docker") || has("ansible") {
        "infrastructure"
    } else if has("next") || has("nuxt") || has("svelte") || has("remix") {
        "fullstack"
    } else if has("react") || has("vue") || has("angular") {
        "frontend"
    } else if has("actix") || has("axum") || has("express") || has("fastapi") || has("django") {
        "backend"
    } else if has("embedded") || has("stm32") || has("esp32") {
        "embedded"
    } else if has("wasm") || has("webassembly") {
        "WebAssembly"
    } else {
        "systems"
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

fn bar_chart(percent: f32) -> String {
    let filled = (percent / 10.0).round() as usize;
    let empty = 10usize.saturating_sub(filled);
    format!("{}{}", "\u{2588}".repeat(filled), "\u{2591}".repeat(empty))
}

// ============================================================================
// Tauri Commands
// ============================================================================

#[tauri::command]
pub async fn get_developer_dna() -> Result<DeveloperDna> {
    crate::settings::require_signal_feature("get_developer_dna")?;
    generate_dna()
}

#[tauri::command]
pub async fn export_developer_dna_markdown() -> Result<String> {
    crate::settings::require_signal_feature("export_developer_dna_markdown")?;
    let dna = generate_dna()?;
    Ok(export_as_markdown(&dna))
}

#[tauri::command]
pub async fn export_developer_dna_svg() -> Result<String> {
    crate::settings::require_signal_feature("export_developer_dna_svg")?;
    let dna = generate_dna()?;
    Ok(export_as_svg(&dna))
}

/// Export Developer DNA as a professional 800×420 card (premium shareable format)
#[tauri::command]
pub async fn export_developer_dna_card() -> Result<String> {
    crate::settings::require_signal_feature("export_developer_dna_card")?;
    let dna = generate_dna()?;
    Ok(export_as_card_svg(&dna))
}

/// Professional 800×420 Developer DNA card — designed for social sharing, portfolios, READMEs.
/// Dark theme with gold accent, structured layout, elegant typography.
pub fn export_as_card_svg(dna: &DeveloperDna) -> String {
    let date = if dna.generated_at.len() >= 10 {
        &dna.generated_at[..10]
    } else {
        &dna.generated_at
    };
    let identity = xml_escape(&dna.identity_summary);
    let stats = &dna.stats;

    // --- Header section ---
    let header = format!(
        r##"  <!-- Header -->
  <rect x="0" y="0" width="800" height="60" fill="#0D0D0D"/>
  <text x="32" y="36" fill="#D4AF37" font-family="'JetBrains Mono', 'SF Mono', monospace" font-size="11" font-weight="500" letter-spacing="0.15em">DEVELOPER DNA</text>
  <text x="768" y="36" fill="#444" font-family="'Inter', -apple-system, sans-serif" font-size="11" text-anchor="end">{date}</text>
  <line x1="32" y1="56" x2="768" y2="56" stroke="#222" stroke-width="1"/>"##,
        date = date,
    );

    // --- Identity section ---
    let identity_section = format!(
        r##"  <!-- Identity -->
  <text x="32" y="92" fill="#FFF" font-family="'Inter', -apple-system, sans-serif" font-size="22" font-weight="600">{identity}</text>"##,
        identity = identity,
    );

    // --- Tech stack pills ---
    let pills = build_card_pills(&dna.primary_stack, 32.0, 112.0);

    // --- Stats grid (4 columns) ---
    let stats_section = format!(
        r##"  <!-- Stats -->
  <g transform="translate(32,160)">
    <rect x="0" y="0" width="170" height="64" rx="6" fill="#141414" stroke="#1F1F1F"/>
    <text x="16" y="28" fill="#FFF" font-family="'JetBrains Mono', monospace" font-size="20" font-weight="600">{days}</text>
    <text x="16" y="48" fill="#666" font-family="'Inter', sans-serif" font-size="11">days active</text>

    <rect x="186" y="0" width="170" height="64" rx="6" fill="#141414" stroke="#1F1F1F"/>
    <text x="202" y="28" fill="#FFF" font-family="'JetBrains Mono', monospace" font-size="20" font-weight="600">{projects}</text>
    <text x="202" y="48" fill="#666" font-family="'Inter', sans-serif" font-size="11">projects scanned</text>

    <rect x="372" y="0" width="170" height="64" rx="6" fill="#141414" stroke="#1F1F1F"/>
    <text x="388" y="28" fill="#D4AF37" font-family="'JetBrains Mono', monospace" font-size="20" font-weight="600">{rejection:.1}%</text>
    <text x="388" y="48" fill="#666" font-family="'Inter', sans-serif" font-size="11">noise rejected</text>

    <rect x="558" y="0" width="178" height="64" rx="6" fill="#141414" stroke="#1F1F1F"/>
    <text x="574" y="28" fill="#FFF" font-family="'JetBrains Mono', monospace" font-size="20" font-weight="600">{deps}</text>
    <text x="574" y="48" fill="#666" font-family="'Inter', sans-serif" font-size="11">dependencies</text>
  </g>"##,
        days = stats.days_active,
        projects = stats.project_count,
        rejection = stats.rejection_rate,
        deps = stats.dependency_count,
    );

    // --- Topic engagement bars ---
    let topics_section = build_card_topics(&dna.top_engaged_topics);

    // --- Source engagement row ---
    let sources_section = build_card_sources(&dna.source_engagement);

    // --- Footer ---
    let footer = r##"  <!-- Footer -->
  <line x1="32" y1="390" x2="768" y2="390" stroke="#1F1F1F" stroke-width="1"/>
  <text x="32" y="410" fill="#444" font-family="'Inter', sans-serif" font-size="11">4da.ai</text>
  <text x="768" y="410" fill="#333" font-family="'Inter', sans-serif" font-size="11" text-anchor="end">All signal. No feed.</text>"##;

    format!(
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="800" height="420" viewBox="0 0 800 420">
  <defs>
    <linearGradient id="cardBg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0A0A0A"/>
      <stop offset="100%" stop-color="#080808"/>
    </linearGradient>
  </defs>
  <rect width="800" height="420" rx="12" fill="url(#cardBg)" stroke="#1A1A1A"/>
{header}
{identity}
{pills}
{stats}
{topics}
{sources}
{footer}
</svg>"##,
        header = header,
        identity = identity_section,
        pills = pills,
        stats = stats_section,
        topics = topics_section,
        sources = sources_section,
        footer = footer,
    )
}

/// Build professional tech stack pills for the card
fn build_card_pills(stack: &[String], start_x: f64, y: f64) -> String {
    if stack.is_empty() {
        return String::new();
    }

    let mut svg = format!(
        r#"  <g transform="translate({},{})">
"#,
        start_x, y
    );

    let mut x: f64 = 0.0;
    for tech in stack.iter().take(8) {
        let label = capitalize(tech);
        let escaped = xml_escape(&label);
        let text_width = label.len() as f64 * 7.2;
        let pill_width = text_width + 18.0;

        svg.push_str(&format!(
            r##"    <rect x="{x}" y="0" width="{w}" height="24" rx="12" fill="#1A1A1A" stroke="#2A2A2A"/>
    <text x="{tx}" y="16" fill="#A0A0A0" font-family="'JetBrains Mono', monospace" font-size="11">{label}</text>
"##,
            x = x, w = pill_width, tx = x + 9.0, label = escaped,
        ));
        x += pill_width + 8.0;
    }

    svg.push_str("  </g>");
    svg
}

/// Build horizontal topic engagement bars for the card
fn build_card_topics(topics: &[EngagedTopic]) -> String {
    if topics.is_empty() {
        return String::new();
    }

    let top = topics.iter().take(4).collect::<Vec<_>>();
    let max_pct = top
        .iter()
        .map(|t| t.percent_of_total)
        .fold(0.0_f32, f32::max);

    let mut svg = String::from("  <!-- Topics -->\n  <g transform=\"translate(32,244)\">\n");
    svg.push_str("    <text x=\"0\" y=\"-6\" fill=\"#555\" font-family=\"'Inter', sans-serif\" font-size=\"10\" letter-spacing=\"0.05em\">ATTENTION DISTRIBUTION</text>\n");

    for (i, topic) in top.iter().enumerate() {
        let y_offset = i as f64 * 28.0;
        let bar_width = if max_pct > 0.0 {
            (topic.percent_of_total / max_pct) * 500.0
        } else {
            100.0
        };
        let label = capitalize(&topic.topic);
        let escaped = xml_escape(&label);

        svg.push_str(&format!(
            r##"    <text x="0" y="{ty}" fill="#888" font-family="'Inter', sans-serif" font-size="11" dominant-baseline="middle">{label}</text>
    <rect x="120" y="{ry}" width="{bw}" height="14" rx="3" fill="#1F1F1F"/>
    <rect x="120" y="{ry}" width="{fw}" height="14" rx="3" fill="{color}" opacity="0.7"/>
    <text x="{px}" y="{ty}" fill="#666" font-family="'JetBrains Mono', monospace" font-size="10" dominant-baseline="middle">{pct:.0}%</text>
"##,
            ty = y_offset + 14.0,
            ry = y_offset + 7.0,
            label = escaped,
            bw = 500.0,
            fw = bar_width,
            color = ["#D4AF37", "#F97316", "#22C55E", "#3B82F6"][i % 4],
            px = 630.0,
            pct = topic.percent_of_total,
        ));
    }

    svg.push_str("  </g>");
    svg
}

/// Build source engagement chips for the card
fn build_card_sources(sources: &[SourceEngagement]) -> String {
    if sources.is_empty() {
        return String::new();
    }

    let mut svg = String::from("  <!-- Sources -->\n  <g transform=\"translate(32,370)\">\n");

    let mut x = 0.0_f64;
    for src in sources.iter().take(6) {
        let label = format!("{} ({})", src.source_type.to_uppercase(), src.items_seen);
        let escaped = xml_escape(&label);
        let text_width = label.len() as f64 * 5.8;
        let chip_width = text_width + 16.0;

        svg.push_str(&format!(
            r##"    <rect x="{x}" y="0" width="{w}" height="18" rx="4" fill="#141414" stroke="#1F1F1F"/>
    <text x="{tx}" y="13" fill="#555" font-family="'JetBrains Mono', monospace" font-size="9">{label}</text>
"##,
            x = x, w = chip_width, tx = x + 8.0, label = escaped,
        ));
        x += chip_width + 6.0;
    }

    svg.push_str("  </g>");
    svg
}

/// Export Developer DNA as a shareable SVG badge (GitHub stats card style)
pub fn export_as_svg(dna: &DeveloperDna) -> String {
    let date = if dna.generated_at.len() >= 10 {
        &dna.generated_at[..10]
    } else {
        &dna.generated_at
    };
    let identity = xml_escape(&dna.identity_summary);

    // Build tech stack pills
    let pills_svg = build_pills_svg(&dna.primary_stack);

    // Build stats row
    let stats = &dna.stats;
    let rejection_pct = format!("{:.1}", stats.rejection_rate);
    let stats_svg = format!(
        r##"<g transform="translate(20,96)">
    <text fill="#FFF" font-family="monospace" font-size="15" font-weight="600">{days}</text>
    <text fill="#666" font-family="sans-serif" font-size="10" y="14">days active</text>
    <text fill="#FFF" font-family="monospace" font-size="15" font-weight="600" x="120">{projects}</text>
    <text fill="#666" font-family="sans-serif" font-size="10" x="120" y="14">projects</text>
    <text fill="#FFF" font-family="monospace" font-size="15" font-weight="600" x="240">{rejection}%</text>
    <text fill="#666" font-family="sans-serif" font-size="10" x="240" y="14">noise rejected</text>
    <text fill="#FFF" font-family="monospace" font-size="15" font-weight="600" x="370">{deps}</text>
    <text fill="#666" font-family="sans-serif" font-size="10" x="370" y="14">dependencies</text>
  </g>"##,
        days = stats.days_active,
        projects = stats.project_count,
        rejection = rejection_pct,
        deps = stats.dependency_count,
    );

    // Build topic engagement bar (top 3 topics as stacked bar)
    let topics_svg = build_topics_bar_svg(&dna.top_engaged_topics);

    format!(
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="495" height="195" viewBox="0 0 495 195">
  <rect width="495" height="195" rx="8" fill="#0A0A0A" stroke="#2A2A2A"/>
  <text x="20" y="26" fill="#F97316" font-family="monospace" font-size="10" font-weight="500" letter-spacing="0.08em">4DA DEVELOPER DNA</text>
  <text x="475" y="26" fill="#666" font-family="sans-serif" font-size="10" text-anchor="end">{date}</text>
  <text x="20" y="52" fill="#FFF" font-family="sans-serif" font-size="16" font-weight="600">{identity}</text>
{pills}
{stats}
{topics}
  <text x="20" y="185" fill="#666" font-family="sans-serif" font-size="10">4da.dev</text>
  <text x="475" y="185" fill="#666" font-family="sans-serif" font-size="10" text-anchor="end">All signal. No feed.</text>
</svg>"##,
        date = date,
        identity = identity,
        pills = pills_svg,
        stats = stats_svg,
        topics = topics_svg,
    )
}

/// Build SVG tech stack pills positioned horizontally
fn build_pills_svg(stack: &[String]) -> String {
    if stack.is_empty() {
        return String::new();
    }

    let mut svg = String::from(r#"  <g transform="translate(20,62)">"#);
    svg.push('\n');

    let mut x: f64 = 0.0;
    for tech in stack.iter().take(6) {
        let label = capitalize(tech);
        let escaped = xml_escape(&label);
        // Approximate character width: ~6.6px per char at 10px monospace
        let text_width = label.len() as f64 * 6.6;
        let pill_width = text_width + 14.0;
        let pill_height = 20.0;

        svg.push_str(&format!(
            r##"    <rect x="{x}" y="0" width="{w}" height="{h}" rx="4" fill="#1F1F1F" stroke="#2A2A2A"/>"##,
            x = x, w = pill_width, h = pill_height,
        ));
        svg.push('\n');
        svg.push_str(&format!(
            r##"    <text x="{tx}" y="14" fill="#A0A0A0" font-family="monospace" font-size="11">{label}</text>"##,
            tx = x + 7.0,
            label = escaped,
        ));
        svg.push('\n');

        x += pill_width + 6.0;
    }

    svg.push_str("  </g>");
    svg
}

/// Build SVG stacked topic engagement bar
fn build_topics_bar_svg(topics: &[EngagedTopic]) -> String {
    if topics.is_empty() {
        return String::new();
    }

    let top3: Vec<&EngagedTopic> = topics.iter().take(3).collect();
    let total_pct: f32 = top3.iter().map(|t| t.percent_of_total).sum();
    let bar_width = 455.0_f32; // Total bar width

    let colors = ["#F97316", "#D4AF37", "#22C55E"]; // orange, gold, green

    let mut svg = String::from(r#"  <g transform="translate(20,135)">"#);
    svg.push('\n');

    // Background bar
    svg.push_str(&format!(
        r##"    <rect x="0" y="0" width="{}" height="10" rx="3" fill="#1F1F1F"/>"##,
        bar_width
    ));
    svg.push('\n');

    // Stacked segments
    let mut bar_x = 0.0_f32;
    for (i, topic) in top3.iter().enumerate() {
        let seg_width = if total_pct > 0.0 {
            (topic.percent_of_total / total_pct) * bar_width
        } else {
            bar_width / top3.len() as f32
        };

        let rx = if i == 0 { "3" } else { "0" };
        svg.push_str(&format!(
            r##"    <rect x="{x}" y="0" width="{w}" height="10" rx="{rx}" fill="{color}" opacity="0.8"/>"##,
            x = bar_x,
            w = seg_width,
            rx = rx,
            color = colors[i],
        ));
        svg.push('\n');
        bar_x += seg_width;
    }

    // Topic labels
    let labels: Vec<String> = top3.iter().map(|t| capitalize(&t.topic)).collect();
    let label_text = labels.join("  ·  ");
    svg.push_str(&format!(
        r##"    <text x="0" y="26" fill="#666" font-family="sans-serif" font-size="10">{}</text>"##,
        xml_escape(&label_text),
    ));
    svg.push('\n');

    svg.push_str("  </g>");
    svg
}

/// Escape XML special characters
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_capitalize() {
        assert_eq!(capitalize("rust"), "Rust");
        assert_eq!(capitalize("typescript"), "Typescript");
        assert_eq!(capitalize(""), "");
    }

    #[test]
    fn test_bar_chart() {
        assert_eq!(bar_chart(50.0).chars().count(), 10);
        assert_eq!(bar_chart(100.0).chars().count(), 10);
        assert_eq!(bar_chart(0.0).chars().count(), 10);
    }

    #[test]
    fn test_identity_summary_empty() {
        let summary = build_identity_summary(&[], &[]);
        assert_eq!(summary, "Developer (no stack configured yet)");
    }

    #[test]
    fn test_identity_summary_with_stack() {
        let stack = vec!["rust".to_string(), "typescript".to_string()];
        let deps = vec![DependencyEntry {
            name: "tauri".to_string(),
            project_path: "/home/user/project".to_string(),
        }];
        let summary = build_identity_summary(&stack, &deps);
        assert!(summary.contains("Rust"));
        assert!(summary.contains("Typescript"));
        assert!(summary.contains("desktop"));
    }

    #[test]
    fn test_infer_domain() {
        let stack = vec!["rust".to_string()];
        let deps = vec![DependencyEntry {
            name: "tauri".to_string(),
            project_path: "/test".to_string(),
        }];
        assert_eq!(infer_domain(&stack, &deps), "desktop");

        let ml_deps = vec![DependencyEntry {
            name: "pytorch".to_string(),
            project_path: "/test".to_string(),
        }];
        assert_eq!(infer_domain(&["python".to_string()], &ml_deps), "ML/AI");
    }

    #[test]
    fn test_export_markdown_structure() {
        let dna = DeveloperDna {
            generated_at: "2026-02-15T00:00:00Z".to_string(),
            primary_stack: vec!["rust".to_string(), "typescript".to_string()],
            adjacent_tech: vec!["cargo".to_string()],
            top_dependencies: vec![DependencyEntry {
                name: "tauri".to_string(),
                project_path: "/test".to_string(),
            }],
            interests: vec!["systems programming".to_string()],
            top_engaged_topics: vec![EngagedTopic {
                topic: "rust".to_string(),
                interactions: 50,
                percent_of_total: 45.0,
            }],
            blind_spots: vec![],
            source_engagement: vec![],
            stats: DnaStats {
                total_items_processed: 5000,
                total_relevant: 50,
                rejection_rate: 99.0,
                project_count: 3,
                dependency_count: 120,
                days_active: 30,
            },
            identity_summary: "Rust/Typescript desktop developer".to_string(),
        };

        let md = export_as_markdown(&dna);
        assert!(md.contains("# Developer DNA"));
        assert!(md.contains("Rust/Typescript desktop developer"));
        assert!(md.contains("## Primary Stack"));
        assert!(md.contains("`tauri`"));
        assert!(md.contains("99.0%"));
    }

    #[test]
    fn test_export_svg_structure() {
        let dna = DeveloperDna {
            generated_at: "2026-02-17T00:00:00Z".to_string(),
            primary_stack: vec!["rust".to_string(), "typescript".to_string()],
            adjacent_tech: vec!["cargo".to_string()],
            top_dependencies: vec![DependencyEntry {
                name: "tauri".to_string(),
                project_path: "/test".to_string(),
            }],
            interests: vec!["systems programming".to_string()],
            top_engaged_topics: vec![
                EngagedTopic {
                    topic: "rust".to_string(),
                    interactions: 50,
                    percent_of_total: 45.0,
                },
                EngagedTopic {
                    topic: "typescript".to_string(),
                    interactions: 30,
                    percent_of_total: 27.0,
                },
            ],
            blind_spots: vec![],
            source_engagement: vec![],
            stats: DnaStats {
                total_items_processed: 5000,
                total_relevant: 50,
                rejection_rate: 99.0,
                project_count: 3,
                dependency_count: 120,
                days_active: 30,
            },
            identity_summary: "Rust/Typescript desktop developer".to_string(),
        };

        let svg = export_as_svg(&dna);
        assert!(svg.starts_with("<svg"));
        assert!(svg.contains("4DA DEVELOPER DNA"));
        assert!(svg.contains("Rust/Typescript desktop developer"));
        assert!(svg.contains("Rust</text>"));
        assert!(svg.contains("Typescript</text>"));
        assert!(svg.contains("99.0%"));
        assert!(svg.contains("4da.dev"));
        assert!(svg.contains("2026-02-17"));
        assert!(svg.ends_with("</svg>"));
    }

    #[test]
    fn test_export_card_svg_structure() {
        let dna = DeveloperDna {
            generated_at: "2026-03-10T00:00:00Z".to_string(),
            primary_stack: vec!["rust".to_string(), "typescript".to_string()],
            adjacent_tech: vec!["cargo".to_string()],
            top_dependencies: vec![DependencyEntry {
                name: "tauri".to_string(),
                project_path: "/test".to_string(),
            }],
            interests: vec!["systems programming".to_string()],
            top_engaged_topics: vec![
                EngagedTopic {
                    topic: "rust".to_string(),
                    interactions: 50,
                    percent_of_total: 45.0,
                },
                EngagedTopic {
                    topic: "typescript".to_string(),
                    interactions: 30,
                    percent_of_total: 27.0,
                },
                EngagedTopic {
                    topic: "webassembly".to_string(),
                    interactions: 10,
                    percent_of_total: 9.0,
                },
            ],
            blind_spots: vec![],
            source_engagement: vec![
                SourceEngagement {
                    source_type: "hn".to_string(),
                    items_seen: 500,
                    items_saved: 25,
                    engagement_rate: 5.0,
                },
                SourceEngagement {
                    source_type: "github".to_string(),
                    items_seen: 200,
                    items_saved: 40,
                    engagement_rate: 20.0,
                },
            ],
            stats: DnaStats {
                total_items_processed: 8000,
                total_relevant: 80,
                rejection_rate: 99.0,
                project_count: 5,
                dependency_count: 180,
                days_active: 45,
            },
            identity_summary: "Rust/Typescript desktop developer".to_string(),
        };

        let svg = export_as_card_svg(&dna);
        assert!(svg.starts_with("<svg"));
        assert!(svg.contains("width=\"800\""));
        assert!(svg.contains("height=\"420\""));
        assert!(svg.contains("DEVELOPER DNA"));
        assert!(svg.contains("Rust/Typescript desktop developer"));
        assert!(svg.contains("45")); // days active
        assert!(svg.contains("99.0%")); // rejection rate
        assert!(svg.contains("ATTENTION DISTRIBUTION"));
        assert!(svg.contains("4da.ai"));
        assert!(svg.contains("All signal. No feed."));
        assert!(svg.ends_with("</svg>"));
    }

    #[test]
    fn test_card_svg_empty_data() {
        let dna = DeveloperDna {
            generated_at: "2026-03-10T00:00:00Z".to_string(),
            primary_stack: vec![],
            adjacent_tech: vec![],
            top_dependencies: vec![],
            interests: vec![],
            top_engaged_topics: vec![],
            blind_spots: vec![],
            source_engagement: vec![],
            stats: DnaStats {
                total_items_processed: 0,
                total_relevant: 0,
                rejection_rate: 0.0,
                project_count: 0,
                dependency_count: 0,
                days_active: 0,
            },
            identity_summary: "Developer (no stack configured yet)".to_string(),
        };

        let svg = export_as_card_svg(&dna);
        assert!(svg.starts_with("<svg"));
        assert!(svg.ends_with("</svg>"));
        // Should still render without crashing on empty data
        assert!(svg.contains("DEVELOPER DNA"));
    }
}
