//! Developer DNA — Shareable Technology Identity Profile
//!
//! Aggregates data from domain profile, attention tracking, knowledge gaps,
//! and source engagement into a single shareable snapshot of the developer's
//! technology identity. Think "Spotify Wrapped for developers."

use serde::{Deserialize, Serialize};
use tracing::info;

use crate::domain_profile;

// ============================================================================
// Types
// ============================================================================

/// Complete Developer DNA snapshot
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeveloperDna {
    /// When this snapshot was generated
    pub generated_at: String,
    /// Primary tech stack (from onboarding + ACE detection)
    pub primary_stack: Vec<String>,
    /// Adjacent/ecosystem technologies inferred from primary stack
    pub adjacent_tech: Vec<String>,
    /// Top dependencies from project manifests (notable ones only)
    pub top_dependencies: Vec<DependencyEntry>,
    /// Declared interest topics
    pub interests: Vec<String>,
    /// Top engaged topics from behavior (what you actually click/save)
    pub top_engaged_topics: Vec<EngagedTopic>,
    /// Knowledge blind spots (dependencies you use but don't track)
    pub blind_spots: Vec<BlindSpotEntry>,
    /// Source preferences: which sources you engage with most
    pub source_engagement: Vec<SourceEngagement>,
    /// Overall stats
    pub stats: DnaStats,
    /// Tech identity summary line (e.g. "Rust/TypeScript systems developer")
    pub identity_summary: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DependencyEntry {
    pub name: String,
    pub project_path: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagedTopic {
    pub topic: String,
    pub interactions: u32,
    pub percent_of_total: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlindSpotEntry {
    pub dependency: String,
    pub severity: String,
    pub days_stale: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceEngagement {
    pub source_type: String,
    pub items_seen: u32,
    pub items_saved: u32,
    pub engagement_rate: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DnaStats {
    /// Total items processed by the system
    pub total_items_processed: u32,
    /// Total items marked relevant
    pub total_relevant: u32,
    /// System rejection rate (as percentage, e.g. 99.2)
    pub rejection_rate: f32,
    /// Number of monitored projects
    pub project_count: u32,
    /// Number of unique dependencies tracked
    pub dependency_count: u32,
    /// Days since first use
    pub days_active: u32,
}

// ============================================================================
// Implementation
// ============================================================================

/// Generate a complete Developer DNA snapshot
pub fn generate_dna() -> Result<DeveloperDna, String> {
    let conn = crate::open_db_connection()?;

    info!(target: "4da::dna", "Generating Developer DNA snapshot");

    // 1. Domain profile
    let profile = domain_profile::build_domain_profile(&conn);

    let mut primary_stack: Vec<String> = profile.primary_stack.into_iter().collect();
    primary_stack.sort();

    let mut adjacent_tech: Vec<String> = profile.adjacent_tech.into_iter().collect();
    adjacent_tech.sort();

    let mut interests: Vec<String> = profile.interest_topics.into_iter().collect();
    interests.sort();

    // 2. Top dependencies (from project_dependencies, limit 30)
    let top_dependencies = get_top_dependencies(&conn)?;

    // 3. Engagement data (from feedback/interactions)
    let top_engaged_topics = get_top_engaged_topics(&conn)?;

    // 4. Blind spots (from knowledge gaps)
    let blind_spots = get_blind_spots(&conn)?;

    // 5. Source engagement stats
    let source_engagement = get_source_engagement(&conn)?;

    // 6. Overall stats
    let stats = compute_stats(&conn)?;

    // 7. Identity summary
    let identity_summary = build_identity_summary(&primary_stack, &top_dependencies);

    Ok(DeveloperDna {
        generated_at: chrono::Utc::now().to_rfc3339(),
        primary_stack,
        adjacent_tech,
        top_dependencies,
        interests,
        top_engaged_topics,
        blind_spots,
        source_engagement,
        stats,
        identity_summary,
    })
}

/// Export Developer DNA as shareable markdown
pub fn export_as_markdown(dna: &DeveloperDna) -> String {
    let mut md = String::new();

    md.push_str("# Developer DNA\n\n");
    md.push_str(&format!("**{}**\n\n", dna.identity_summary));
    md.push_str(&format!(
        "*Generated by [4DA](https://github.com/4da-dev/4da-home) on {}*\n\n",
        &dna.generated_at[..10]
    ));

    // Primary Stack
    if !dna.primary_stack.is_empty() {
        md.push_str("## Primary Stack\n\n");
        for tech in &dna.primary_stack {
            md.push_str(&format!("- {}\n", capitalize(tech)));
        }
        md.push('\n');
    }

    // Top Dependencies
    if !dna.top_dependencies.is_empty() {
        md.push_str("## Key Dependencies\n\n");
        for dep in dna.top_dependencies.iter().take(15) {
            md.push_str(&format!("- `{}`\n", dep.name));
        }
        md.push('\n');
    }

    // Interests
    if !dna.interests.is_empty() {
        md.push_str("## Interests\n\n");
        for topic in &dna.interests {
            md.push_str(&format!("- {}\n", capitalize(topic)));
        }
        md.push('\n');
    }

    // Top Engaged Topics
    if !dna.top_engaged_topics.is_empty() {
        md.push_str("## Where My Attention Goes\n\n");
        md.push_str("| Topic | Engagement |\n|-------|------------|\n");
        for topic in dna.top_engaged_topics.iter().take(10) {
            let bar = bar_chart(topic.percent_of_total);
            md.push_str(&format!(
                "| {} | {} {:.0}% |\n",
                capitalize(&topic.topic),
                bar,
                topic.percent_of_total
            ));
        }
        md.push('\n');
    }

    // Blind Spots
    if !dna.blind_spots.is_empty() {
        md.push_str("## Blind Spots\n\n");
        for spot in dna.blind_spots.iter().take(5) {
            md.push_str(&format!(
                "- **{}** — {} severity, {}d stale\n",
                spot.dependency, spot.severity, spot.days_stale
            ));
        }
        md.push('\n');
    }

    // Stats
    md.push_str("## Stats\n\n");
    md.push_str(&format!(
        "- Items processed: {}\n",
        dna.stats.total_items_processed
    ));
    md.push_str(&format!(
        "- Rejection rate: {:.1}%\n",
        dna.stats.rejection_rate
    ));
    md.push_str(&format!(
        "- Projects monitored: {}\n",
        dna.stats.project_count
    ));
    md.push_str(&format!(
        "- Dependencies tracked: {}\n",
        dna.stats.dependency_count
    ));
    md.push_str(&format!("- Days active: {}\n", dna.stats.days_active));

    md
}

// ============================================================================
// Internal helpers
// ============================================================================

fn get_top_dependencies(conn: &rusqlite::Connection) -> Result<Vec<DependencyEntry>, String> {
    let mut deps = Vec::new();
    let mut stmt = conn
        .prepare(
            "SELECT DISTINCT package_name, project_path FROM project_dependencies
             WHERE is_dev = 0
             ORDER BY package_name
             LIMIT 50",
        )
        .map_err(|e| format!("Failed to query dependencies: {}", e))?;

    let rows = stmt
        .query_map([], |row| {
            Ok(DependencyEntry {
                name: row.get(0)?,
                project_path: row.get(1)?,
            })
        })
        .map_err(|e| format!("Failed to read dependencies: {}", e))?;

    for row in rows.flatten() {
        deps.push(row);
    }
    Ok(deps)
}

fn get_top_engaged_topics(conn: &rusqlite::Connection) -> Result<Vec<EngagedTopic>, String> {
    // Pull from topic_affinities (learned behavior)
    let mut topics = Vec::new();

    let query =
        "SELECT topic, affinity_score FROM topic_affinities ORDER BY affinity_score DESC LIMIT 20";
    if let Ok(mut stmt) = conn.prepare(query) {
        if let Ok(rows) = stmt.query_map([], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, f64>(1)?))
        }) {
            let all: Vec<(String, f64)> = rows.flatten().collect();
            let total_weight: f64 = all.iter().map(|(_, w)| w).sum();

            for (topic, weight) in all {
                let pct = if total_weight > 0.0 {
                    (weight / total_weight * 100.0) as f32
                } else {
                    0.0
                };
                topics.push(EngagedTopic {
                    topic,
                    interactions: weight as u32,
                    percent_of_total: pct,
                });
            }
        }
    }

    Ok(topics)
}

fn get_blind_spots(conn: &rusqlite::Connection) -> Result<Vec<BlindSpotEntry>, String> {
    // Simplified: find dependencies we haven't engaged with recently
    let mut spots = Vec::new();

    let query = "
        SELECT pd.package_name, MAX(pd.project_path) as project_path
        FROM project_dependencies pd
        WHERE pd.is_dev = 0
        AND pd.package_name NOT IN (
            SELECT DISTINCT topic FROM topic_affinities WHERE weight > 0.3
        )
        AND LENGTH(pd.package_name) >= 4
        GROUP BY pd.package_name
        ORDER BY pd.package_name
        LIMIT 10
    ";

    if let Ok(mut stmt) = conn.prepare(query) {
        if let Ok(rows) = stmt.query_map([], |row| {
            Ok(BlindSpotEntry {
                dependency: row.get(0)?,
                severity: "medium".to_string(),
                days_stale: 30, // Approximate; would need temporal tracking for precision
            })
        }) {
            for row in rows.flatten() {
                spots.push(row);
            }
        }
    }

    Ok(spots)
}

fn get_source_engagement(conn: &rusqlite::Connection) -> Result<Vec<SourceEngagement>, String> {
    let mut sources = Vec::new();

    // Total items by source
    let query = "
        SELECT source_type, COUNT(*) as total,
               SUM(CASE WHEN id IN (SELECT item_id FROM feedback WHERE action = 'save') THEN 1 ELSE 0 END) as saved
        FROM source_items
        GROUP BY source_type
        ORDER BY total DESC
    ";

    if let Ok(mut stmt) = conn.prepare(query) {
        if let Ok(rows) = stmt.query_map([], |row| {
            let total: u32 = row.get(1)?;
            let saved: u32 = row.get(2)?;
            let rate = if total > 0 {
                saved as f32 / total as f32 * 100.0
            } else {
                0.0
            };
            Ok(SourceEngagement {
                source_type: row.get(0)?,
                items_seen: total,
                items_saved: saved,
                engagement_rate: rate,
            })
        }) {
            for row in rows.flatten() {
                sources.push(row);
            }
        }
    }

    Ok(sources)
}

fn compute_stats(conn: &rusqlite::Connection) -> Result<DnaStats, String> {
    let total_items: u32 = conn
        .query_row("SELECT COUNT(*) FROM source_items", [], |row| row.get(0))
        .unwrap_or(0);

    let total_relevant: u32 = conn
        .query_row(
            "SELECT COUNT(*) FROM source_items WHERE id IN (SELECT item_id FROM feedback WHERE action IN ('save', 'click'))",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    let rejection_rate = if total_items > 0 {
        (1.0 - total_relevant as f32 / total_items as f32) * 100.0
    } else {
        0.0
    };

    let project_count: u32 = conn
        .query_row(
            "SELECT COUNT(DISTINCT project_path) FROM project_dependencies",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    let dependency_count: u32 = conn
        .query_row(
            "SELECT COUNT(DISTINCT package_name) FROM project_dependencies WHERE is_dev = 0",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    // Days active: difference between earliest and latest source_items
    let days_active: u32 = conn
        .query_row(
            "SELECT CAST((julianday('now') - julianday(MIN(created_at))) AS INTEGER) FROM source_items",
            [],
            |row| row.get(0),
        )
        .unwrap_or(0);

    Ok(DnaStats {
        total_items_processed: total_items,
        total_relevant,
        rejection_rate,
        project_count,
        dependency_count,
        days_active,
    })
}

fn build_identity_summary(primary_stack: &[String], deps: &[DependencyEntry]) -> String {
    if primary_stack.is_empty() {
        return "Developer (no stack configured yet)".to_string();
    }

    let top_langs: Vec<String> = primary_stack
        .iter()
        .take(3)
        .map(|s| capitalize(s))
        .collect();

    // Try to infer domain from dependencies
    let domain = infer_domain(primary_stack, deps);

    format!("{} {} developer", top_langs.join("/"), domain)
}

fn infer_domain(stack: &[String], deps: &[DependencyEntry]) -> &'static str {
    let all: Vec<String> = stack
        .iter()
        .chain(deps.iter().map(|d| &d.name))
        .map(|s| s.to_lowercase())
        .collect();

    let has = |term: &str| all.iter().any(|s| s.contains(term));

    if has("tauri") || has("electron") || has("wry") {
        "desktop"
    } else if has("react-native") || has("flutter") || has("swift") || has("kotlin") {
        "mobile"
    } else if has("tensorflow") || has("pytorch") || has("scikit") || has("transformers") {
        "ML/AI"
    } else if has("kubernetes") || has("terraform") || has("docker") || has("ansible") {
        "infrastructure"
    } else if has("next") || has("nuxt") || has("svelte") || has("remix") {
        "fullstack"
    } else if has("react") || has("vue") || has("angular") {
        "frontend"
    } else if has("actix") || has("axum") || has("express") || has("fastapi") || has("django") {
        "backend"
    } else if has("embedded") || has("stm32") || has("esp32") {
        "embedded"
    } else if has("wasm") || has("webassembly") {
        "WebAssembly"
    } else {
        "systems"
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

fn bar_chart(percent: f32) -> String {
    let filled = (percent / 10.0).round() as usize;
    let empty = 10usize.saturating_sub(filled);
    format!("{}{}", "\u{2588}".repeat(filled), "\u{2591}".repeat(empty))
}

// ============================================================================
// Tauri Commands
// ============================================================================

#[tauri::command]
pub async fn get_developer_dna() -> Result<DeveloperDna, String> {
    generate_dna()
}

#[tauri::command]
pub async fn export_developer_dna_markdown() -> Result<String, String> {
    let dna = generate_dna()?;
    Ok(export_as_markdown(&dna))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_capitalize() {
        assert_eq!(capitalize("rust"), "Rust");
        assert_eq!(capitalize("typescript"), "Typescript");
        assert_eq!(capitalize(""), "");
    }

    #[test]
    fn test_bar_chart() {
        assert_eq!(bar_chart(50.0).chars().count(), 10);
        assert_eq!(bar_chart(100.0).chars().count(), 10);
        assert_eq!(bar_chart(0.0).chars().count(), 10);
    }

    #[test]
    fn test_identity_summary_empty() {
        let summary = build_identity_summary(&[], &[]);
        assert_eq!(summary, "Developer (no stack configured yet)");
    }

    #[test]
    fn test_identity_summary_with_stack() {
        let stack = vec!["rust".to_string(), "typescript".to_string()];
        let deps = vec![DependencyEntry {
            name: "tauri".to_string(),
            project_path: "/home/user/project".to_string(),
        }];
        let summary = build_identity_summary(&stack, &deps);
        assert!(summary.contains("Rust"));
        assert!(summary.contains("Typescript"));
        assert!(summary.contains("desktop"));
    }

    #[test]
    fn test_infer_domain() {
        let stack = vec!["rust".to_string()];
        let deps = vec![DependencyEntry {
            name: "tauri".to_string(),
            project_path: "/test".to_string(),
        }];
        assert_eq!(infer_domain(&stack, &deps), "desktop");

        let ml_deps = vec![DependencyEntry {
            name: "pytorch".to_string(),
            project_path: "/test".to_string(),
        }];
        assert_eq!(infer_domain(&["python".to_string()], &ml_deps), "ML/AI");
    }

    #[test]
    fn test_export_markdown_structure() {
        let dna = DeveloperDna {
            generated_at: "2026-02-15T00:00:00Z".to_string(),
            primary_stack: vec!["rust".to_string(), "typescript".to_string()],
            adjacent_tech: vec!["cargo".to_string()],
            top_dependencies: vec![DependencyEntry {
                name: "tauri".to_string(),
                project_path: "/test".to_string(),
            }],
            interests: vec!["systems programming".to_string()],
            top_engaged_topics: vec![EngagedTopic {
                topic: "rust".to_string(),
                interactions: 50,
                percent_of_total: 45.0,
            }],
            blind_spots: vec![],
            source_engagement: vec![],
            stats: DnaStats {
                total_items_processed: 5000,
                total_relevant: 50,
                rejection_rate: 99.0,
                project_count: 3,
                dependency_count: 120,
                days_active: 30,
            },
            identity_summary: "Rust/Typescript desktop developer".to_string(),
        };

        let md = export_as_markdown(&dna);
        assert!(md.contains("# Developer DNA"));
        assert!(md.contains("Rust/Typescript desktop developer"));
        assert!(md.contains("## Primary Stack"));
        assert!(md.contains("`tauri`"));
        assert!(md.contains("99.0%"));
    }
}
